
= ROI
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

==== 坑与坑是不一样的. 不是所有的失败都是成功之母. 什么才是"有价值"的失败?

坑与坑是不一样的. 有的坑(编程)你可以填平; 有的坑(设计)你只会陷死在里头, 并不会因你有多少决心和热情而能跨过.

.不是所有的失败都是成功之母， 那些"有价值"的失败, 它们必须具备3个前提条件:
[%collapsible%open]
====
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.必须**具有清晰的评判标准**, 而非像艺术那样玄学, "文无第一武无第二".
|可量化. +
"运营"本身不是个具有"标准化"的职业. 那你就很难总结成"课程". 因为个人理论色彩浓厚的课程, 很难普世. (这和"设计"这种工作是一样的)

|2.可重复, *可复现, 可复盘*
|投资（炒股）行为有一个特点，赚了钱常常不知道是怎么赚的，亏钱也不知道是怎么亏的，或者说**总结的那些原因, 没有可重复性。无法从成功中总结经验，也无法从失败中总结教训，这只能叫"经历", 而非"教训"。**

|3.损失是可控的
|能实施“快速失败”策略的前提, 是你对失败的亏损, 能拥有"可控性". 否则, 该策略就会变成一个黑洞: 一开始以为只是一个小小的投入，最后却变成“葫芦娃救爷爷"，全部搭进去了.
|===

'''
====


==== 付出了代价, 就要拿到相应回报 (贼不走空)

.付出了代价, 就要拿到相应回报 (贼不走空)
[%collapsible%open]
====
- 付出了代价, 就要拿到回报. 花了时间, 就要拿到收益 (ROI),(贼不走空). 反之, 如果不存在回报(或回报是虚拟的, 只会"转瞬即逝"), 就不要去投入.

- 思考「如何使工作对我有意义」，比死磕「我的工作有什么意义」更有意义。

- 学习中遇到的问题, 在你解决后, 必须将"解决过程中的思路, 和采坑教训"记录下来, 复盘. 即, *结果不重要, 如何想出"解决思路"的过程, 才是最有价值的! 如果没有复盘，你 90% 的功夫白费了 —— 你花了不少时间，读了不少代码，除了拿到一个结果外，并无太大的"掌握了解决问题的方式"收获。*

- 提高复盘频率: **在做事的当时，遇到各种问题，你做出过的各种失误, 就要立刻把"领悟"记录下来，**随遇随记，用最小迭代法，最高频率的提升自己。

'''
====



==== 做不同的事, 职业, 会带给你不同的投资回报率 ROI

.用两个骰子得到"点数总和"的每个值, 成功概率是不同的
[%collapsible%open]
====
两个骰子加起来:  +
→ 等于5点的概率, 是 1/9.  +
→ 等于2点和12点的概率最小, 是1/36.  +
→ 中间7点的概率最大, 是 1/6.  +
我们发现, *这11种情况并不是等概率的.*

'''
====

.老板与打工人的不平等待遇
[%collapsible%open]
====
- 赵云老了, 还要出征. 刘备老了, 享受荣华.
- 将军在关键性的大战中失败一次, 就可能被军法斩首，而诸侯老板, 如曹操等, 遭遇大败,  则不会受任何影响.  可见，老板和打工的，所享受的机会数量, 有着天生的不公平. 对老板来说, 除非他的势力灭亡, 否则不会掉脑袋, 永远有下一次机会. 而对于打工人来说, 有一次失败, 可能就不会有下一次机会了.

- 打工人占1%股份, 老板占50%, 公司市值从100万涨到10亿, 打工人多赚几万, 老板多赚上亿.

'''
====


.★ 好职业的特征
[%collapsible%open]
====
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|-> 有门槛, 有护城河
|- 门槛是好事, *对你难的, 对别人也难. 而只要你翻过了这堵高墙, 这堵墙就会变成保护你, 去挡住别人进来.*
- 网上公开能学到的(设计, 程序员)，都没有门槛和护城河. 网上学不到的(医生, 律师)，才有真正门槛.

|-> 不是青春饭, 能做到老
|

|-> 自带"磁场价值"效应(提供是所有人的刚需服务)
|- 你做的, 是所有人一辈子的刚需, 你才不会没饭吃, 职业才能稳固。而且这些刚需不需要你出去推销, 而是别人会主动找上门来的. 如: 医生，司法，公安，律师，教师工作. 显然, 这些大多是提供公共服务的体制内工作。统治者垄断这些既"具为刚需, 又有光环"的工作，说明他们看得很穿.
- 能让你当别人的大脑! 而不是别人当你的大脑, 你只变成工具人.
- 老师,律师,医生, 都是你教育别人, 别人听你的. 为什么在发达国家, 医生会同律师、法官一样，成为收入最高的职业? 从终极意义上说，这都是主宰人的命运的人，角度不同而已。

|-> 其经验, 能用在你退休后的日常生活中.
|- 真正的好工作要满足一个重要要求：你在这个工作中学到的技能与思想领悟，必须能够用在你的实际生活中，能提高你解决生活问题的能力。否则，一旦你离开原先的工作行业 (比如失业, 退休后)，它的经验对你一点价值也没有, 它离个人的日常生活太远，你无法用它来给你带来生活上的帮助。
|===


'''
====


.★ 水源越广大, 水管越滋润
[%collapsible%open]
====
清廷成立"总理衙门", 本来只是主持外交的，但后来包干了所有与洋人有关的事务 : +
- 跟洋人有关的商务你管不管？得管。现在的外交部管商务吗？不管. 但当时中国还没有商务部，只有让总理衙门来管了。 +
- 牵涉外国传教士的宗教事务，也得由总理衙门来管。 +
- 无论是"官办"的还是"官督商办"的工厂, 都需要从西方购买机器，招募洋人技师. 这个本来也不属于外交，但跟洋人有关，它也得管。 +

**所以"总理衙门"本来只是个临时机构，但后来编制和规模越来越庞大，**就变成永久机构了。本来只是办外交的，后来随着洋务运动的推行，**中国无论什么事，都开始和洋人沾边，这就使它变得几乎无所不管。以至于后来的"军机大臣"必须得兼任"总理衙门"大臣了，否则就只能去管理那些既没有洋人活动，也没有多少钱的偏远地方 ——谁愿意干那种差事?**

(**所以跟着欧美走，有前途。就像一个水管，另一端衔接了大洋，于是水管也会越来越粗, 越来越向阳, 和有前途**.)

'''
====

.用报纸(公共媒体平台)发声, 带来声望
[%collapsible%open]
====
- 甲午战争后, 西方瓜分中国的念头开始. 中国的应对之策就是加快变法. 中国第一次办报纸的高潮就在甲午之后.《国闻报》、《时务报》等风靡天下，**通过办报纸发声, 这样话语权就掌握在这些呼吁变法的士人手中。** +
梁启超之所以在变法之前即声名大噪，就在于他主持过一段时期的《时务报》。**梁启超凭借《时务报》这一平台，极大地放大了他自己的声音和名望。**借助《时务报》，梁启超的名声便超过了他的老师(康有为)。

'''
====

.设计这种工作, 找参考图, 你的ROI是0
[%collapsible%open]
====
画面设计这种工作, 是没有内涵的, 你被花花绿绿的画面吸引一天, 看过即忘, 头脑依然空空. 因为画面不像看书一样对你有思想收获 (有精神食粮感)!

设计上的画面，你看参考，比如花瓣，*每张花花绿绿的画面会吸引你一两秒中, 然后当你看下一张时, 上面那张就被你忘却, 你重新被新的一张所吸引一两秒钟. 然后一直循环这个过程. 所以你看一天时间，也不会记住任何内容. 因为画面本身是没有内涵的, 徒有漂亮的外观,* 会短暂吸引你. 广告画面就像糖精, 只有甜味(只愉悦你的眼球), 没有营养成分(不包含你的精神粮食).

画面甚至连短视频都不如, 短视频或许还有可怜的一点点信息含量的, 而广告平面画面上是完全没有任何"有价值的阅读内容"存在的, 只有广告信息! 本质上这张画面就是服务于垃圾信息的. +
所以很多4a广告会把画面故事化，就是为了让人看过后能记得点什么。而不像地产画面等都是抽象化，抽离故事，就只剩下视觉刺激，只能走眼睛，而不会走内心。（留不下任何记忆）。

*而你去看书，你看一天时间，是真的能有收获的，你能记得它里面讲的故事, 理论, 逻辑，因果，原理等。* +
 所以你看一天花瓣，就是浪费一天时间，看过即忘，而无所得。*而你看365天数学教材，你都学会了, 考研都考上了！而你看365天花瓣，你的脑袋依然空空如也！*

'''
====


- 好的, 成功概率更高的专业和职业, 就是比低的职业更能上岸！

- 理科能润

- 男怕如错行. 越是吃人深坑的入口处，越是铺满了最迷惑人的鲜花, 来引诱你陷进去

.★★ **越是巨坑的陷阱入口处, 越铺满了最诱人进来的鲜花.**
[%collapsible%open]
====
- 社会一直有需求，但是又无利润的工作，自然就要制造各种舆论谎言，不断的让人入坑.

'''
====




==== *每一个赛场对于你是否'普通'或者'别致'的判断,都有不同的判定标准*

.*每一个赛场对于你是否'普通'或者'别致'的判断,都有不同的判定标准*
[%collapsible%open]
====
你小时候你手脚麻利勤快。街坊四邻看见你三五岁就开始帮你妈做家务，都觉得这不是个普通孩子。当时的你像极了内个下蛋勤快的鸡A。 +
上学以后你出落的蛮漂亮。不但仰慕者众多，历次做汇报演出你都是没有争议的舞台C位。校领导说你不是个普通孩子。当时你像极了内个毛色炫丽的鸡B。

你回忆起人生的各个阶段，你都曾经不普通过，因为每个阶段的大环境，他人都只关注到你与该环境相符的你的特质。 +
可是你后来走上社会了。你发现老板才不会关注你之前的那些人生阶段里是否有勤劳，是否有绚烂，是否有努力。他只关注肉质鲜美。你没有, 你在这就只适合当个螺丝钉。

人的一生，每个生命从生到死，都会经历若干个赛场. 每一个赛场对于你是否普通或者别致的判断，都有不同的判定标准。 +
如果你有本事，可以进入, 并在那个“可以证明你不普通”的赛场里浸淫一生，你就是成功的. 如果你没做到, 则泯然众人是每个人最终的归宿。

'''
====

- 我见过一个人的简历, 上学时可谓出类拔萃, 中考在学校第一名, 拿过各种作文比赛一等, 二等奖项, 可谓人才. 但工作后, 十几年, 做的却是经营公司公众号. 我看得真是很感慨.


