
= 如何选择主题
:sectnums:
:toclevels: 3
:toc: left
//:stylesheet: myAdocCss.css

---



.把你的主题, 和人的生活中更有价值的东西(人生观,价值观, 世界观,人性矛盾)联系起来.
[%collapsible%close]
====
主线(是用一句话概括故事情节), 主题(一定是和一个"更大价值的加东西"联系在一起的. 即该故事表达出的一种人类可贵的精神,价值观.)

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|例如：某高考题: "齐桓公、管仲和鲍叔三人你对哪个感触最深？"
|该思考可以如下: 齐桓公任命管仲，起初遭到了拒绝，齐桓公把他追了回来，这才有了后来的拜相。诸葛亮也是刘备三顾茅庐而来。   +
管仲的传奇故事, 其实就是中国知识分子想要成为的人物, 他们也希望能被"明主识才". 那么从这一点上,  就可以来谈谈中国的“贤臣”梦。 这个平台, 就明显比单纯就管仲这个人"就事论事", 立意要高得多。

|主线(情节): 服刑了 26 年的江西“杀人犯”张xx, 被xx省高级人民法院宣告无罪.
|主题(价值观):

- **关键词: “污名” ** +
第一，因为她的前夫是一名“杀人犯”，一定会遭到当地人的说三道四；
第二，在张服刑期间，她改嫁了，这点在传统农村是很难被人接受的，同样会受到歧视。
- **关键词: “信念”. ** +
因为尽管自己被污名化，26 年来，张的前妻依然四处奔走，支撑她的一定有一种信念，而这个信念是可以打动人的。

综上分析，我们就可以确定文章的主线了：一名“杀人犯”的前妻，在流言蜚语之下，凭借着某种信念，在长达 26 年的时间里为前夫伸冤，最终成功。 +
总结来说，主线就是通过“一句话原则”，先确定价值（找关键词），再高度概括。
|===

怎么从一个现象或者人物, 拎出来一个好主题, 或者找到一个好的角度呢？-- 你想表达的主题，一定要和某个更大价值的东西联系起来。

这个更大的东西, 可以是一种情感，比如爱、孤独.  +
可以是一种观念，比如自由、平等  +
可以是一种对做法的反思: 比如对公共安全的拷问等.

*这些, 都是对人活着, 具有重要意义的东西 （是人都会需要去追求的东西）.* -- 如同电影编剧一样, 创作的故事, 要反映人性和困境, 才具有现实性意义. 才会在受众中产生共情.


'''
====

.如何找到这个"更大价值"的东西呢？有两种方法
[%collapsible%close]
====
如何找到这个"更大价值"的东西呢？有两种方法:  +
1. 以专业研究中的各种关键词, 作为讨论主题.  +
2. *因果链追溯法, 一层层往上游追溯, 直到找到一个具有"高价值含金量"的问题点.*

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.以专业研究中的各种关键词, 作为讨论主题.
|比如, 谈“散装卫生巾”这个话题.

- 性别角度: 男性如何看待这个问题.

- 政治层面角度: *可以从"政策"的角度去分析问题点.* 地方政府都出台了一些政策，这些政策, 围绕"经期女性"都提供哪些政策支持? 共同点在哪里, 不同点在哪里? 不足在哪里, 执行难点在哪里?
由此，我们可以确定一个主题：地方政策当中经期女工的权利保护。

- 经济层面角度: **经济学上, 重点考察哪些变量因素呢? -- 价格、税收、贫困、经济福利等. ** +
我们先来思考, 为什么会有“散装卫生巾”出现? 对其原因一步步溯源:   +
是为了降低购买成本吗?  -> 为什么太贵? -> 原因之一: 税收高. 在中国, 卫生巾的征用税率是 13%，这是增值税里最高的一档。 -> 为什么税收高? -> 无法降低的原因是什么?     +
*这些溯源链条上的一个个问题, 其实就构成了一个明确的主题 : 女性摆脱“月经贫困”的阻力在哪？*

- 文化层面角度: 同样先思考, 文化研究中, 有哪些常见的关注点.   +
-> 比如"女性主义". 如果从这个点切入的话, 我们就可以从"父权制社会"的角度, 来讨论男权社会下的女性议题困境。   +
-> "文化禁忌"角度, 来讨论 "月经禁忌".  +

- 考察他人的关注点视角: 一个热点事件, 在翻看他人的评论之前, 先思考一下, 你自己能想到几个角度? 然后再去看评论, 看看人家想到了哪些你没想到的角度。这个方法对"扩充你视角范围", 帮助非常大.


|2.因果链追溯法, 一层层往上游追溯, 直到找到一个具有"高价值含金量"的问题点.
|比如, 某高速出口, 老是发生车祸事故.   +
我们来分析这个问题的原因 : 除了常见原因外. 有一个奇怪的现象 : 既然司机知道车辆失控了，为什么很少有车辆主动开进避险车道，避免事故的发生呢？不断去追溯因果链.
|===


'''
====

."独到的见解", 本身即是有价值的.
[%collapsible%close]
====
在如今这个人人都能成为自媒体的时代, 写作的主题越来越同质化，如果没有一个独到的主题，你写的东西就很难脱颖而出。  +
*所谓独到，就是指作者看到了一些读者没有注意到的东西(性质). 读者的视线需要经过作者引导, 才能看见。 即, 读者只能借着你(作者)的智慧和思考，犹如戴上神奇眼睛一样, 他们才能看到新的方面.*

'''
====






