
= 影响力 and 说服
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''



.先建立信任, 后才有可能发展关系
[%collapsible%open]
====
人与人, 你与陌生人之间的关系, 肯定是从最冷, 最敌意, 再到熟悉亲近的. 所以你生活中遇到陌生人对你恶语相向, 是非常符合这个心理逻辑的.

'''
====

.做生意之前, 首先要建立起别人对自己的信任
[%collapsible%open]
====
*做生意之前, 首先要建立起别人对自己的信任. 换位思考: 你不相信别人, 你就不会放心去和别人做金钱交易.*

- 在对方心中还未建立起你的亲和性、可信度和权威感的情况下，就想说服对方, 是很少会成功的.
- 如果说客户只认识到了你的价值，但是并没有建立起对你的信任，一切就不会有下一步进展。
- 某些药，是为别的药服务的，它们被叫作“药引子”；同样，*某些沟通，是作为预备性的, 目的是为了让接下来的沟通更顺畅. 即, 在开展实际对话之前，我们有很多准备工作要做；在对话从浅水区. 渐渐迈向深水区的过程中，我们需要先建立起情感联系, 与基本共识.* (即: 郭德纲的"闲白"所起的功能)
所以, 那些演讲时，上台就急着煽情或者下结论的演讲者, 是不会有效果的.
- 双方已然失去了基本的信任，没有这个误会它也得有那个误会，没有事它也会生出事儿来。(两国关系也是如此)

'''
====

.必须先建立情感, 然后才有可能说服对方.
[%collapsible%open]
====
- 异性之间，顺序是: 先喜欢一个人的性格特质，然后才会对其肉体（性）产生兴趣，而非顺序相反。 不首先对一个人产生心理上的喜欢，是不会对其肉体产生爱的。
- 郭德纲再说评书前, 必先和观众闲白, 就是这个原因, 先建立起双方情感连接, 对方才会听你说事.
- 她说某品牌的安装师傅到家装空调, 会带一块布把这个地擦干净. 我说这块布要贵10％，*这块布擦的不是你们家地板，擦的不是你们家的机器，擦的是客户的心。*

'''
====

.情感是流动的
[%collapsible%open]
====
- 关系就如逆水行舟，如果没有得到改善、维持和发展，就会随着时间而衰退。人与人的关系不是变热就是变冷，没有保持不变的中间的关系。
- *任何一个运动系统如果要持续稳定地运行，必须要有持续稳定的能量源源不断地注入；否则，系统就会紊乱(熵增)，甚至崩溃。婚姻也是运动的系统，它若要持续稳定的运行，也需要持续稳定的能量源源不断地注入。*
- 感情是流动的，因而必须要有不流动的合同来规范我们的行为(做生意上)。

'''
====

.★ *把社交看做吃饭、睡觉一样自然。不需要什么心理负担.*
[%collapsible%open]
====
- 社交就像吃饭、睡觉一样重要，同样，也应该像吃饭、睡觉一样自然。*不要对它抱着过高的期待和目标，把它放低一点，让它成为你生命中一件自然而然的事情，把它跟你的形象、评价、标准松绑。*
- 你很难喜欢上嘉宾, 可以这样操作: 别把他想象成一个真人，你们可能这辈子都不会再见面了，你就当采访一个NPC（非玩家角色），就隔离那个情感。

- 对方也在乎你对他们的看法. 台上表演者, 也希望台下观众能与自己互动越热情越好. 而不是收到冷场.

'''
====

.*不要欺骗别人，能被你骗到的都是相信你的人。*
[%collapsible%open]
====

'''
====

.*要想人与人之间做事能顺利的话, 必须先建立"处理问题"的机制(如同"合同"的逻辑一样)*
[%collapsible%open]
====
- 夫妻之间应该建立一种就矛盾冲突进行讨论的机制（平等地位、就事论事, 相同权利）。如果没有机制, 很快地，争吵的焦点就不是本来要讨论的事情，而是“对方的态度如何不对”这种"机制"上的问题了. (所以, 美中两国对话, 就要先建立起双方对话的机制, 双方先达成共识.)

'''
====

.(人气)传播的背后是情绪。能激发人情绪的东西, 会被参与, 并传播.
[%collapsible%open]
====
- 根据"消费者体验的心理动线", *要对这六个关键时刻(场景): 感知→接触→触动→行动→消费→分享, 来进行布局(进行说服性动作) . 这其实就是研究广告的人总结出的一个模型而已.*

'''
====

.*在公共舆论上, 少数人密集持有的”激情观点”, 能够抵消(击败)大量冷漠的人的”温和,无所谓态度的观点”*
[%collapsible%open]
====
- 对某一事物或现象, 能够影响政治家的, 永远是那些"充满激情的，密集"发声的少数群体, 而不是"沉默的, 或持无所谓态度的"大多数. 即少数的“炙热”的观点, 在任何时候都能击败大数的“温和”的观点。 +
在许多问题上，普通大众因为缺乏相关知识, 或缺乏明确的意见，这时, 少数人的密集关心，就可能会主导民意测验的结果。 +
*所以, 所谓的“公共”舆论，永远只是一个小团体的观点, 而不代表大众的想法.*

- 网络骂战不像实际战争, 战争能通过消灭敌人的肉体, 来彻底让他们不再能够发声. 而网络骂战不行. 骂不死敌人, 他们是永远能够”卷土重来”的. 所以, 双方从来不能够一方完全压倒另一方.

'''
====



