
= action
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 行动


.行动是唯一能令你移动人生位置的
[%collapsible%close]
====
- 自己认为很重要(表现在头脑里), 和清晰认识到很重要(表现在行动上)，往往不是一回事。

'''
====

.★ 你缺乏行动的最大原因是 : 你对"你的现实处境"还抱有虚假的幻想
[%collapsible%close]
====
- *人的见解越成熟，在政治上的幻想就越少. 清醒的人不会指望独裁领袖行善，只会指望他不搞破坏。*

'''
====

.星星之火，可以燎原
[%collapsible%close]
====
星星之火，可以燎原. 一个小想法只要你天天想着，就会越来越变成动力做它，然后跨出第一步, 就会跨第二步，越行越专业！ +
但前提条件是，你要心里要永远惦记着（荆轲刺秦里面，秦始皇说，“朕一刻也不敢忘 历代先君一统天下的大愿!”）。否则，你的注意力就会被拉离这一点上. 比如你心里如果想着别的非上岸的东西（比如视频编辑学习之类），就会把你的注意力拉离上岸。没有燃烧你的星星之火, 没有实际去行动, 你永远停留在原地, 所以你永远缺乏入职条件。

'''
====

.不要站在原地哭，即使哭泣，也要在移动中哭泣。
[%collapsible%close]
====
- 不要站在原地哭，即使哭泣，也要在移动中哭泣。工作、吃饭、运动、休息、社交……再难过，这些该做的事情还是要做。因为秩序生活本身会帮你复原。*走着走着，你会发现，让你掉泪的事已经在你身后了。*

- 易中天: 面对一条大河，许多人都不敢过去。我却摸着石头一步步的走了过去，*当别人嘲讽我说，你看这人弄的是一身泥泞，满身臭水的时候，打不起！我已经在河对岸了！你们还在河那边！*

- 前进是一步步做出来的，那些身有多套房的人，是一套套投资买出来的！

- *力无所用, 与无力同，勇无所施, 与不勇同，计不能行, 与无计同。*---- 努力没有用到实处就跟没有努力一样，有勇却没有施展就跟没有勇一样，有计却没有施行就跟没有计一样。

'''
====

.★ 要做“难而正确的事”.
[%collapsible%close]
====
- 要做“难而正确的事”. *否则, 你有一万个理由说服自己不去做, 因为它不是你正确的路.*

- 你做某事, 自己得兴奋(有追求)。如果你自己都做得不兴奋，那成果也许还能看，但绝对不会成。

- 金钱不能使你快乐，不要认为你有钱后就一定会快乐。*如果你在致富的过程中没有感到快乐的话，就不要希望你富有之后会快乐起来。记住，不论你是穷人还是富人，首先要让自己快乐。*

- 能不曲线救国, 就不要绕着走. *如果你绕着走, 费的能量，远远超过你直接面对它耗费的能量，而且你的青春不就蹉跎了吗？*

'''
====

.★ "有意义的失败", 远比"无意义的成功"有价值
[%collapsible%close]
====

'''
====

.★★★ 能打败你敌人的不是你的说辞(你不要幻想能说服他人), 而是你永不停下的行动 (既成事实大于一切)
[%collapsible%close]
====
- 人是不可能被说服的 (人只会被自己陷入的困境所打服). 屁股决定脑袋, 站位决定态度
- 预测未来最好的方法，就是去创造它。—— 林肯
- 英雄是"正在形成的事物"的捍卫者，而不是"已经形成的事物"的捍卫者，因为他就是"正在形成的事物"。 ——约瑟夫·坎贝尔

- 战士死了的时候，苍蝇所首先发见的是他的缺点和伤痕，嘬，营营地叫，以为得意，以为比死了的战士更英雄。但是战士已经死了，不再来挥去它们。
的确的，谁也没有发见过苍蝇们的缺点和创伤。然而，有缺点的战士终竟是战士，完美的苍蝇也终竟不过是苍蝇。

'''
====

.世上没有不被攻击的人, 每个人是每个人的敌人
[%collapsible%close]
====
- *有不虞之誉，有求全之毁.*  +
虞：预料。有意料不到的赞誉，也有过分苛求的诋毁。所以毁誉不必太在意。

- *善操理者-不能有全功，善处身者-不能无过失。* +
善于处理事理, 尚且不能完全成功. 善于修身的人, 尚且不能没有过失。 +

- 百善孝为先，论心不论迹，论迹贫家无孝子；
万恶淫为首，论迹不论心，论心终古少完人。 +
真正孝顺与否, 这个主要看心，不是看表面行为，不是说锦衣玉食给父母就是孝顺，假如这样的话，那么清贫的人家就没有孝子了。  +
真正好色与否, 这个主要看行为，不是看心，假如按心念论，世人都免不了面对美色动心，这样的话，世上就没有一个完美无缺的人了。

- 一人难称百人心
- 人上一百，形形色色shai。 人上一万，无边无沿.
- 一路玩意 惊动一路主顾, 一路宴席 款待一路宾朋。

- *政治家不惧怕人们的责备，但惧怕人们的轻蔑。这代表他在个人素质上不被承认。*

- 曾国藩:  +
天津的教会育婴堂和别处的一样，都会搜集和抚养孤儿，而且会对那些主动送来孤儿的人给予一定的奖励，算是辛苦费。但是有一些人渣，为了这几个钱，就拐卖正常人家的孩子送过去。当被人抓住时，这帮无赖马上就找理由，说是教会的育婴堂让他们干的(栽赃陷害)。于是就激起民愤。人们冲进育婴堂，把嬷嬷们杀了，把育婴堂也砸了。法国领事来处理, 结果互相动起手来, 死了几个中国人，法国领事也被人打死. +
清廷没人愿意出面负责处理这件事情, 最后就只能曾国藩出面处理，但这种事情谁处理谁倒霉. 曾国藩”实事求是”地查，发现没有之前中国人传言说的那些事. 曾国藩本来极高的名望，经此事后一落千丈。(所以也不要怪西方人自己保护自己侨民的做法, 那时中国人不靠谱.)

- 慈禧 : +
甲午惨败，每个人都骂西太后，整个国家、朝野上下都逼着她退位。 +
当时李莲英也被人骂得很狠，其实李莲英没有干预过朝政. 当然这并不意味着他没有权力.

- 袁世凯: +
袁世凯当选正式大总统以后，就把国会给抛弃了——追缴国民党议员的代表证书，然后就把他们驱散了。而**国民党代表当时占国会多数，现在他们一走，国会投票无法构成最基本的法定人数，就等于废掉了.** 这是袁世凯的错招，如果觉得议员不行，应该重选国会代表.  +
袁世凯的确因为签了《二十一条》而声望大跌。

'''
====

.机会是留给有准备的人的
[%collapsible%close]
====
- 机会是留给有准备的人的，即，只要你平时每天做好了准备，就随时都有"走人"和"上位"的机会.  +
→ 你平时每天都在学习锻炼数学英语，就能随时去考研； +
→ 你平时每天都在针对性, 有意识的锻炼"考公"必需的能力，如演讲, 和待人接物，你就能随时去考公。

'''
====

