
= 谋事者
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 谋事者

.对于真正做大事(做大家业)的人来说，难, 阻力大, 敌人多, 他就会不干了吗？ 真正的懒惰，是头脑懒惰。
[%collapsible%close]
====
- 长年累月的刷手机不但荒废了学业，更荒废了对人生的思考 (永恒的转移了对自己大事的注意力). 他们没有考虑过前途大事，他们什么都不想，也什么都没做，就稀里糊涂地几年刷手机过去了，一到毕业，才发现没了去路。  +
农村孩子的主要问题是“不想事”。能力低，学历低，还不想事，这是很多青年最糟糕的地方。“裸奔”着走出校门，却又经受不住社会的毒打，到最后败给生活，甚至放弃生命。

- 大部分生活中的困苦, 只是你长期脑懒累积下来的最终结果而已。脑懒毁全家。

'''
====

.★★ 人的一生, 你要考虑哪几种事情? -- 人(性), 事(道), 事(术)
[%collapsible%close]
====
*人在一生中的核心认识, 归根结底只有三种: 1.对人类构成的社会的认识(人性). 2.对具体某个人的认识(观人, 识人), 3.对如何做事的认识(方法论, 及对未来走势的判断)*

'''
====

.★★★ 如果你能做到超出行业中的传统认知, 你就是开拓者了
[%collapsible%close]
====
在与日俱增的运营大军中，*更多人缺乏的是统观行业上下游的运营思维高度，以及跳出具体岗位外，对这个职业的想象力* (即: 这个职业的内涵, 其实也是个"筐", 它里面该包含什么内容, 它将来该怎么发展, 不是由别人定义的, 而是由你自己来定义的!)。

'''
====

.分娩通常不会跟着计划走，你自己要有所准备。(预则立, 不预则废)
[%collapsible%close]
====
- 关键是阶段式计划性。你有没有想过未来三年，你会如何度过？未来三年，有什么关键节点？这些关键节点上的变化，你都会如何应对？你有没有应对的招数？你有没有抗风险的安排？(可能发生的国家战争, 运动)

- 有plan B了，我就能安心执行plan A了。

- 从创业的第一天起，你作为创业者都要有这个心理准备，每天要思考自己未来的10年、20年要面对什么. 你现在碰到的倒霉的事情，在这几十年遇到的困难中，只会是小小的一部分。

'''
====

.你一直考虑什么, 你就会成为什么
[%collapsible%close]
====
想把一件事做好，就只能把这个行业里所有的事情打通。即: 要像项目负责人一样思考。我哪怕只是为了写好当时的一条段子，我也得像这个节目的制片人一样思考。*事实是, 如果你一直像制片人这么思考的话，你最后就是会变成制片人。*

'''
====



== 创建自己的 理论/方法论"架构大树"

.你被启发出来的思考, 价值要远远超过你看到的思想
[%collapsible%close]
====
- **看书最重要的收获,** 不是为了书上所写的内容，而**是你在看书时，被启发思考出来的你自己的观点。正是这些观点**, 才导致书上那些事情和研究的后来发生. 出发点是万物之源, 没有出发点，就不会发生之后的一切政治思想，思考，理论.

'''
====

.★★★ 对任何"事物"做出你自己的判断, 都要问4个问题
[%collapsible%close]
====
1. 它存在的意义和价值是什么? 即, *它是为了解决什么问题, 而存在?* 为什么它必须要存在? *它(该理论, 该方法)的同类竞争对手有哪些? 其他事物能替代它吗 ?*

2. *它宣称能针对解决的问题, 这些问题重要吗? 价值度如何?*

3. 它是如何做到的? 方法是什么? *背后的原理是什么?* 底层逻辑是什么? 心理学依据是什么? *每个方法的ROI如何? 成功率如何? 优点和缺点分别是什么?* 使用场景的前提要求是什么?

4. 没有一个理论是完美无缺的. 对同一个问题, 经常不同高人间的观点(所站角度), 也会彼此不同 (这在政治学领域很常见). 那么你就要特别注意**他们(即竞争性理论)彼此间的批判, 观点逻辑如何. 对对方理论的漏洞, 挖掘深度如何? 犀利度如何,** 一针见血吗? 令你拍案叫绝吗? 并以此来补足你的思考漏洞, 和理论框架.

理论的思想演变历史, 能让我们知道它一路在解决的缺点.  +
不迷信任何理论, 就去查看它一路演过来的思想史. (背后的逻辑演变链条, 前因后果, 渊源发展路径). *因为每一次发展更新, 都是它试图解决自己原先的缺陷.*

image:../img/0041.svg[,]

'''
====

.创建你自己的一颗大树, 建立你自己的"理论架构树"!
[%collapsible%close]
====
- 各科都有自己的理论框架模型，就像一棵棵不同长相的大树. 你不可能记住世上所有的树（各种学科的各种理论框架），而且未来还会永远有新树出来. 但你一定能记住你自己, 从零创造出来的这一棵树 (自己的框架)！ 即, 你能以你的“一”，来统其他的“万“。 +
将管理学的书,找出里面的所有模型, 把前人总结出来的模型， 用MECE法则, 来重新分析拆解,组装到你自己的"理论架构树"上. +
*每个阶段的问题, 有每个阶段的思维模型(解决方法).*

- 一棵树上的叶子万万千（各种规律现象发现），我们去单独直接记忆所有的叶子是错误的. 我们要理解弄懂的, 是更少的树干，树枝(即"本源出发点"). 正是树干, 推导出了树枝, 树枝又推导出了树叶.

- 只记底层的本质逻辑. 而不要抄别人的原话.

- 要翻译成自己的话, 你才能记得住.

- 做书籍笔记, 不要啰嗦, 只要提取出解决问题的"思维模型(模块)"即可. 并且画图出模块系统.

'''
====

.如果世上还没有我关心的主题的"方法论", 我就建立自己的"方法论".
[%collapsible%close]
====
我不能因为世上还没有某方法论，我就一直在等待. 别人没做方法论的，我就自己创建自己的方法论。这样我事事才不会停下脚步，停滞不前。

'''
====



== 复盘

.不复盘, 就意味着光采坑了, 而什么教训都没从里面学到
[%collapsible%close]
====
- 经历了文革，国人没有反思，就走不出食人部落，文革重演的所有元素都存在了下来.

'''
====


