
= 过程和结果, 手段和目的, 战略和战术
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


.★★ 各个"点"必须能够串联起来, 形成累加势能.
[%collapsible%close]
====
- 所谓战略, 就是在你的大方向下, 各个"点"必须能够串联起来, 形成累加势能。 如果你在各种方向上布满了各种产品，*彼此却不能借力, 以至于每个单点都只能单独去与对手竞争, 你就会非常吃力.* (这和人生是一样的, 你在人生中所做的任何事情, 必须对你的最终目标有累加推动效果. 即, 不要去积累你不想积累的, 对你"上岸"没有用的经验!)

'''
====

.★ 战术的目标，就是赢。而战略的目的，是我推动当前的均衡向下一个均衡点转化，并使自己在下一个均衡点中，那个优势稍微大一点点。
[%collapsible%close]
====
- 毛泽东有句话 ： “谁是我们的朋友，谁是我们的敌人， 这是革命的首要问题 。朋友搞得多多的，把敌人搞得少少的， 革命就赢了。” 这是一种典型的战术思维。

- 梅特涅讲过一句名言，他说， *我控制欧洲局势的心法其实就是一条，就是确保所有国家之间的矛盾， 要大于他们和奥地利之间的矛盾。* +
就是敌人和朋友搞清楚有那么重要吗？ 大家都有矛盾，但是这个矛盾都有化解的可能，只要**我确保你们之间的矛盾，大于你们和我之间的矛盾，你们就会永远争取我的支持，** 所以我奥地利虽然国力不强，但是我就是控制欧洲的局势。这就叫战略思维。

- 中国人经营南海，主张”搁置争议，共同开发”。原来的均衡是， 我要在主权这个矛盾下, 和菲律宾这样的国家去谈什么国际法、海洋法，没准儿还把美国招进这个格局来，这个谈法我是吃亏的。 +
所以我搁置它，**我推动这个均衡往下一个均衡去转化，**转化矛盾到什么？——我们共同开发。 开发远洋海岛这个东西你以为容易啊，**这是比拼国力，所以就能导致我的优势扩大。矛盾就转化到对我有利的那个主场上来了。**你美国人总不能来共同开发吧，你根本不是南海的周边国家。

'''
====

.不要把"方法"当做"目的"本身!
[%collapsible%close]
====
你要以这个目的来做: “我要写比以前更好的段子”, “不知道能不能行，但是我试试”。 我不会在乎这一场和那一场的观众的不一样. 我只会想今天哪里有问题，是不是可以更好。 +

你必须思考这个问题，我们上台演出的目的是什么？是为了伺候好哪一场，哪一天的观众吗？ 我们当然要为演出效果负责，但你上台的出发点不该是这个， 你的目的始终是 — 成为更强的脱口秀演员。  +
即, 最终目的是: 通过逗笑观众来磨砺自己，而不是逗笑观众。 "逗笑"只是你利用的工具而已. **不停演出的目的，是为了磨练自己，而不是为了炸场。**炸场只是副产品，名利也是副产品。

**人是目的，不是手段。**这不只是一种道德要求，也是很理性的结论。**如果你的表演是为了让观众笑的话，你就成了手段，你变成了工具。**拿自己当手段，你顶多掌握二流手段。拿自己当最终目的，你才有机会掌握一流手段。 你是你自己的目的。 +
*同样, 我也不会关心这家公司的死活. 人最终是要成就你自己这个人的。你不能把自己的命运和某个公司绑在一起。做大事的人，一定是要把自己和自己的伟大事业绑在一起去做的。*


- *你学习并使用各种思维模型, 来分析解决工作, 商业等问题, 也并不只是为了该问题本身, 而是为了借助它们来训练你的大脑思维方式!* +
*把案例研究当哑铃, 你的目的不是哑铃, 而是锻炼你肌肉* (大脑思维认知, 及建立你自己"方法论大树"的食材)


- 我是在学JavaScript吗？不, 我在学的是"函数式编程"的思想逻辑，单独为了学一门编程语言对我没用, 但编程思想却是相通的"底层逻辑思考方式".
- 你学的是背后的做菜方法，而不是去记那些做出来的菜本身！
- 你学的不是那几首歌, 而是发声技巧

'''
====


