
= 演讲
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== 我的个人总结

.我的个人总结
[%collapsible%open]
====
- *不需要系统化讲解，删掉所有不重要的观点，只说几个重点*（系统化结构写在ppt上就行了，演讲时不重要的点一语带过，说话时间放在重要的点上）
- 面对不同的听众，要用不同的讲解精简方式。不要用教育讲课的方式，*不要对一个概念反复重复讲 -- 即, 不要用"画素描"的方式, 从粗到细地反复勾轮廓; 而要用"毛笔白描"的方式, 一笔过, 精准, 不来回勾。
- 重要的观点和举证案例，记下来，讲时别遗漏，否则就失去精彩点了。* (*不要翻来覆去讲同一个意思, 你拍自己的讲课短视频就知道了, 同一个意思(比如ps中蒙版的意思)前后反复讲, 会非常令观众厌倦和觉得啰嗦, 浪费观众的时间*)
- *话语安排别啰嗦.*
- 别"词不达意".
- 无关的话题，故事，不要在会议上说，不要浪费大家时间，可以私下聊。
- 不要把所有的你要讲的内容都写在ppt上，这就剧透了，导致听众会用“看”的而不是“听”你讲，他自己就全看完了。所以，ppt上只写关键词就够了，别把逻辑因果解释都写上去。逻辑解释必须听你说！

'''
====


== 演讲(道)

.脱口秀就是制造“改变的幻觉”
[%collapsible%open]
====
- *人天然喜欢看成长，你要用五分钟的时间成长给他看，观众也会感觉自己在"成长"(幻觉)。 也许观众过几天就忘了, 但脱口秀就是制造“改变的幻觉”。*

- 脱口秀故事, 类似于电影中的主角. 五到十分钟的讲述之后，你需要有一个成长变化.  +
成长可以是你理解了你的父亲，走出了失恋阴影，也可以是戏弄了你愚笨的老板。  +
或者, 你也可以没解决任何问题，但是，你通过这五分钟让观众知道，你意识到了人生的无解 ——这也是一种成长，智慧的成长。

'''
====

.你有没有实现一上来就让观众觉得我是自己人? 即, 先卸下他人对你的防御感, 他们才会继续听你说下去 (如, 郭德纲)
[%collapsible%open]
====
要让人愿意相信你说的, 你的真诚是第一位的。要让对方接受你，心理上拉近彼此，敲门砖只能是情绪 (情感, 攻心为上)。之后, 你的说服, (价值观呈现), 才能对他人发挥作用. 检视自己 : 有没有一上来就让观众觉得我是自己人? (即亲和力, 如郭德纲就有对观众的亲和力)

'''
====

.(脱口秀)你的目的是为了"共鸣", 而不是去”改变”尽可能多的人。
[%collapsible%open]
====
很多演员在看完别人的表演后会说，“他没啥毛病，就是没劲儿。” 那就是没有投入情绪，或者你俩没有共鸣。

'''
====

.暴露, 不是为了把真实隐私说出来，而是"还原"那份心情。
[%collapsible%open]
====
- 表演老师在教表演时，会强调演员在台上要学会保护自己(无论是演反派角色, 还是悲惨人物)，要记住舞台上都是假的，你进入的是角色，虽然你要用真情实感来演，但下了台要尽快抽离。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|脱口秀演员怎么抽离, 保护自己呢？
|我的办法是: 做到**只保证情绪永远是真的. 其他的文本可以是编造的，对人生故事可以做修改。** +
脱口秀表演中的自我暴露, 是有分寸的暴露. **暴露, 目的不是为了把真实隐私说出来，**而是把那种情绪带到舞台上。**是"还原"那份心情。** 故事的真实性并不重要, 怎么改头换面其实都可以， 关键是从中的"情绪"是真的.  +
讲故事，还原那个故事的目的, 其实你是在"还原"那个情绪.

|关键是"还原"，不要"表演". **能用演的就不要讲，能代入角色就不要冷眼旁观。**
|方法就是**把你要说的情境, "还原"在眼前。让听你说话的人仿佛看到了一样。情境本身的真假不重要, 我们的表演任务，就是让它变成真的。** +
能用演的就不要讲. *把那些啰唆的话语都删掉。你的目的是"还原"那个情境，而不是"告诉"大家发生了什么事。*

比如我说 “昨天我跟我爸说，爸，上海户口办下来了”, “啊，怎么做到的”，而不是说，“我爸就问我，那你是怎么做到的”。这句话没有必要，直接就开始表演就好。
|===

- 脱口秀行业有一句话：一个人摔跤的时候是可笑的，但是当一个人摔出血了就不好笑了。

'''
====


== 演讲(术)

.听众最多能记住7个要点, 但推荐只说3个点.
[%collapsible%open]
====
实验证明，一次记住3个要点最容易，记住7个要点需要比记住3个要点多15倍的努力，而记住10个要点就需要比记住3个要点多50倍的努力！所以，不能一下子输出太多的内容，小份高频的输入才有利于听众记忆。

麦肯锡对总结提炼的要求, 是要简化到几个要点呢？自然就是最容易记住的3点。有个笑话说，麦肯锡内部发言的开场白都一样，都是清一色的“我有3点看法……”如果有第4个要点要说，那就拆分成3a和3b，依然是以“我有3点看法”开场，然后补充“第3点分为两部分”。 +
所有事情都应尽量简化，但不能损失原味。

给别人讲述核心要点, 会强迫我们内化信息, 并用对方能听懂的语言将其重构. (其实就是翻译成你自己的话语说出来，看出其背后通用的底层逻辑.)

'''
====

.以15分钟为一单元
[%collapsible%open]
====
- 人能够集中精神“听一件事情(即"干货")的单元，大概是15分钟。之后的15分钟左右, 他可以听些不要紧的闲话、扯谈之类的。之后你再讲下一件干货事情, 依次循环。(番茄时间法, 一个单元是 25分钟) (15分钟, 不正好是比较长的短视频的时长么, 有其道理)

- 一场演讲，能让人记住三件事，已经是非常好的演讲了。剩下的时间，你就是逗他们开心，勾起他们的兴趣.
如果在相聚的两小时里面，你有三次让对方开心的笑，那对方应该是绝对不会记得你曾经提过几个无聊的话题的。


'''
====

.故事, 是拆解成"小情境"与"大情境"的
[%collapsible%open]
====
你讲的故事, 可以拆解成小情境与大情境

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|小情境: *就是你的一个又一个段子，你在用这些小情境, 反复证明与拓展自己的价值观。*
|如果你有个段子经常忘，我的经验就是别讲。说明你就是不喜欢它。

|大情境: 就是你对整条线的主持.
|*这是三个小情境，你中间要有一个逻辑线把它串起来的。大情境就是我怎么把这些串起来，能体现你人格的完整性, 和你的"成长".* +
*要有"起承转合",* 就是你写的不能是趣事堆积，*也不能是你几个不相干的好段子联排。你在五到十分钟里要完成层层推进，要有主题有人物有冲突，最终有一个像结局的结局。*
|===

'''
====

.节奏感
[%collapsible%open]
====
一个人的节奏感，就是这个人在一个时间线上, *对信息量松弛的一个整体把控能力。*

一定要让观众在心理上跟你是一头儿的，*首先必须先"同步"，情绪，共鸣，都是为了同步。 接着, 一定还要"引领"，让观众对你表演的预测落空。还要无限循环, 不停找到同步，做出一点点引领，打破，重建，再同步，再引领。这过程光想一想你就知道它是有节奏的。*

听段子的过程中，你在等，就是"铺垫"; 你等到了，就是"梗"。  +
没等到，就是垮了.   +
如果你等的过程中走神了，那就是他没铺好。

有的演员是梗比较密，铺垫接梗，铺垫接梗，铺垫接梗. 有的演员是会铺很长，然后出来一个特别大的梗。 这就是不同的表演节奏.  +
**所谓的节奏就是嗒嗒/嗒，嗒嗒/嗒，有的人就是喜欢嗒嗒嗒嗒/嗒，也有的人就是喜欢嗒/嗒，嗒/嗒。** +
*好的脱口秀表演，节奏都是变的。如果是五分钟，你可以一直嗒嗒/嗒，嗒嗒/嗒，嗒嗒/嗒，但你要是超过十五分钟用一个节奏，观众会疯的。*

'''
====

."能掌控人心理"的手段(表达技巧), 都要掌握下来
[%collapsible%open]
====
对于"能激起你的某种感受"的写作技巧, 把这些感触, 和作者实现它的手段, 都记录下来.

'''
====
