
== (价值观) 如何对待自己的人生


== 我是谁


.★★★*人最怕的是没有个性。你的差异性都没有了，客户怎么会选择你？*
[%collapsible%open]
====
- **遇到比你有钱的人，请不要自动的卑躬屈膝，除非…他有要把他的钱给你… 而通常有钱人，并不会把钱送给随便就对他们卑躬屈膝的人。**

- **人最怕的是没有个性。 没有个性，你就只能做别人的影子或者传声筒。都不用说你的优势在哪里了，你的差异性都没有了，客户怎么会选择你？**(我们要让别人, 无论他是客户, 朋友, 对象, 知道我们的独特，这一点非常重要。)

- 电视上每个主持人，如果都只是拷贝其他之前的主持人的讲话的方式，哪里会有这么多各式各样的主持风格来？大家都长一个样子，分不出谁是谁了。 +
**同质化艺人过多，会降低每一个偶像的不可替代性，**最终导致粉丝社群的黏性下降，缩短每一个偶像产品的变现周期。 +
(所以“设计师主不要有自己的风格？“你只会变成可无缝替换的标准件螺丝！自我阉割。这句话完全是站在资本方立场做出的，对资方有利，而不利于设计师本人）

- 如果是千篇一律的作品，有什么必要存在？总是要有点不一样的内容.


'''
====

.*★★ 话语权即政治， 表达出的话语即政治. 是你很重要的权力！*
[%collapsible%open]
====
- 每个人都偏爱自己的主张——不是因为这是他(她)想出来的，而是该主张与他(她)的潜在信仰和偏好(即价值观)相适应（相一致）。
- *我的看法未必对别人有影响, 但对自己却很重要。这表达了你自己的价值排序, 好恶、爱憎，等等。*
- “那是他的价值观，我说的是我的！”
- 这一类问题往往并没有谁对谁错，关键要逻辑自洽. (但**逻辑自洽, 不等于就是真相.** 柯南探案中逻辑是自洽的, 但作品故事依然是编的)

'''
====

.斗争精神是生而为人的核心
[%collapsible%open]
====
- 不为自己的权利而战，你一生都将是个懦夫，被世界上那些恃强凌弱的人推来搡去。


- 如果别人对你没有善意，你就要做出反击.（**不要让他在他的头脑中形成你不希望的负面经验：你软弱可欺。不要让他人形成对你不该有的条件反射**）。

- Don’t give them the satisfaction of being insulted. **不要让他们从侮辱你中得到成就感.**

- **于不可已而已者，无所不已。于所厚者薄，无所不薄也。** 对于不应该停止的却停止了，那就没有什么不可以停止。 对于应该厚待的却薄待了，那就没有什么不可以薄待。

- **一旦坏了规矩，开了个坏头，一旦有了第一次，后面就会有第二次，第三次。(有一就有二, 有二就有三)**

- 台湾: "**我们相信软弱会招致侵略**".

- **我们最终会被人的坚强性格能力所吸引, 他的艺倒是其次的.** 我们为什么会被郭德纲吸引? 因为他的奋斗精神, 当他陷入困境时(因私下报销而成被告事件,陷入抄袭网络段子事件)的强大的求生欲爬出来的精神, 与敌人战斗(嘴仗)不认输的精神. **在这种强烈的战斗精神下, 他的优秀才艺能力的吸引力, 反倒显得其次了, 黯然失色了.** 于是最终, 郭德纲就成了一个既有才艺能力, 又有不服输的性格魅力的人.

- 他们替我加薪的主要原因, 是因为我能“舍命”保护自己的权益。“*一个能保护自身权益的人，就一定能保护公司的权益。因为你是一个不会向阻力和障碍妥协的人.*” (想想董明珠, 王志安, 接班的企二代, 林肯, *越是成名的人, 越是敌人众多, 越是经常被网暴, 他们也越是有斗争精神, 能向前推进. 因为他手下的几万甚至百万员工, 都指望着他排除敌人阻力开疆拓土, 一家老小才能吃上饭* )

- 因为你能保护手下的利益, 他们愿意跟你, 才能不吃亏. ( 想象中国历史上的军阀节度使)

- 当一件产品既可以卖600元，也可以卖300元，那么人们便会觉得它只值300元。

'''
====


.对家人的责任
[%collapsible%open]
====
- **如果你不把重心放在家庭上，又有什么家庭可言呢？**你们不是一家人——你们只是同居的伴侣。

- **你是否在很多情况下，担心其他事物，其程度要超过对自己或孩子成长及情感关系的重视？**

- 要让所有人在任何事情中, 面子上过得去, 不让他们在任何场合难堪. 这就是会说话. +
xx的疏忽在于不该当着孩子的面说。妈妈的话使儿子当当自尊心深受伤害。

- 真正的夫妻双方关系, 不是借你(男方)的高枝来炫耀我(女方)自己，也不是我(女方)牺牲掉来增加你(男方)的高度或衬托你的威仪，而是相互敬爱。


'''
====

.对他人, 正确的自我站位:
[%collapsible%open]
====
→ 面对陌生人，是站在他们的上有老下有小的家人之后。   +
→ 面对熟人，是站在他们的老公或老婆之后（时时刻刻想到他们家人关系网），而非仅你们两个人面对面的存在. 唯如此，你才能超脱于"陷入与对方的情感纠葛”之外！你要跳出来, 作为外人, 第三方旁观者, 你才能看清楚: 在外人看来”你和有家室的人家”是何等的狗血剧情. +
你与同事之间都没有情感欠债, 彼此都不欠什么, 轻松点好.

'''
====




== 我的人生使命



.★★★ **人生的任务, 是要去解决你生活中更多的问题，而不是只盯着一两个问题解决到最好(所以不要去追求完美的方法)**
[%collapsible%open]
====
- 正如你一路长大, 都不是"恋爱专家","育儿专家", "教育专家", "父母专家", "买房专家", "买车专家", 但你却一路解决了很多人生大事. 这正是你的人生任务! 必须要完成的. 很多事情我们只需要赢，而并非必须做到完美。 因此, 你要追求去解决"更多问题"(成为事事60分的管理者, 而不是成为只能做一件事的100分的专家), 即, 不断向管理层上走, 向"上方"走, 而不是在"平行线"上走.

- **事实上, 即使是只一件事, 也是永远也做不到"完美"的. 你也只是暂时在这个舞台上, 会交棒给后来者. 所以, 相反, 你要追求去解决"更多问题",** 即, 不断向管理层上走, 向"上方"走, 而不是在"平行线"上走.

- 每个阶段的问题, 有每个阶段的思维模型(解决方法), 所以我们要对每个问题的解决方式, 进行"建模".


'''
====

.★★ 人的一生, 你要考虑哪几种事情? -- 人(性), 事(道), 事(术)
[%collapsible%open]
====
- *人在一生中的核心认识, 归根结底只有三种: 1.对人类构成的社会的认识(人性). 2.对具体某个人的认识(观人, 识人), 3.对如何做事的认识(方法论, 及对未来走势的判断)*

- 认知，几乎是人和人之间唯一的本质差别。*技能的差别是可量化的，技能再累加，也就是熟练工种。而认知的差别是本质的，是不可量化的。*

'''
====

.对于真正做大事(做大家业)的人来说，难, 阻力大, 敌人多, 他就会不干了吗？ 真正的懒惰，是头脑懒惰。
[%collapsible%open]
====
- 长年累月的刷手机不但荒废了学业，更荒废了对人生的思考 (永恒的转移了对自己大事的注意力). 他们没有考虑过前途大事，他们什么都不想，也什么都没做，就稀里糊涂地几年刷手机过去了，一到毕业，才发现没了去路。  +
农村孩子的主要问题是“不想事”。能力低，学历低，还不想事，这是很多青年最糟糕的地方。“裸奔”着走出校门，却又经受不住社会的毒打，到最后败给生活，甚至放弃生命。

- 大部分生活中的困苦, 只是你长期脑懒累积下来的最终结果而已。脑懒毁全家。

'''
====

.★★★ *你是否意识到自己的部分性格特点, 影响到了你的某些思考和行为习惯? 并改变自己的这些局限性条件反射?*
[%collapsible%open]
====
- 你往上走得越高, 同时也会看清自己的尚缺之处. **你要思考你承担更大的挑战时，必须得到修正和完善的性格中的一些基本缺失是什么?**

- **反思, 自己当前的格局、视野和心性, 能否能够支撑这家公司走得更远?** 这就是你身一个企业家需要具备的责任感和气质担当。

- 随着团队和公司的发展，也越发意识到“如果你不能突破自己的瓶颈，就会成为整个团队的天花板”的意义.

- **人人都有自己的功课要做，那些没有做好的和欠下的，终归要“还”。**

- 没有哪一件称得上顺利、轻松和成功，但也没有哪一件不是在帮我补足自己身上的短板和缺失. 而且, 你努力后还能收获很多意料之外的发现，那不是按部 就班就能得到的。 这才是生命的乐趣. 你生命中很多美好的东西，往往不是被给予和创造的，而是被你意外发现的。

- 无论做什么事, 哪怕是你不喜欢的, 你也可以选择从多种不同的视角去看待它，并在每一种视角下得到全然不同的意义. 并从与未知的互动中, 获得持续的发现收获. 物尽其用.

'''
====





.★ 要做“难而正确的事”.
[%collapsible%open]
====
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|对你不喜欢的工作, 一旦遇到困难, 你一定会很快放弃
|- 要做“难而正确的事”. *否则, 你有一万个理由说服自己不去做, 因为它不是你正确的路.*
- 你做某事, 自己得兴奋(有追求)。如果你自己都做得不兴奋，那成果也许还能看，但绝对不会成。
- 金钱不能使你快乐，不要认为你有钱后就一定会快乐。*如果你在致富的过程中没有感到快乐的话，就不要希望你富有之后会快乐起来。记住，不论你是穷人还是富人，首先要让自己快乐。*


|如果你上错了梯子, 做了你不喜欢的职业, 即使你升职了, 也不会解脱
|- 你行业的工作模式和盈利模式在这放着的，你即使不做具体工作，以后也是指挥别人做这些事情。
.. 设计是糟糕的工作, 即使当了领导, 也是管理这些糟糕的工作.
.. 物业管理本质还是一个低层次的劳动密集型行业（保安、扫地阿姨、设备维护工人），同业排名前30名之间的服务标准和品质之间, 没有巨大的区别. 不像互联网科技企业那样, 技术之间差距巨大.

|能不曲线救国, 就不要绕着走.
|-  *如果你绕着走, 费的能量，远远超过你直接面对它耗费的能量，而且你的青春不就蹉跎了吗？*
|===

'''
====

.★ "有意义的失败", 远比"无意义的成功"有价值
[%collapsible%open]
====

'''
====

.★★ 真正的好工作(好职业)必须达到的条件有哪几条?
[%collapsible%open]
====
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2
|-> 看归宿是否能善终
|- **越是巨坑的陷阱入口处, 越铺满了最诱人进来的鲜花.** +
社会一直有需求，但是又无利润的工作，自然就要制造各种舆论谎言，不断的让人入坑.

- 归宿决定一个人的命运和前程。因此, **选兴趣和职业，一定要先看这些职业, 各自的终极归宿是什么。** 如果你不喜欢那些归宿, 你一开始就不要进入它!
.. 设计走技术路线的话, 终点归宿是导演, 你想当导演么? 不想的话, 一开始就不要进入做设计!

- **你想知道你老后会怎样, 就看看现在身边的老年人, 是怎样的状态. 未来会怎样, 其实在身边就可知，只怕你"视而不见"。**



|-> 有门槛, 有护城河
|- 网上公开能学到的(设计, 程序员)，都没有门槛和护城河. 网上学不到的(医生, 律师)，才有真正门槛.
- 韩国医学采取的英文授课模式, 使韩国医生具有"赴海外行医"的资本。自医师罢工开始以来(韩国政府威胁要吊销罢工医师的医师执照)，赴美的出国咨询增加了 7～8 倍.


|-> 不是青春饭, 能做到老
|作为历史长河中的一条连贯到未来的线，技术是永远在发展的，这决定了你有限的生命，不可能解决所有的技术问题。所以, 你只能占据这条无限的发展线上的 一段时间，掌握住 一段技术前沿，然后把技术交接给后来人。(任何一个奥运冠军都必将退役, 但体育技术的发展却不会停下脚步.)    +
你去哪呢？ 管理岗位。因为**人性是自古不变的，更具有稳定性。** 历史书中的人性故事，对现在也是有启迪的。**所积累的管人经验, 能用到老。而不像技术那样迭代极快，积累的经验, 很快就会过时无用。**

|-> 自带"磁场价值"效应(提供是所有人的刚需服务)
|- 你做的, 是所有人一辈子的刚需, 你才不会没饭吃, 职业才能稳固。而且这些刚需不需要你出去推销, 而是别人会主动找上门来的. 如: 医生，司法，公安，律师，教师工作. 显然, 这些大多是提供公共服务的体制内工作。统治者垄断这些既"具为刚需, 又有光环"的工作，说明他们看得很穿.
- 能让你当别人的大脑! 而不是别人当你的大脑, 你只变成工具人.
- 老师,律师,医生, 都是你教育别人, 别人听你的. 为什么在发达国家, 医生会同律师、法官一样，成为收入最高的职业? 从终极意义上说，这都是主宰人的命运的人，角度不同而已。

|-> 其经验, 能用在你退休后的日常生活中.
|- 真正的好工作要满足一个重要要求：你在这个工作中学到的技能与思想领悟，必须能够用在你的实际生活中，能提高你解决生活问题的能力。否则，一旦你离开原先的工作行业 (比如失业, 退休后)，它的经验对你一点价值也没有, 它离个人的日常生活太远，你无法用它来给你带来生活上的帮助。


|===

'''
====



.官僚体系让人发挥作用的最大上限，是这个职位所要求的最高技能，而不是这个人的最大才能. 所以要尽可能的往上走（《白色巨塔》财前五郎）
[%collapsible%open]
====
- 即使是做运营工作, 如果一个公司它对运营的期待, 就是定期生产出标准的内容、做些活动、维护促活核心用户，**这类架构给予运营师的可操作性空间, 就非常有限。**(所以刘备不会久居人下, 必须要有自己能自主的空间, 地盘.)

- 这个岗位, 是我还是别人来做, 不会有任何区别. 她的性格、能力、处事方式, 在工作中能够发挥的自主空间很少，公司只是给电脑找个暂时按键的主人。

- **在其位才能谋你政！你想要自由地执行你自己的意见观点** (并历练, 用实践证明, 并修炼完善 你的价值判断眼光)，**必须向上爬.**

- **爬高几层，有助于看出自己的处境，从哪来，往哪去，别人的道路有何不同，等等不爬高就看不见的事。**

- **我不断往上爬, 不是为了被世界看见, 而是为了看见整个世界.** Climb mountains not so the world can see you, but so you can see the world.
- 最关键一点，不断突破自己的心理界限。如果你总是活在当前自己的世界里，就容易把事情想小, 或想得”太大” (要么太看轻, 要么太高看), 总之就是不符合客观实际。

- 居后而望前，则为前；居前而望后，则为后。    +
身在后面，望着前面(志向远大)，那是前；而在前面望着后面的，就为后。

- **追取晋升, 这恰恰是一个人雄心的反映**. 通过各种手段(与高管有联系)获得上升(晋升)没什么不好意思的, 这恰恰是一个人雄心的反映, 当前的低下"现状"不匹配自己的真正能力!



'''
====





.★ 职业即阶层. 你所选择的角色和挑战，将会重新塑造你.
[%collapsible%open]
====

- 我们每一个人身处社会环境中，都在扮演着多种不同的角色，如儿 子、丈夫、妻子、母亲、员工、同学…… 不同的角色，需要你调整自己的思考、工作方法、沟通表达习惯甚至性格特征. 同时, **你所选择的角色和挑战，将会重新塑造你. **

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2
|**任何职业, 早就被社会标好了它们的下限和上限. 它们在世人眼中的地位和价值. 职业即社会阶层.**
|- **职业会直接"定位住"你的社会地位. 你学的是服务员技巧, 那出来做的, 也就是服务员的地位!**
- **在别人眼中，我是一个符号（贴标签）。这个符号, 就只有这个符号的价值(收入. 以岗设薪).** 事实上，每个人在每个他人的眼中，都是一个符号。既然是一个符号，我就要努力变成另一个符号。 #important
- 茨威格: 那时他们还年轻，不知道命运馈赠的礼物，早已在暗中标好价格。
- C位才是王道. 阶层地位从一开始的选择中, 就注定了. 金字塔结构, 不站在舞台中央(C位核心圈, 核心岗位, 核心职业)的人, 就不会有前途.
- 学乐器，当背景：学唱歌，万人迷。

|职业决定阶层
|- 职业决定阶层, 阶层有固化的趋势.
**"工具人"的最高价值, 也不会超过该"工具"所能给你带来的"上限功能"所值的价值本身.**
职业确实有贵贱之分，跟你的能力无关. **服务员洗碗洗的再干净，你也还是一个服务员的价值与身份. (乞丐的帮主, 还是乞丐)**

.. **设计能力再强， 它也是个设计的作用. 价值不会超过"设计作用"的本身.**
.. 艺术无价，上不封顶; 但一变设计，就封顶了，哪怕你设计的艺术性做上天了, 你也就是几千的月薪。 因为**设计作为"工具", 就是只值"工具"的身价.**
.. 一个擦皮鞋的技术再牛, 人家对擦皮鞋这种活的看待, 依然是只值擦皮鞋的价值.
.. 厨师厨艺再强, 你是老板, 你付给他们钱, 也不会超过你"为了填饱肚子所要花的钱"的上限本身.

- 位置即”眼界和资源”, “眼界和资源”即命运. +
你做的是啥(程度)，来的(遇到的)就是啥(能力的)人。你做什么层次的事情和事业, 就会交接到什么层次的人. (想想曹操). 当你越来越成功的时候，要找成功者来帮你工作(曹操广揽天下人才和英雄)。


|追求你的本心, 没那么难!
|- 很多事都是这样——在参与亲历之前，你从未想过你也可以成为某类别人眼中很厉害的人。**但当真的突破心理上的束缚，打破某些边界，把自己放到相应位置或环境中浸淫一段时间后，你会发现：好像有些事，其实也没那么难，**给你一些时间，让你经历一些摔打，你也完全可以做到。 是他的自律和无与伦比的好胜心, 驱动着他不断前行.

- **我希望大家不要对所有事物都觉得遥远而崇高，都不碰，可是自己却在受苦。其实它们不遥远也不崇高，你一做就会有进展，自己受的苦会减少。这才是我相信的事情。**
|===

'''
====

.一旦选错职业，就像坐上了开往"远离你内心向往方向"的火车.
[%collapsible%open]
====
- 老板甲：一个做市场的, 居然没有看过<一个广告人的自白>。我要告诉所有的求职者，你来参加这个节目一定要问自己准备了些什么，你这样是对自己的不负责，对我们的不尊重。

'''
====


.成为掌舵人(曹操), 而非工具人(武将)
[%collapsible%open]
====
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|成为核心
|- 不要做岗位的横向平移, 而要做职业的纵向发展. 成为“自我命运掌控者”（Owner）
即 : *你应该果断升级做业务的负责人, 为最终结果(收入, 利润, 流量)负责，而不是成为其中的一个模块。*  +
为了能更快带动你的成长, 要寻求参与或负责一些涉及多部门协作的复杂项目的推进落地. 能**了解和学习你之前岗位接触不到的公司各模块如何交互的核心内容** (你就是ceo).

|具有领导者眼界
|- 对“做事”进行管理的本质，就是树立一个具有前途的核心的业务，让这个业务带着所有的员工和组织架构往前走. (刘邦建基业, 带领大家往前走, 往上走)

- 你已经是一个管理者，尽量让自己在做思考、决策、对外获取有效信息的时间， 大于60%。
不断上行去看到更大的世界，了解更多顶尖高手在关注什么、如何思考，及如何才能成为那样的高手.

- *你要时刻关注: 你当前的成长模式，到底更多是"打补丁、提升能力"的线性竞争，还是"升级操作系统、切换赛道和模式"的非线性竞争。 竞争是分不同层次的，成长也是。*

|超越行业
|- 你必须以一条接一条的“S型曲线(生命周期)” 来带动持续的职业成长
*世上任何事物的发展(生命,组织,新技术,商业模式)都逃不开“生命周期”规律, 都会经历从诞生、成长、成熟、衰退，到最后结束的过程. 即不会一直无限地增长下去。*
|===

'''
====

.有两种人 : 1.谋事的(脑), 2.成为工具人的(变成手)
[%collapsible%open]
====
- 兴趣分两种，一种是(狭窄的)技术类兴趣（下棋，弹琴，画画，编程，武士），一种是(具有综合能力锻炼的)事业类兴趣（做生意，建帝国，赚大钱，诸侯之心）。

- 正像王立群所说, 人分为几种: 1. 琢磨事的, 2. 琢磨人的, 3. 琢磨钱的, 4. 琢磨人事钱三者的, 5. 琢磨"死物"的(设计, 工匠).

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|谋事者
| - **始终会关心更底层的逻辑, 即, 我做什么(how), 才能更好驱动自己生意的某个指标发展? 即, 你脑海中已经开始形成"对于业务进行拆解, 驱动, 和管理"的思维模型.**
- 中国古语"知之为知之, 不知为不知" , 从来不是谋事者的价值观. **谋事者从来不会以"自己并非那个专业出身的人士",而关闭自己大脑的主动分析判断能力,** 来抑制自己观点的发表, 盲从"专家". 谋事者绝不会"被动式的学习", 和"不加验证, 不加批判"的接收他人的说法. ( 具有独立思考能力, 和批判性思维.)
 - 掌握"结构化战略思维"的谋事者, **不会以“不懂”为拒绝思考的借口，他总是试图分解问题(换言之, 这种人是天生的”思考者, 谋事人. 如曹操”. 是刻在基因里的)**，运用放之四海而皆准的方法 (太阳底下没有新鲜事), 来逐渐深化“切”好问题.
 - **谋事者在内心中, 首先就是把自己定位成”解决问题的人”，** 而不是"在一旁的看戏者, 吃瓜群众". **谋事者的性格中, 本身就对问题保持着亢奋的“进攻”状态。(你自己就是爱思考者，要建立自己的价值观方法论大树框架"的人.** 项羽: 彼可取而代之. 曹操: 若天下没有孤，不知有几人称帝几人称王.)
 - *淘宝网总裁孙彤宇有90%的时间都在考虑淘宝的发展.*
|===



工具人工作对你的毁人之处
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|-> 毁脑
|- 工具人只关注把手中的事情做完, 而不去想这件事的意义价值有多大, 要想驱动你公司业务的发展, 有没有更好的方式?
- 工具人, 因为你满眼都是芝麻，天天为捡芝麻而忙碌，就没有机会练就捡西瓜的能力了。

|-> 工具人会变成"工具"本身, 而不是"人". 缺乏意义感.
|- 技术类兴趣是悲剧，因为小时候你在这方面努力和投资花钱，被看成是“特长”，但**技术的归宿就是"工具" — 最终会变成"谋事者"手里的工具人。** +
-> 擅长做菜是优点，当了厨师就是悲剧了。 +
-> 小时候是个小画家，长大当了做小广告传单的就是悲剧了。

- **如果你老是做着靠“软件本身自带的功能”就能实现效果(比如调色)的内容的话，** 这性质就跟以前的工人, 工作只是在操作扳手一样，那注定将来会被机器ai 所取代。**因为ai自己就能调用软件api, 来调色了，还要用你干嘛？** 就像智能汽车, 或自动驾驶飞机一样. ai自己就是操作工具最有效率的“工具人”了。所以你必须要做超越软件的事情，做ai做不到的事情。

- 电影特效让演员的英雄形象更伟大，**为什么演员赚大钱，而特效人员只能提他人（演员）做嫁衣裳**，是固定收入，不能分成票房？**因为演员是独一无二的，每个人的魅力都不同，不可替代。而特效技术换任何人都可以做，软件算法得出的效果都一样。作特效的不具有不可替代性。而只有人是独一无二的**，每个人都是独一无二的，不可替代的。


- 如果人类是机器人，那可以高度劳动分工(变成螺丝钉), 但人是活生生的生命体, 他们需要"内在的激励因素"和"意义感". 而高度分工这种方式剥夺了他们的这些人性需求。
- 作为人类，我们一生的很多时间都在寻求意义——无论它多么简单、多么微不足道。
- 人有"自然属性需求"和"社会属性需求"。卡车司机，一年绝大多数时间在车上，不回家，不社交，社会属性几乎丧失。

|*"工具人"的最高价值, 也不会超过该"工具"所能给你带来的"上限功能"所值的价值本身.*
|- 职业确实有贵贱之分，跟你的能力无关. 服务员洗碗洗的再干净，你也还是一个服务员的价值与身份. (乞丐的帮主, 还是乞丐)
.. *设计能力再强， 它也是个设计的作用. 价值不会超过"设计作用"的本身.*
艺术无价，上不封顶; 但一变设计，就封顶了，哪怕你设计的艺术性做上天了, 你也就是几千的月薪。 *因为设计作为"工具", 就是只值"工具"的身价.*
.. 一个擦皮鞋的技术再牛, 人家对擦皮鞋这种活的看待, 依然是只值擦皮鞋的价值.
.. 厨师厨艺再强, 你是老板, 你付给他们钱, 也不会超过你"为了填饱肚子所要花的钱"的上限本身.

|*任何职业, 早就被社会标好了它们的下限和上限. 它们在世人眼中的地位和价值. 职业即社会阶层.*
|- 职业会直接"定位住"你的社会地位. 你学的是服务员技巧, 那出来做的, 也就是服务员的地位!
- 茨威格: 那时他们还年轻，不知道命运馈赠的礼物，早已在暗中标好价格。
- C位才是王道. 阶层地位从一开始的选择中, 就注定了. 金字塔结构, 不站在舞台中央(C位核心圈, 核心岗位, 核心职业)的人, 就不会有前途.
.. 学乐器，当背景：学唱歌，万人迷。
.. 职业会直接"定位住"你的社会地位. 你学的是服务员技巧, 那出来做的, 也就是服务员的地位!
.. 和朋友一起去考了**"家庭收纳师"（算"家政服务员"的一种）,** 让我体会到了现实的残酷。在一所院校周日考试，**同场还有茶艺师，咖啡师，糕点师……都是职业培训类的。唯独家政服务员考场死气沉沉，有一位考官完全不把我们当人看。那种鄙视，呵斥，**眼都懒得抬一下. 我只是来考证，敢骂我一个字试试，我就投诉到底. 但是现场你们不知道有多少位真的想找份糊口的活儿的人，一下萎了，变得唯唯诺诺。**那种低人一等，呼来喝去，毫无尊重可言的滋味，**没有强大的内心和钢铁般的意志真干不了。现实生活中哪来那么多高素质的人？ +
**即使雇主待人很不错。雇主的家人呢？亲戚呢？我家婆婆就觉得阿姨就是个佣人！**要平等尊重吗？*我婆婆一毛钱没花，就能拿自己当主人看。*

- *在别人眼中，我是一个符号（贴标签）。这个符号, 就只有这个符号的价值(收入. 以岗设薪).* 事实上，每个人在每个他人的眼中，都是一个符号。既然是一个符号，我就要努力变成另一个符号。


|-> 职业即阶层, 工具即"人下人"地位, 是被人使唤的. (劳心者治人,劳力者治于人)
|- 你是工具人, 会**人为的把你变成"人下人"地位 , 并让你的关注点偏离"真正重要的东西"上.**
.. 比如视频剪辑, 你一直在关注底层执行层面的"操作技巧"的事, 就会将你肤浅化, 带歪你, 令你平时看电影时, 也会更多去注意那些低价值的, "运镜技巧"东西, 而影响你对"故事内核"的专注程度.
.. 人与人之间天生没有地位差别, 但如果有人强行把你打入某个工种中, 那就是他人为地, 强行把人划分成不同等级地位了. 比如, "编剧"与"摄影剪辑"这两个工种, 没有人天生是一定要去做哪个的, 但如果上级任意指定你必须去做剪辑, 那你就是被直接赐予了更底层的地位, 让做"编剧"的人来指手画脚你.

|你做的是啥(程度)，来的(遇到的)就是啥(能力的)人。
|- 你做什么层次的事情和事业, 就会交接到什么层次的人. (想想曹操). 当你越来越成功的时候，要找成功者来帮你工作(曹操广揽天下人才和英雄)。

|以有涯追无涯
|作为历史长河中的一条连贯到未来的线，技术是永远在发展的，这决定了你有限的生命，不可能解决所有的技术问题。所以, 你只能占据这条无限的发展线上的 一段时间，掌握住 一段技术前沿，然后把技术交接给后来人。(任何一个奥运冠军都必将退役, 但体育技术的发展却不会停下脚步.) +
你去哪呢？ 管理岗位。因为**人性是自古不变的，更具有稳定性。**历史书中的人性故事，对现在也是有启迪的。*所积累的管人经验, 能用到老。而不像技术那样迭代极快，积累的经验, 很快就会过时无用。*

|-> 工具人, 没对收入来源进行"风险分散", 造成"手停口停".
|财富收入的来源, 不能只唯一挂靠在你自己的肉身上.

|-> 工具人工作, 会带给你职业病
|- 做剪辑这种职业的人，要不就是得胃病（剪视频可以忘记吃饭），要不就是得失眠（睡觉脑里还在剪视频），要不耳朵痛（整天挂着耳机）。
|===

'''
====





- 你是专业的，就不要干业余的人也能轻易做到的事.








