

== 如何看人 (你对他人的真实为人, 做出怎样的判断)

.忧郁症和你事业人生等成不成功没有任何关系. 很多名人都有抑郁症
[%collapsible%open]
====
忧郁症和你事业人生等成不成功没有任何关系. 好莱坞许多喜剧演员一样，罗宾威廉斯及金凯瑞都是忧郁症患者。(财富如李玟亦然). **忧郁症不分**性别、年龄、*财富地位，也不管个性阳光、充满活力或是内向不擅表达，都有可能罹患。*

'''
====


.★★ *“可预测性”是对”稳定性”的判断，“可展望性”是对”成长性”的评估。*
[%collapsible%open]
====
- 如果你十次有八次把事情做到80分，两次做到60分，上司对你的预期就是80分；  +
如果你十次有六次把事情做到100分，四次不及格，那上司对你没有稳定的预期。

'''
====

.★★★ *人的价值，在遭受诱惑的一瞬间被显现. 别人对你价值的判断, 是步步试探, 从你的态度反馈上得出来的.*
[%collapsible%open]
====
- **权，然后知轻重；度，然后知长短。**物皆然，心为甚。 +
→ 权：本指秤锤，这里用作动词，指称物。  +
→ 称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。

- 相形不如论心，论心不如择术.  +
观察人的相貌, 不如考察他的思想; 考察他的思想, 不如鉴别他立身处世的方法。

- 其实我并没有傻到每次约会都带女儿，我只是想试一下，他对我女儿的态度。

- 他时不时地颁布一两条严苛的法令，以此来给社会做"压力测试"；如果民众反应强烈，就把法案稍作调整；如果没有抵抗，就不妨加重力道。 +
不断地测试民众的压力，权衡中国人在基础生存需求之外还有多少可榨取空间.

- 不要对自己提出提高薪水的要求感到愧疚：人做的最愚蠢的事情之一，就是有的人总是白干活。 *不要把自己白白捐献出去，否则，你不仅会失掉你应得的钱，还会贬低自己在别人眼中的价值。*

- 头部主播奉行的这种全网最低价，对品牌来说是慢性毒药。*当消费者长此以往习惯低价，品牌溢价就没了，以后价格很难上去。(形成了不该有的条件反射, 固化印象)*

- **你最低所需要的, 不等于你的价值。**在研究生时，我一年12,000美元也活得很不错。可是，我会因为生存只需要12,000美元, 就只要求拿这么多的薪水吗？ *如果你只想着你需要的程度（维持最低生活的），你永远也不会得到你所值的（与你价值相符的）。*

'''
====

