
= (关系) 如何发展关系与解决障碍




.★ *把社交看做吃饭、睡觉一样自然。不需要什么心理负担.*
[%collapsible%open]
====
- 社交就像吃饭、睡觉一样重要，同样，也应该像吃饭、睡觉一样自然。*不要对它抱着过高的期待和目标，把它放低一点，让它成为你生命中一件自然而然的事情，把它跟你的形象、评价、标准松绑。*
- 你很难喜欢上嘉宾, 可以这样操作: 别把他想象成一个真人，你们可能这辈子都不会再见面了，你就当采访一个NPC（非玩家角色），就隔离那个情感。

- 对方也在乎你对他们的看法. 台上表演者, 也希望台下观众能与自己互动越热情越好. 而不是收到冷场.

'''
====

== 建立


.先建立信任, 后才有可能发展关系
[%collapsible%open]
====
人与人, 你与陌生人之间的关系, 肯定是从最冷, 最敌意, 再到熟悉亲近的. 所以你生活中遇到陌生人对你恶语相向, 是非常符合这个心理逻辑的.

'''
====

.做生意之前, 首先要建立起别人对自己的信任
[%collapsible%open]
====
*做生意之前, 首先要建立起别人对自己的信任. 换位思考: 你不相信别人, 你就不会放心去和别人做金钱交易.*

- 在对方心中还未建立起你的亲和性、可信度和权威感的情况下，就想说服对方, 是很少会成功的.
- 如果说客户只认识到了你的价值，但是并没有建立起对你的信任，一切就不会有下一步进展。
- 某些药，是为别的药服务的，它们被叫作“药引子”；同样，*某些沟通，是作为预备性的, 目的是为了让接下来的沟通更顺畅. 即, 在开展实际对话之前，我们有很多准备工作要做；在对话从浅水区. 渐渐迈向深水区的过程中，我们需要先建立起情感联系, 与基本共识.* (即: 郭德纲的"闲白"所起的功能)
所以, 那些演讲时，上台就急着煽情或者下结论的演讲者, 是不会有效果的.
- 双方已然失去了基本的信任，没有这个误会它也得有那个误会，没有事它也会生出事儿来。(两国关系也是如此)

'''
====

.必须先建立情感, 然后才有可能说服对方.
[%collapsible%open]
====
- 异性之间，顺序是: 先喜欢一个人的性格特质，然后才会对其肉体（性）产生兴趣，而非顺序相反。 不首先对一个人产生心理上的喜欢，是不会对其肉体产生爱的。
- 郭德纲再说评书前, 必先和观众闲白, 就是这个原因, 先建立起双方情感连接, 对方才会听你说事.
- 她说某品牌的安装师傅到家装空调, 会带一块布把这个地擦干净. 我说这块布要贵10％，*这块布擦的不是你们家地板，擦的不是你们家的机器，擦的是客户的心。*

'''
====



== 维持


.情感是流动的
[%collapsible%open]
====
- 关系就如逆水行舟，如果没有得到改善、维持和发展，就会随着时间而衰退。人与人的关系不是变热就是变冷，没有保持不变的中间的关系。
- *任何一个运动系统如果要持续稳定地运行，必须要有持续稳定的能量源源不断地注入；否则，系统就会紊乱(熵增)，甚至崩溃。婚姻也是运动的系统，它若要持续稳定的运行，也需要持续稳定的能量源源不断地注入。*
- 感情是流动的，因而必须要有不流动的合同来规范我们的行为(做生意上)。

- 很多人愚蠢地以为, 不把情绪说出来是为了不使配偶担心，事实上，不说出来反而使配偶更加担心，她只能干着急。本来两人可以相互扶持、共同度过的一段经历，你却没有好好地利用。（危机中隐含着机会，这或许能成为你们感情加深的良机。危难见真情）

- 很多婚外情的开始, 就是源于家中的配偶不去了解另一方。因为**当你对你的爱人关闭了情感交流的大门，你的爱人就会去寻找其它向她敞开的情感之门.**
- 如果一个男人的自尊心与虚荣心, 没有从妻子那里得到，他的情感, 就会转移到那个能给予他赏识与肯定的女人那里去。
- 先是夫妻两人的关系破裂了，第三者才会出现（第三者乘虚而入。家必自毁，而后人毁之）。

'''
====

.撒娇女人可能真的会更容易好命。这里的**“撒娇”指“在关系中，直接、清晰地提出需要.**
[%collapsible%open]
====
2017 年发表在《人格与社会心理学公报》上的一项研究：撒娇女人可能真的会更容易好命。这里的**“撒娇”指“在关系中，直接、清晰地提出需要.**  +
→ 清晰地表达需要, 能带来正向循环 : 促进伴侣给予相应的情感等支持, 令你们走向下一个新的关系阶段。 +
→ 不让对方猜你的心理, 只会带来负面循环 : 对方猜不准，你很失望. 对方对你的模糊表达也会失望.
即, 亲密关系中, 一个人"表达需要"的方式，能直接影响着两个人接下来互动的走向（Cutrona, 1995 ).

'''
====




.*不要欺骗别人，能被你骗到的都是相信你的人。*
[%collapsible%open]
====

'''
====

.*要想人与人之间做事能顺利的话, 必须先建立"处理问题"的机制(如同"合同"的逻辑一样)*
[%collapsible%open]
====
- 夫妻之间应该建立一种就矛盾冲突进行讨论的机制（平等地位、就事论事, 相同权利）。如果没有机制, 很快地，争吵的焦点就不是本来要讨论的事情，而是“对方的态度如何不对”这种"机制"上的问题了. (所以, 美中两国对话, 就要先建立起双方对话的机制, 双方先达成共识.)

'''
====


.圆滑地解决障碍
[%collapsible%open]
====
- **你当前对某事物认知上的对错不重要, 但你要很自然 natural 顺滑的和客户回到正确的轨道上来, 而不能"宕机" (awkward interviewer).** 即, 你的反应, 处理事情的能力, 要很圆滑自然.

- (脱口秀)我们想出来的梗，肯定永远不是最好的。观众也不需要最好的。嘉宾也不需要最好的。**它本身对不对, 并不是最重要的，它能解决问题就行了 (”有用”就是”对”)。**

'''
====



