
= (政治制度) 资本主义制度内含的本质价值是什么



.资本主义, 意味着一种价值体系
[%collapsible%open]
====

- 英国实现了资本主义, 是一系列偶然汇集到一起的结果： +
*一个软弱的君主政权; 及常备军制度的长期缺乏* → 削弱了王权的力量 +
一部根深蒂固的**习惯法; 自治传统; 强大的议会** → 加强了民间资本的力量

- Mancur Olson :“充满活力的市场经济绝对不是什么空穴来风。**它需要一系列**当今绝大多数国家都不具备的**制度安排**。”

- (从演化的角度看), 资本主义是一个整体性的历史运动，而不是个别经济现象。 +
仅有“雇佣劳动”, “私营手工作坊”，并不足以称之为资本主义萌芽，事实上这些早在汉代就已经出现了。所以李伯重认为，*中国不存在所谓的“资本主义萌芽” (因为缺乏配套的法律, 司法体制)*.

'''
====

.中西方法律差距的背后, 实际上隐含着对个人”权利”和”义务"的两种截然相反的看法价值观.
[%collapsible%open]
====
西方人对中国落后的司法(随意逮捕, 折磨被告)不满, 因此执行"治外法权"制度 (由外国司法机构, 来审理外国国民). **中西方法律差距的背后, 实际上隐含着对"个人权利和义务"的两种截然相反的看法价值观.**  +
**司法要改革，**如同在日本的一样, *被外国列强认为是废除在华"治外法权"的必要前提。*

'''
====



.欧洲国家在发展中探索过四种制度, 英国的体制胜出
[%collapsible%open]
====

欧洲在构建民族国家的过程中，进行了多种尝试，探索了多种道路(四种模式). 这四种方式经过长期竞争. 最终英国式的国家体制, 获得压倒式优势，并决定了今天世界的面貌。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|极端专制 (西班牙)
|

|集权专制 (法国)
|


|君主立宪 (英国)
|.国王本身不过是最大的贵族而已, 而非有阶级地位
英语里的“king”，除了“国王”之意外，还表示“大的”“主要的”。事实上，英国的贵族一直认为国王是自己队伍中的一员，是“贵族中的第一人”。国王本身不过是最大的贵族而已。

.英国历史上一直有着强烈的”自治”传统。
**自治城市中的市民之间, 只有贫富不同, 而法律地位平等**. 因为**资本主义本质上是反特权、反等级制的.** +
自治城市可以自己立法，可以组织军队，可以发行货币，可以决定如何收税。

.有陪审团制度
1166年，亨利二世颁布《克拉灵顿诏令》，确立了陪审团制度，*规定大部分地方案件由当地人自己处理。*  +
这一制度对英国社会和英国人的思想影响, 是非常深远的。*“每一个陪审团都是一个小国会”，这一制度逐渐培养了英国人的权利意识，对英国普通民众, 起到非常好的社会参与培训作用。*



|松散联邦 (荷兰)
|.遇到问题: 海外经商的"融资"和"分散风险" ← 解决方式 : 创造出"股份有限公司"制度

- 问题机会:  +
1602年，荷兰东印度公司成立之初，面临着"筹集资金"和"分散风险"两大问题。

- 解决方式: +
荷兰人进行了制度创新，面向荷兰的所有市民公开发行股票，成为股东，分享它的收益。

- 存在的条件基础: +
**股份有限公司的出现，事实上很不简单。它的背后，反映出契约精神和法治精神。几千人几万人敢于把自己的钱, 投给一个与自己完全没有私人关系的组织，并信相信董事会会营运好这些钱，并且赚了钱后会公平地分给自己，**这并不是哪个国家都能做到的 -- *这完全就需要这个国家具有悠久的法制契约基因。*

.遇到问题: 股东资金的自由进出 ← 解决方式: 股票交易所
为了方便股东资金的随意进出, 1609年，世界历史上第一个股票交易所, 诞生在阿姆斯特丹。
|===

'''
====

.(母国的)文化基因, 决定(殖民地)长成什么大树果实.
[%collapsible%open]
====

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|英国(民主)
|- 基于英格兰自治传统，英王对殖民地的管理也是放羊式的。殖民地时代的美国并没有一个统一的政治规划。所以美洲殖民地一开始是一个又一个分散的殖民点，这些殖民点从一开始, 就是高度自治的。 乡镇政治, 因此成为美国政治的基础。
- 作为一个代议制国家，英国把"民选代议制", 也带到了殖民地。 +
托克维尔：“*在我们法国，是中央政府把它的官员借给了村镇 (对上负责)；而在美国，则是乡镇把它的官员借给了州政府 (对下负责)。*”
- （北美洲的殖民者）具有企业主的开拓和进取的精神……他们并不按照英国政府的意图行事，不愿意把自己生存的土地变成一个落后的原料供给地。

|西班牙(专制)
|- 西班牙把本国的封建专制制度, 直接移入殖民地，建立起与西班牙完全相同的集权体系。总督集民政、军政与司法大权于一身，只对国王负责，并不代表地方利益。西班牙殖民地政府, 具有其母国专制政体的一切缺点。

- 殖民地时期，拉丁美洲社会实行严格的等级划分: +
-> 第一等人是“半岛人”，即来自西班牙半岛的人，他们担任殖民地的高官. +
-> 第二等级是“克里奥尔人”，即美洲出生的纯种西班牙人。 +
-> 第三等级是“梅斯提索人”，也就是西班牙人同印第安人混血的后代. +
-> 第四等级是印第安人. +
-> 第五等级是黑人。 +
-> 第六个等级是黑奴。 +
 +
image:../img/0051.svg[,] +
 +
从殖民地时期开始，拉丁美洲就存在着北美没有的巨大阶级差别.

- 事实上，独立战争的结果“仅仅是一场政治权力的转移，除了由原来的二等公民克里奥尔人取代了西班牙人的政治位置” , 其他没有变化。   +
西班牙的政治遗产拖了拉美的后腿。“我们是独立的，但我们是不自由的；*西班牙的军队不再压迫我们，但她的传统却压得我们喘不过气来。*” +
文化缺乏民主的基因, 成为拉美现代化的重要障碍.

因此，以欧洲移民为主体的"英属"殖民地, 今天基本上都是发达国家。 +
而同样以欧洲移民为主体的"西班牙（包括葡萄牙）"殖民地, 今天则大都是发展中国家。西班牙对拉丁美洲的数百年旧式殖民统治，决定了拉丁美洲今天的落后面貌。 (种下民主的种子, 才能收获民主的大树)

李光耀说：“新加坡成功的关键，是英国人留下的法治制度，而不是什么儒家文化。”

|===

'''
====

.大乱带来大治
[%collapsible%open]
====
大乱带来大治. 把整层专制的土铲掉, 才能种下民主基因的种子, 才能生长出民主的大树. +
经过大规模农民起义后建立的王朝, 往往寿命更长. 因为这些农民起义把原来的社会破坏得很彻底。所以就有这种说法: “大乱达到大治”。

'''
====



