
= 如何确保权力

==== 巩固自己的地位

- 把个人目的裹上家国民族的外衣，来集权 (如曹操)。

.★ 身兼多职, 才能不被失业
[%collapsible%open]
====
- 和珅把持着掌管"财政"和"官员任命"的重要职位. 有时他兼任的官职多达20个.

'''
====




==== 压制他人

.将阶层固化住
[%collapsible%open]
====
- 他积极地让红色子弟去西方学习管理和技术，然后回国管理那些新型国企。企业将会由拥有高学历的红色后代们治理. 在今后的企业中，无论是董事，CEO，研发总监，还是会计和各类高管，都将是红色家族的子女。 +
这能无限拉开"统治者"和"被统治者"两个阶级的差距，塑造一种稳固的社会二元结构。**在这种模式下，官僚就是上层建筑，民众则充当生产资料。**

'''
====

.利益笼络
[%collapsible%open]
====
- 袁世凯习惯用传统政治的那些方式 (即权术+军权掌控) 来对政局进行控制。他相信对所有人都可以实行笼络. +
**在这一过程中，袁世凯不仅试探出了国民党的实力和能耐，**他也最大限度地使自己的能力和权限扩大化。 +

- 袁世凯还要依靠国会把他选成大总统。虽然国民党在国会占有多数，但袁世凯很清楚，国民党本来就是一盘散沙, *这些议员主要是想来北京当官的，他们不认为自己乃是民意代表，而自认为是国家的官.* 很多都是贪图个人享受。因此袁世凯在国会中的第一个议案，就是给议员加工资. 这样, 这些议员就会把他选出来(当总统).

'''
====

.执行对他人行动的"情报网"
[%collapsible%open]
====
- 规定私企要建立党支部，让他们养一批官方眼线去监控自己。

'''
====


- 禁锢住你的"思想与觉悟", 让你永远保持在"奴役思想"状态中, 保持你的"被统治意识"

.思想专政 -- 统治者垄断对经典的诠释, 民间新思想体系无法建立
[%collapsible%open]
====
以前的中国, 对儒家思想的解释, 主要是由士大夫来负责的.  +
但清朝更加集权, 乾隆剥夺了士大夫的这种权力, 自己来阐释经典. 清朝有很多皇帝, 都编有自己对经典的解释集. +
因此士大夫的精力, 就只能投向去搞"考据"了. 顾炎武帮助创立了"考据学", 用来判断古代文献的真伪.

但**中国文化之精髓不在于考据，而在于对经典思想的阐释, 并创造出新的思想体系。两汉的经学、宋代的理学, 明朝的心学, 均建构出了新的学术思想体系.** 但清朝，统治者禁止了士大夫去做这个, 学者的创造力被禁锢，一生都被消磨在琐碎的考据之中. +
而且**"考据学"只能用于文化研究的有限领域, 不能用于自然科学和技术.** +
事实上, 中国许多早期的科学发现和发明, 更多是与道教徒有关, 而不是与儒士有关. 中国对自然的研究, 也从来没有像西方那样, 将现代科学"系统化"和"理性化". +

*这导致, 清代的主要学术, 对如何解决清代晚期面临的紧迫问题, 几乎没有提供任何良策.* +
一直要到太平天国之后, 汉人士大夫(曾国藩, 李鸿章等)崛起, 清政府就再也没有能力搞文字狱了。汉族士大夫中, 不仅"实学"开始活跃，一些人也开始追求"西学" (洋务运动).

'''
====

.新教对”开放性诠释”的追求, 本身就是一种对”思想垄断”的打破
[%collapsible%open]
====
新教就是能让"西方文明理念"传入的的窗口与渠道. +
**中法《黄埔条约》(1844), 规定了"开放教禁". 西方的文明思想, 就能借着传教士渠道输入进来。**由新教教士创办的报纸, 如《万国公报》，对中国思想界起到了启蒙作用。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|天主教 |新教

|天主教是本教，普通信徒对教义是不能随便解释的，《圣经》的解释权掌握在教皇手中。
|**"新教"不允许"垄断解释权"的人存在, 每人都能按自己的理解读《圣经》，**这样必然会产生对教义的不同解释。(*新教对”开放性诠释”的追求, 本身就是一种对”思想垄断”的打破.*) 因此新教有很多流派.

- 而洪秀全的"拜上帝教", 可不精确地看做是他自创的”新教”的一个分支. 但是, 这也造成士绅直接地把”拜上帝教”的罪过, 加到”天主教”的头上. 太平天国覆灭后，士绅们直接将天主教视作挑起农民造反的"恶势力”.

- *为了传播基督教教义, 传教士们发现, 向社会秩序提出质疑 — 至少通过暗示来做到这一点,是必要的.* 而这种秩序在地方上的中坚人物 — 是士绅。 *传教士们在诸如孤儿抚养、济贫, 和在灾荒年月提供赈济之类的事务中, 与士绅展开竞争. 这在传统势力看来, 基督教似乎一心在鼓动对现实不满的人。* (因为基督教在解决儒教无法解决的问题，反衬出儒教的无能，所以在儒教看来，基督教就是暴露自己无能的人, 是敌人.)

|罗马"天主教"的布道, 有单一的机构协调他们的活动.
|而新教则没有. 后者的活动几乎像西方商人的活动一样分散。
|===


'''
====











