
= (模型思维) 如何解决学校所学和社会需求脱节问题

.探索之: 德国“双元制”职业教育
[%collapsible%open]
====
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|“双元制”的概念
|- 所谓“双元制”，就是学生一部分时间在职业院校学习理论知识、一半以上时间在企业实训的职业教育模式。（这很像医学生）。 +
德国人崇尚实用主义，读书是为了就业的想法根深蒂固。德国的年轻人中，差不多每 3 人中就有 2 人通过职业教育实现就业。 +
德国的“双元制”职业教育不看学历看技能证书，以就业为导向。这也是"职业教育"和"普通教育"最本质的区别——职业教育和学历是没有关系的。

- “双元制”的招生主体不是学校，而是企业（这就说通了，所以他们想把人变成工具人，他们根本就不是大学，没有大学培养素质人的价值取向），企业和学生签订为期三年或三年半的"学徒合同"之后，学校会自然录取(相当于企业办校, 自己办学校来培训自己的工人)。这意味着，企业是在"校企合作"中的主导方，学校是为企业服务的，编纂的课程要围绕企业需求开展。 +
在德国, 在职业培训方面的投入中，企业贡献了大约 85% 的费用。

|教师
|为了实现教学理论与实践的无缝对接，德国“双元制”教育的师资队伍也是双元的，即拥有"职业学校教师"和"企业技术人员"两支队伍: +
-> 学校教师, 要求具备企业相关工作经历, 才能进行理论传授， +
-> 企业技术人员, 指导学生实习实训

但在中国，大量硕士、博士毕业后就直接入校就职, 他们没有实际企业经验。

|员工(学生?)评价体系
|企业的"人才评价体系"，和学校的评价体系无法耦合. +
但要求建立一套以企业岗位胜任力为主导的评价体系, 也有问题. （企业的需求变化快；不同企业的考核看中，也是不一样的；很多职业的绩效是无法量化的；所以不可能让学校容纳这么多企业的差异标准，对老师和学生也是巨大的负担。你一个学校不可能只对口一个公司吧？那么学校就会变得非常弱势，完全受制于那个公司，相当于变成了乙方，而企业是甲方，地位完全不平等）

某企业的slogan（宣传语）原来是"帮助企业培养有用的人", 后来改成了"...培养好用的人". （*其实已经将学生从一个"素质人"，窄化变成了"工具人"*） +

|德国“双元制”能成功(及中国失败)的原因
|- 德国社会在观念上，没有“万般皆下品，唯有读书高”的思想.
- 为了在教学上紧贴企业需求实际, 德国"联邦职业教育研究所"（BIBB）是德国"职业教育"系统规划的总设计师，负责收集每个企业发现的问题，制定出新的方案。

- (中国)我们的学生从小学五、六年级开始，基本上两耳不闻窗外事，一心只读‘圣贤’（解题技巧）书，不知道自己未来想从事什么职业，（说得也对。*要尽早知道自己的志向，然后把资源都用在这一方向上*）。导致大部分大学毕业，不是盲目的到大厂去实现自我价值，就是在社会摸爬滚打很多年，仍然从事自己不喜欢的行业，到不喜欢的公司打工，仅仅为了一日三餐。如何有幸福感？

- 中国企业普遍的短视和急功近利, 导致对职业教育投入的动力不足。德国企业做职业教育的目标是"培养人"，企业制定计划的横跨周期, 是 5 年甚至 10 年. 而中国的企业，KPI完不成，领导就会被‘干掉’, 导致企业在用人时宁愿直接招‘掐尖’的, 而不愿‘培养’。

|===







'''
====
