

= (目标)如何一步步实现你的最终目标


.★★★ 如果你能做到超出行业中的传统认知, 你就是开拓者了
[%collapsible%open]
====
在与日俱增的运营大军中，*更多人缺乏的是统观行业上下游的运营思维高度，以及跳出具体岗位外，对这个职业的想象力* (即: 这个职业的内涵, 其实也是个"筐", 它里面该包含什么内容, 它将来该怎么发展, 不是由别人定义的, 而是由你自己来定义的!)。

'''
====

.★ 战术的目标，就是赢。而战略的目的，是我推动当前的均衡向下一个均衡点转化，并使自己在下一个均衡点中，那个优势稍微大一点点。
[%collapsible%open]
====
- 毛泽东有句话 ： “谁是我们的朋友，谁是我们的敌人， 这是革命的首要问题 。朋友搞得多多的，把敌人搞得少少的， 革命就赢了。” 这是一种典型的战术思维。

- 梅特涅讲过一句名言，他说， *我控制欧洲局势的心法其实就是一条，就是确保所有国家之间的矛盾， 要大于他们和奥地利之间的矛盾。* +
就是敌人和朋友搞清楚有那么重要吗？ 大家都有矛盾，但是这个矛盾都有化解的可能，只要**我确保你们之间的矛盾，大于你们和我之间的矛盾，你们就会永远争取我的支持，** 所以我奥地利虽然国力不强，但是我就是控制欧洲的局势。这就叫战略思维。

- 中国人经营南海，主张”搁置争议，共同开发”。原来的均衡是， 我要在主权这个矛盾下, 和菲律宾这样的国家去谈什么国际法、海洋法，没准儿还把美国招进这个格局来，这个谈法我是吃亏的。 +
所以我搁置它，**我推动这个均衡往下一个均衡去转化，**转化矛盾到什么？——我们共同开发。 开发远洋海岛这个东西你以为容易啊，**这是比拼国力，所以就能导致我的优势扩大。矛盾就转化到对我有利的那个主场上来了。**你美国人总不能来共同开发吧，你根本不是南海的周边国家。

'''
====

.★★ 各个"点"必须能够串联起来, 形成累加势能.
[%collapsible%open]
====
- 所谓战略, 就是在你的大方向下, 各个"点"必须能够串联起来, 形成累加势能。 如果你在各种方向上布满了各种产品，*彼此却不能借力, 以至于每个单点都只能单独去与对手竞争, 你就会非常吃力.* (这和人生是一样的, 你在人生中所做的任何事情, 必须对你的最终目标有累加推动效果. 即, 不要去积累你不想积累的, 对你"上岸"没有用的经验!)

'''
====


