
= (工具手段) 如何找到因果关系中的"因"


.相关关系 ≠ 因果关系
[%collapsible%open]
====
统计学教科书里教的第一件事就是: "相关关系"不是"因果关系"! +
*相关关系: 是指一个变量(var 1)变化的同时，另一个变量(var 2)也会随之发生变化，但不能确定var 1 变化是不是 var 2 变化的原因。*

image:../img/0042.svg[,]


- "大数据分析"可以在完全不考虑"因果关系"的情况下，通过数据点的"相关性"和其他规律，精准地给出对下一个购买行为的预测分析。商家不必纠结“因果”，仅用"相关关系", 就可预测大部分市场营销的需求。 (就好像你不需要知道量子物理学的具体原理，只需要知道它是有效的, 就能直接使用它.)

- 美国零售大户Target, 曾经利用消费者购买数据, 判断女性消费者的怀孕状态，并通过推送婴儿用品广告等方式, 进行精准市场营销。— 如果发现女性消费者突然改变自己的消费习惯, 并开始新的消费行为，如购买无香的身体乳液，购买一系列如钙、镁和碘等维生素，购买育儿图书或杂志，或者注册了孩子的礼物名单等，商家内部客户管理系统（CRM）就会提升所谓“怀孕预测指数”。一旦指数达到设定标准，公司就会为此类消费者打上标签，并向这类消费者按不同孕期阶段, 进行促销，一次推送多达20多种孕期产品的介绍或样品。


- 虽然"相关关系" 给我们提供了很多增加收益的方法。但成也萧何败萧何 : *"相关关系"也是相对不稳定的, 易变的. (因为你还是不知道背后真正起作用的变量(即真正的因果关系)是哪个)*

'''
====

.真正的"因果关系" 该如何验证? 需要以下4种可能性矩阵来收集数据:
[%collapsible%open]
====
最简单的"因果关系"验证实验, 需要以下4种可能性矩阵来收集数据:

[.small]
[options="autowidth" cols="1a,1a,1a"]
|===
|Header 1 |待证实的”结果”, 出现|待证实的”结果”, 未出现

|待证实的”原因”, 出现
|a 数量
|b 数量

|待证实的”原因”,未出现
|c 数量
|d 数量
|===

即: 只有在严格控制其他因素，去掉混淆变量，并在我们得到这四种数据下: +
原因出现，结果出现（a个案例）； +
原因出现，结果未出现（b个案例）； +
原因未出现，结果出现（c个案例）； +
原因未出现，结果未出现（d个案例）。

我们才能用以下的数学公式, 来验证"因果关系"是否真的成立: +
latexmath:[ \varDelta P =\dfrac{a}{a+b} - \dfrac{c}{c+d} ]

即: +
→ 如果ΔP的值是零，则完全无相关性； +
→ 如果ΔP的值是正数，则值越大（总实验次数为上限），因果关系越强； +
→ 如果ΔP的值是负值，则说明, 此"原因"有"抑制结果产生"的功效。

- 假设我们做了200次实验，其中100次有原因出现，这时有80次出现了期待的结果，20次没有出现。另外100次实验没有这种原因出现，有80次出现了期待的结果，20次没有出现。 +
现在套用公式： +
latexmath:[\varDelta P =\dfrac{a}{a+b} - \dfrac{c}{c+d} = \dfrac{80}{80+20} - \dfrac{80}{80+20} =0 ] +
在200个实验基数上，ΔP=0, 说明这两个变量(待验证的原因, 和待验证的结果)之间, 并无真正的因果关系。

'''
====

