

= (价值观)如何看待他人嘲讽

- ★★★ *人是一个“活”的东西，有变化性，因此没有任何人能定义你！说死你. 也没有任何人能给你"盖棺定论".*

.人有给别人瞎戴帽子的倾向
[%collapsible%open]
====
- 列宁的”帝国主义理论”, 强行将所有人都贴了标签, 被戴了帽子，不管是不是，都被粗糙蛮横地强制分类定性身份 — 封建反动的军阀, 民族资产阶级, 无产阶级. (其目的就是为了借助一部分人群的力量, 来斗另一部分人群, 已实现自己的目的.)

- 中国传统喜欢的做法是 : 树立起的圣人(儒家)的道德榜样, 使之具有道德权威. 与近代的"平等思想"趋势正相反, 这种哲学具有强烈的高人一等的优越感和等级色彩.


'''
====

.世上没有不被攻击的人, 每个人是每个人的敌人
[%collapsible%open]
====
- *有不虞之誉，有求全之毁.*  +
虞：预料。有意料不到的赞誉，也有过分苛求的诋毁。所以毁誉不必太在意。

- *善操理者-不能有全功，善处身者-不能无过失。* +
善于处理事理, 尚且不能完全成功. 善于修身的人, 尚且不能没有过失。 +

- 百善孝为先，论心不论迹，论迹贫家无孝子；
万恶淫为首，论迹不论心，论心终古少完人。 +
真正孝顺与否, 这个主要看心，不是看表面行为，不是说锦衣玉食给父母就是孝顺，假如这样的话，那么清贫的人家就没有孝子了。  +
真正好色与否, 这个主要看行为，不是看心，假如按心念论，世人都免不了面对美色动心，这样的话，世上就没有一个完美无缺的人了。

- 一人难称百人心
- 人上一百，形形色色shai。 人上一万，无边无沿.
- 一路玩意 惊动一路主顾, 一路宴席 款待一路宾朋。

- *政治家不惧怕人们的责备，但惧怕人们的轻蔑。这代表他在个人素质上不被承认。*

- 曾国藩:  +
天津的教会育婴堂和别处的一样，都会搜集和抚养孤儿，而且会对那些主动送来孤儿的人给予一定的奖励，算是辛苦费。但是有一些人渣，为了这几个钱，就拐卖正常人家的孩子送过去。当被人抓住时，这帮无赖马上就找理由，说是教会的育婴堂让他们干的(栽赃陷害)。于是就激起民愤。人们冲进育婴堂，把嬷嬷们杀了，把育婴堂也砸了。法国领事来处理, 结果互相动起手来, 死了几个中国人，法国领事也被人打死. +
清廷没人愿意出面负责处理这件事情, 最后就只能曾国藩出面处理，但这种事情谁处理谁倒霉. 曾国藩”实事求是”地查，发现没有之前中国人传言说的那些事. 曾国藩本来极高的名望，经此事后一落千丈。(所以也不要怪西方人自己保护自己侨民的做法, 那时中国人不靠谱.)

- 慈禧 : +
甲午惨败，每个人都骂西太后，整个国家、朝野上下都逼着她退位。 +
当时李莲英也被人骂得很狠，其实李莲英没有干预过朝政. 当然这并不意味着他没有权力.

- 袁世凯: +
袁世凯当选正式大总统以后，就把国会给抛弃了——追缴国民党议员的代表证书，然后就把他们驱散了。而**国民党代表当时占国会多数，现在他们一走，国会投票无法构成最基本的法定人数，就等于废掉了.** 这是袁世凯的错招，如果觉得议员不行，应该重选国会代表.  +
袁世凯的确因为签了《二十一条》而声望大跌。

'''
====

.★★★ 能打败你敌人的不是你的说辞(你不要幻想能说服他人), 而是你永不停下的行动 (既成事实大于一切)
[%collapsible%open]
====
- 人是不可能被说服的 (人只会被自己陷入的困境所打服). 屁股决定脑袋, 站位决定态度
- 预测未来最好的方法，就是去创造它。—— 林肯
- 英雄是"正在形成的事物"的捍卫者，而不是"已经形成的事物"的捍卫者，因为他就是"正在形成的事物"。 ——约瑟夫·坎贝尔

- 战士死了的时候，苍蝇所首先发见的是他的缺点和伤痕，嘬，营营地叫，以为得意，以为比死了的战士更英雄。但是战士已经死了，不再来挥去它们。
的确的，谁也没有发见过苍蝇们的缺点和创伤。然而，有缺点的战士终竟是战士，完美的苍蝇也终竟不过是苍蝇。

- 易中天: 面对一条大河，许多人都不敢过去。我却摸着石头一步步的走了过去，当别人嘲讽我说，你看这人弄的是一身泥泞，满身臭水的时候，打不起！我已经在河对岸了！你们还在河那边！

- *“面子”这种东西就不是靠别人“给”，而是靠自己“挣”的!*

'''
====



