
= (说服) 如何说服第三方 (方法论)


.权力在他方(即第三方), 而非在对方
[%collapsible%open]
====
辩论是一种“权力在他方(而非对方)”的话语体系。辩论, 本质目的不是为了说服对方, 而是为了拉拢第三方听众的数量, 扩大自己的_盟友_. → 即, 将”中立者”转化为”支持者”; 将”反对者”转化为”中立者”.

即表面上看彼此都盯着对手，其实心里是在想着怎样得到旁观者的认同。**对手其实并不重要， 他们只是我们向第三方证明自己更优秀的一个工具。**辩论其实是辩给第三方(陪审团)听. **辩论是针对第三方的，那些游移不定、看哪边都觉得有道理的观众，才是我们真正要争取的对象。这是辩论的基本策略，**也是辩论者要"讲究风度"的根本原因。

'''
====

.能获得观众"共情"者, 为最终赢家
[%collapsible%open]
====
辩论总会遇到论点出尽的时候，*能讲的都讲了，利弊都摆在这里并且反复质询过了，可形势仍然不明朗。这个时候，观众看的是什么呢？看谁更能打动(共情)自己。*

演讲要先和自己的支持者, 建立语言和情绪上的默联结。 而那些表情漠不关心的人，既有可能是"中立者"，也有可能是"反对者". 你的策略就是: +
→ 要将"中立者"转化为"支持者"， +
→ 并将那些不那么坚定的"反对者"转化为"中立者"。 +
→ 那些主动打断我们，提出刁钻问题的人，则是活跃的反对者。我们的策略是良好的应对挑战, 来强化"支持者"的关注，并转化部分"中立者"加入"支持者"的行列。

'''
====




.(人气)传播的背后是情绪。能激发人情绪的东西, 会被参与, 并传播.
[%collapsible%open]
====
- 根据"消费者体验的心理动线", *要对这六个关键时刻(场景): 感知→接触→触动→行动→消费→分享, 来进行布局(进行说服性动作) . 这其实就是研究广告的人总结出的一个模型而已.*

'''
====

.*在公共舆论上, 少数人密集持有的”激情观点”, 能够抵消(击败)大量冷漠的人的”温和,无所谓态度的观点”*
[%collapsible%open]
====
- 对某一事物或现象, 能够影响政治家的, 永远是那些"充满激情的，密集"发声的少数群体, 而不是"沉默的, 或持无所谓态度的"大多数. 即少数的“炙热”的观点, 在任何时候都能击败大数的“温和”的观点。 +
在许多问题上，普通大众因为缺乏相关知识, 或缺乏明确的意见，这时, 少数人的密集关心，就可能会主导民意测验的结果。 +
*所以, 所谓的“公共”舆论，永远只是一个小团体的观点, 而不代表大众的想法.*

- 网络骂战不像实际战争, 战争能通过消灭敌人的肉体, 来彻底让他们不再能够发声. 而网络骂战不行. 骂不死敌人, 他们是永远能够”卷土重来”的. 所以, 双方从来不能够一方完全压倒另一方.

'''
====

