
= (说服) 辩论带给人的益处是什么


.锻炼人的“批判性思考能力"
[%collapsible%open]
====
多数辩题都是正反皆言之成理的, 目的就是为了达成训练“批判思考". 为了竞赛的公平性，多数辩题都是正反皆言之成理的。正因为辩论可以培养这两项基本态度，因此对达成训练“批判思考”（critical thinking）很有帮助。

- 能培养辩手“换位思考”（decentering）的态度，即: 即使不同意对方的立场，也要体验从对方的角度观察问题。
- 能培养辩手“延迟判断”（suspend judgment）的态度，即: 深入思考问题，再作出“明智”（informed）判断，不要遽下结论。

'''
====

.能令人获得六项重要能力
[%collapsible%open]
====
训练辩论, 可以得到六项重要能力：①提升民主参与的能力、②孕育社会的领导精英、③培养求知的能力与兴趣、④接触与整合多元知识、⑤提升批判思考的能力，⑥提升口语传播能力等。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.接触与整合多元知识
|- 与通识课程比较起来，竞赛辩论是学生接触与整合多元知识的更佳途径。 +
台湾竞赛辩论的常见辩题，范围就广及法学、政治学、教育学、社会学、经济学、心理学与自然科学（例如核能辩论）。更重要的是，对多数辩题而言，单一领域的知识是不够的。辩论选手们必须将相关学科的知识整合起来，才能构筑出强而有力的论点，这等于是一种科技整合的训练。 +
+
以“安乐死应合法化”的辩论为例，虽然表面上这是一个“法律”题目，但一位法律系学生将很难只靠自己的本行应战。要想在竞赛辩论中取胜，除了法学以外，他可能还必须接触医学、社会学、心理学、哲学，甚至神学的知识， 并且将这些知识整合在一起。试问，有哪种通识课程可以达成这样的效果呢？

- 辩论选手们需要充分的证据与资料为后盾。在密集的准备过程中，许多辩论选手因此学会了搜集、分析与整理资料的技巧。

|2.提升批判思考的能力
|- 批判思考能力可以分为两大类： +
1.*判定"论证的性质"* : 判定证据的类型、*评估"论证的品质"*、判断**"证据与论点间, 是否有关联"**等 +
2.提出论证 : 选择有力证据, 来为个人立场辩护; 为问题拟出最佳解决方案; 预期对方的反对论证，提出高品质论证的能力等。

- 中国传统中, 不善于批判性思考. 古人怎么说，他便怎么信。造成这种习惯的原因主要有： +
→ 中国不讲究辩论术。 +
→ 事事主张退让, 和谐，因而真理泯没，是非颠倒.

|3.提升口语表达能力, 能建立参加者的勇气.
|
|===

根据辩论学者基利与特龙（Keele & Matlon，1984）对美国全国辩论锦标赛理念选手所进行的调查，发现其中有高达九成的人，后来至少获得硕士学位。

'''
====

