
= (说法) 辩论中的基本概念是什么

.推定 presumption
[%collapsible%open]
====
推定（presumption）：是辩论开始前，我们在某项争议问题上的既定立场。如果此一立场没有被足够的证据与理由给驳倒，我们就会维持对此一立场的支持.

*注意: 推定某事实对的，与它是否真的是对的，并没有必然关系，我们之所以支持它，是因为迄今没有证据让我们不支持它。* (即, 我们认为外星人不存在, 与它是否真的不存在, 没有关系. 我们现在相信该观点, 是因为至今没有发现反例存在.)

对于未知的事物: +
→ 如果我们预先认定它不存在，要推翻这个认定，只要等以后发现了它就行了。 +
→ 但是，如果我们预先认定它存在，要推翻这个认定，却需要彻底查找所有的地方才行，这往往是不切实际的。

所以，在实际上（特别是在科学研究中），在没有确凿的证据表明某个事物存在以前，我们都是认定它不存在的。

“推定”的观念, 被纳入了许多制度化的真实辩论中: +
- 法庭辩论中有所谓“无罪推定”，意思是任何人都是无罪的，直到有人先证明其有罪； +
- 议事及竞选辩论则有所谓“现状推定”，在新政策或新人选证明其优于现状前，我们能可保持不变。

'''
====

.举证责任 burden of proof
[%collapsible%open]
====
举证责任（burden of proof）: 就是挑战“推定”的一方，所必须担负的证明责任。 +
既然“推定”在被成功挑战前，将继续维持现状，那么确认了“推定”，也就等于确认了要由谁来发动挑战。所谓的“举证责任”（burden of proof）指的就是挑战“推定”的一方，所必须担负的证明责任。

做到什么程度, 算满足推翻了“推定”呢？ — 至少反对“推定”的理由, 要胜过原本支持推定的理由。*如果举证完毕后仍是五五开，那么多数人仍会选维持推定（因为改变是要付出额外风险的）。* 挑战推定的一方要达成六四开，或至少是51对49，才能赢得这场“反推定战争”。

'''
====

.辩题可分为三大类：事实, 价值, 政策。
[%collapsible%open]
====

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.事实辩题（resolution of fact）: 探讨某种现象，是否存在或发生。
|如: +
- 温饱是/不是谈道德的必要条件? +
- 艾滋病是/不是医学问题，不是社会问题? +
- 真理越/不会越辩越明?

|2.价值辩题（resolution of value）: 探讨某种主观评价, 赞成还是不赞成. 或为两种认识，排定优劣或重要顺序。
|如: +
储蓄（事项/主词）是良好习惯（判断/正面评价） +
后冷战时期，美国以军事介入支持民主国家的做法，是适当的 +
经济（事项/主词）重于（判断/大于）环保（事项/受词）

当评价或比较的对象， 是某种行动或政策时，“价值辩题”将与“政策辩题”相当类似.

|3.政策辩题（resolution of policy）（即“行动辩题”resolution of action）： 探讨某个个人或团体，是否应该采取某种行动。
|如 : +
你应该念医学院 +
我国应继续兴建核能电厂

不过, 政策辩题也有两个缺点 :

1. 政策辩论涉及许多细节问题，需要大量的资料作证，往往造成参加者的沉重负担。
2. 政策辩题涉及政策主事者（政府）及特定政策法令系统，较不适合跨国性辩论大赛使用.

|*"事实"、"价值"及"政策"辩题间，存在着一种层级关系 ——1. 做出何种"政策", 需由"价值判断"来做支撑; 2. 而该"价值判断"从何产生，就由"事实依据"来证明.*
|image:../img/0043.svg[,]

例如, 要证明“我国应全面禁烟”(政策)，支持者必须先证明“吸烟大幅度提高肺癌发生率”（事实辩题），再据以主张“吸烟是不良嗜好”（价值辩题），才能主张“我国应全面禁烟”（政策辩题）。

|===
'''
====

.民主制度中的辩论, 可分三类: 1.司法辩论, 2.议事辩论, 3.竞选辩论
[%collapsible%open]
====
民主制度中的辩论, 一般可分为三类：①司法辩论（judicial debates）、②议事辩论（parliamentary debates），以及③竞选辩论（campaign debates）。刚好对应于民主制度的三大部门(三权分立)——司法、立法, 行政。


[.small]
[options="autowidth" cols="1a,1a,1a"]
|===
|Header 1 |Header 2 |中立的裁决者

|议事辩论
|→ 立法
|保持中立的议员，或会场外的舆论。

|司法辩论
|→ 司法
|通常由一位法官、多位法官，或是陪审团来担任。

|竞选辩论
|→ 行政
|选民手中的一票
|===

这三类辩论的输赢, 都不是由辩论双方自己作出的, 而是由"第三方"来裁决的. 也就是说，无论是哪一种“正式辩论”，正反双方及其辩论的过程所扮演的，只是工具，目的在让"第三方裁决者"做出更好的裁决。

政治中 “正式辩论”的一项特色是，参加辩论的各方人马，通常不会以说服对方为目标。因为**他们知道，在制度设计上，对方是“不能也不会”被他们说服的** (人是不可能被说服的, 只能被社会打服)，他们要说服的是“中立的第三方”——观看仪式辩论的公众、欣赏竞选辩论的选民，以及聆听法庭辩词的法官或陪审团。

**而在生活中的“人际辩论”中，**辩论者中的一方往往也自认为是辩论胜负的裁决者，*“球员兼裁判”的情况很常见。*

'''
====

