
= 001 my core value
:toc: left
:toclevels: 3
:sectnums:
//:stylesheet: myAdocCss.css

'''


== 形象即资源


.你的形象举止, 只会产生两种影响：交往与回避。
[%collapsible]
====
**你的形象举止, 只会产生两种影响：交往与回避。**而他人对你的隔离与封闭, 会对你的成长造成很大阻碍 -- 成长只有在具体的一件件事情中, 才能渐渐积累起来，而其他人不与你进行这些事情，你也就没有机会（机遇）来完成你的“进化”。

- 人各方面的魅力(包括颜值)，所起的真正作用利益，不是引人喜欢，而是通过引人喜欢来带来“成长事件”的实现！吸引人不是最终目的，而是实现你进化目的的手段（诱饵、催化剂）。

- 女性应该利用自己的女性资本, 取得对自己有利的结果。 +
"露出你的大腿"（有目的的为了自身利益）和"张开你的腿"有很大的不同.

====


== 眼不见, 就会心不想






== 谋事者


.对于真正做大事(做大家业)的人来说，难, 阻力大, 敌人多, 他就会不干了吗？ 真正的懒惰，是头脑懒惰。
[%collapsible]
====
- 长年累月的刷手机不但荒废了学业，更荒废了对人生的思考 (永恒的转移了对自己大事的注意力). 他们没有考虑过前途大事，他们什么都不想，也什么都没做，就稀里糊涂地几年刷手机过去了，一到毕业，才发现没了去路。  +
农村孩子的主要问题是“不想事”。能力低，学历低，还不想事，这是很多青年最糟糕的地方。“裸奔”着走出校门，却又经受不住社会的毒打，到最后败给生活，甚至放弃生命。

- 大部分生活中的困苦, 只是你长期脑懒累积下来的最终结果而已。脑懒毁全家。

====


.分娩通常不会跟着计划走，你自己要有所准备。(预则立, 不预则废)
[%collapsible]
====
- 关键是阶段式计划性。你有没有想过未来三年，你会如何度过？未来三年，有什么关键节点？这些关键节点上的变化，你都会如何应对？你有没有应对的招数？你有没有抗风险的安排？(可能发生的国家战争, 运动)

- 有plan B了，我就能安心执行plan A了。

- 从创业的第一天起，你作为创业者都要有这个心理准备，每天要思考自己未来的10年、20年要面对什么. 你现在碰到的倒霉的事情，在这几十年遇到的困难中，只会是小小的一部分。
====

.你一直考虑什么, 你就会成为什么
[%collapsible]
====
- 想把一件事做好，就只能把这个行业里所有的事情打通。即: 要像项目负责人一样思考。我哪怕只是为了写好当时的一条段子，我也得像这个节目的制片人一样思考。*事实是, 如果你一直像制片人这么思考的话，你最后就是会变成制片人。*
====





== 行动是唯一能令你移动人生位置的

.自己认为很重要(表现在头脑里), 和清晰认识到很重要(表现在行动上)，往往不是一回事。
[%collapsible]
====

====


.不要站在原地哭，即使哭泣，也要在移动中哭泣。
[%collapsible]
====
- 不要站在原地哭，即使哭泣，也要在移动中哭泣。工作、吃饭、运动、休息、社交……再难过，这些该做的事情还是要做。因为秩序生活本身会帮你复原。*走着走着，你会发现，让你掉泪的事已经在你身后了。*

- 易中天: 面对一条大河，许多人都不敢过去。我却摸着石头一步步的走了过去，*当别人嘲讽我说，你看这人弄的是一身泥泞，满身臭水的时候，打不起！我已经在河对岸了！你们还在河那边！*

- 前进是一步步做出来的，那些身有多套房的人，是一套套投资买出来的！

====


.能打败你敌人的不是你的说辞(你不要幻想能说服他人), 而是你永不停下的行动 (既成事实大于一切)
[%collapsible]
====
- 预测未来最好的方法，就是去创造它。—— 林肯
====


.要做“难而正确的事”.
[%collapsible]
====
- 要做“难而正确的事”. *否则, 你有一万个理由说服自己不去做, 因为它不是你正确的路.*

- 你做某事, 自己得兴奋(有追求)。如果你自己都做得不兴奋，那成果也许还能看，但绝对不会成。

- 能不曲线救国, 就不要绕着走. *如果你绕着走, 费的能量，远远超过你直接面对它耗费的能量，而且你的青春不就蹉跎了吗？*

====


.星星之火，可以燎原.
[%collapsible]
====
- 星星之火，可以燎原. 一个小想法只要你天天想着，就会越来越变成动力做它，然后跨出第一步, 就会跨第二步，越行越专业！ +
但前提条件是，你要心里要永远惦记着（荆轲刺秦里面，秦始皇说，“朕一刻也不敢忘 历代先君一统天下的大愿!”）。否则，你的注意力就会被拉离这一点上. 比如你心里如果想着别的非上岸的东西（比如视频编辑学习之类），就会把你的注意力拉离上岸。没有燃烧你的星星之火, 没有实际去行动, 你永远停留在原地, 所以你永远缺乏入职条件。

====



.机会是留给有准备的人的
[%collapsible]
====
- 机会是留给有准备的人的，即，只要你平时每天做好了准备，就随时都有"走人"和"上位"的机会.  +
→ 你平时每天都在学习锻炼数学英语，就能随时去考研； +
→ 你平时每天都在针对性, 有意识的锻炼"考公"必需的能力，如演讲, 和待人接物，你就能随时去考公。


====








