
= argumentation 论证, 辩论
:sectnums:
:toclevels: 3
:toc: left
//:stylesheet: myAdocCss.css

---

== #辩论#

=== 辩论中的基本概念

==== 推定 presumption

推定（presumption）：是辩论开始前，我们在某项争议问题上的既定立场。如果此一立场没有被足够的证据与理由给驳倒，我们就会维持对此一立场的支持.

*注意: 推定某事实对的，与它是否真的是对的，并没有必然关系，我们之所以支持它，是因为迄今没有证据让我们不支持它。* (即, 我们认为外星人不存在, 与它是否真的不存在, 没有关系. 我们现在相信该观点, 是因为至今没有发现反例存在.)

对于未知的事物: +
→ 如果我们预先认定它不存在，要推翻这个认定，只要等以后发现了它就行了。 +
→ 但是，如果我们预先认定它存在，要推翻这个认定，却需要彻底查找所有的地方才行，这往往是不切实际的。

所以，在实际上（特别是在科学研究中），在没有确凿的证据表明某个事物存在以前，我们都是认定它不存在的。

“推定”的观念, 被纳入了许多制度化的真实辩论中: +
- 法庭辩论中有所谓“无罪推定”，意思是任何人都是无罪的，直到有人先证明其有罪； +
- 议事及竞选辩论则有所谓“现状推定”，在新政策或新人选证明其优于现状前，我们能可保持不变。

'''


==== 举证责任burden of proof

举证责任（burden of proof）: 就是挑战“推定”的一方，所必须担负的证明责任。 +
既然“推定”在被成功挑战前，将继续维持现状，那么确认了“推定”，也就等于确认了要由谁来发动挑战。所谓的“举证责任”（burden of proof）指的就是挑战“推定”的一方，所必须担负的证明责任。

做到什么程度, 算满足推翻了“推定”呢？ — 至少反对“推定”的理由, 要胜过原本支持推定的理由。*如果举证完毕后仍是五五开，那么多数人仍会选维持推定（因为改变是要付出额外风险的）。* 挑战推定的一方要达成六四开，或至少是51对49，才能赢得这场“反推定战争”。

'''


==== 辩题可分为三大类：事实, 价值, 政策。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.事实辩题（resolution of fact）: 探讨某种现象，是否存在或发生。
|如: +
- 温饱是/不是谈道德的必要条件? +
- 艾滋病是/不是医学问题，不是社会问题? +
- 真理越/不会越辩越明?

|2.价值辩题（resolution of value）: 探讨某种主观评价, 赞成还是不赞成. 或为两种认识，排定优劣或重要顺序。
|如: +
储蓄（事项/主词）是良好习惯（判断/正面评价） +
后冷战时期，美国以军事介入支持民主国家的做法，是适当的 +
经济（事项/主词）重于（判断/大于）环保（事项/受词）

当评价或比较的对象， 是某种行动或政策时，“价值辩题”将与“政策辩题”相当类似.

|3.政策辩题（resolution of policy）（即“行动辩题”resolution of action）： 探讨某个个人或团体，是否应该采取某种行动。
|如 : +
你应该念医学院 +
我国应继续兴建核能电厂

不过, 政策辩题也有两个缺点 :

1. 政策辩论涉及许多细节问题，需要大量的资料作证，往往造成参加者的沉重负担。
2. 政策辩题涉及政策主事者（政府）及特定政策法令系统，较不适合跨国性辩论大赛使用.

|*"事实"、"价值"及"政策"辩题间，存在着一种层级关系 ——1. 做出何种"政策", 需由"价值判断"来做支撑; 2. 而该"价值判断"从何产生，就由"事实依据"来证明.*
|image:img/0043.svg[,]

例如, 要证明“我国应全面禁烟”(政策)，支持者必须先证明“吸烟大幅度提高肺癌发生率”（事实辩题），再据以主张“吸烟是不良嗜好”（价值辩题），才能主张“我国应全面禁烟”（政策辩题）。
|===

'''




==== 民主制度中的辩论, 可分三类: 1.司法辩论, 2.议事辩论, 3.竞选辩论


民主制度中的辩论, 一般可分为三类：①司法辩论（judicial debates）、②议事辩论（parliamentary debates），以及③竞选辩论（campaign debates）。刚好对应于民主制度的三大部门(三权分立)——司法、立法, 行政。


[.small]
[options="autowidth" cols="1a,1a,1a"]
|===
|Header 1 |Header 2 |中立的裁决者

|议事辩论
|→ 立法
|保持中立的议员，或会场外的舆论。

|司法辩论
|→ 司法
|通常由一位法官、多位法官，或是陪审团来担任。

|竞选辩论
|→ 行政
|选民手中的一票
|===

这三类辩论的输赢, 都不是由辩论双方自己作出的, 而是由"第三方"来裁决的. 也就是说，无论是哪一种“正式辩论”，正反双方及其辩论的过程所扮演的，只是工具，目的在让"第三方裁决者"做出更好的裁决。

政治中 “正式辩论”的一项特色是，参加辩论的各方人马，通常不会以说服对方为目标。因为**他们知道，在制度设计上，对方是“不能也不会”被他们说服的** (人是不可能被说服的, 只能被社会打服)，他们要说服的是“中立的第三方”——观看仪式辩论的公众、欣赏竞选辩论的选民，以及聆听法庭辩词的法官或陪审团。

**而在生活中的“人际辩论”中，**辩论者中的一方往往也自认为是辩论胜负的裁决者，*“球员兼裁判”的情况很常见。*

'''




=== 辩论带给人的益处

==== 锻炼人的“批判性思考能力"

多数辩题都是正反皆言之成理的, 目的就是为了达成训练“批判思考". 为了竞赛的公平性，多数辩题都是正反皆言之成理的。正因为辩论可以培养这两项基本态度，因此对达成训练“批判思考”（critical thinking）很有帮助。

- 能培养辩手“换位思考”（decentering）的态度，即: 即使不同意对方的立场，也要体验从对方的角度观察问题。
- 能培养辩手“延迟判断”（suspend judgment）的态度，即: 深入思考问题，再作出“明智”（informed）判断，不要遽下结论。

'''


==== 能令人获得六项重要能力

训练辩论, 可以得到六项重要能力：①提升民主参与的能力、②孕育社会的领导精英、③培养求知的能力与兴趣、④接触与整合多元知识、⑤提升批判思考的能力，⑥提升口语传播能力等。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.接触与整合多元知识
|- 与通识课程比较起来，竞赛辩论是学生接触与整合多元知识的更佳途径。 +
台湾竞赛辩论的常见辩题，范围就广及法学、政治学、教育学、社会学、经济学、心理学与自然科学（例如核能辩论）。更重要的是，对多数辩题而言，单一领域的知识是不够的。辩论选手们必须将相关学科的知识整合起来，才能构筑出强而有力的论点，这等于是一种科技整合的训练。 +
+
以“安乐死应合法化”的辩论为例，虽然表面上这是一个“法律”题目，但一位法律系学生将很难只靠自己的本行应战。要想在竞赛辩论中取胜，除了法学以外，他可能还必须接触医学、社会学、心理学、哲学，甚至神学的知识， 并且将这些知识整合在一起。试问，有哪种通识课程可以达成这样的效果呢？

- 辩论选手们需要充分的证据与资料为后盾。在密集的准备过程中，许多辩论选手因此学会了搜集、分析与整理资料的技巧。

|2.提升批判思考的能力
|- 批判思考能力可以分为两大类： +
1.*判定"论证的性质"* : 判定证据的类型、*评估"论证的品质"*、判断**"证据与论点间, 是否有关联"**等 +
2.提出论证 : 选择有力证据, 来为个人立场辩护; 为问题拟出最佳解决方案; 预期对方的反对论证，提出高品质论证的能力等。

- 中国传统中, 不善于批判性思考. 古人怎么说，他便怎么信。造成这种习惯的原因主要有： +
→ 中国不讲究辩论术。 +
→ 事事主张退让, 和谐，因而真理泯没，是非颠倒.

|3.提升口语表达能力, 能建立参加者的勇气.
|
|===

根据辩论学者基利与特龙（Keele & Matlon，1984）对美国全国辩论锦标赛理念选手所进行的调查，发现其中有高达九成的人，后来至少获得硕士学位。

'''



=== 辩论的实战方法论



==== 权力在他方(即第三方), 而非在对方

辩论是一种“权力在他方(而非对方)”的话语体系。辩论, 本质目的不是为了说服对方, 而是为了拉拢第三方听众的数量, 扩大自己的_盟友_. → 即, 将”中立者”转化为”支持者”; 将”反对者”转化为”中立者”.

即表面上看彼此都盯着对手，其实心里是在想着怎样得到旁观者的认同。**对手其实并不重要， 他们只是我们向第三方证明自己更优秀的一个工具。**辩论其实是辩给第三方(陪审团)听. **辩论是针对第三方的，那些游移不定、看哪边都觉得有道理的观众，才是我们真正要争取的对象。这是辩论的基本策略，**也是辩论者要"讲究风度"的根本原因。

'''


==== 能获得观众"共情"者, 为最终赢家

辩论总会遇到论点出尽的时候，*能讲的都讲了，利弊都摆在这里并且反复质询过了，可形势仍然不明朗。这个时候，观众看的是什么呢？看谁更能打动(共情)自己。*

演讲要先和自己的支持者, 建立语言和情绪上的默联结。 而那些表情漠不关心的人，既有可能是"中立者"，也有可能是"反对者". 你的策略就是: +
→ 要将"中立者"转化为"支持者"， +
→ 并将那些不那么坚定的"反对者"转化为"中立者"。 +
→ 那些主动打断我们，提出刁钻问题的人，则是活跃的反对者。我们的策略是良好的应对挑战, 来强化"支持者"的关注，并转化部分"中立者"加入"支持者"的行列。

'''

== --------- ---------

'''

== #演讲#

=== 我的个人总结


- *不需要系统化讲解，删掉所有不重要的观点，只说几个重点*（系统化结构写在ppt上就行了，演讲时不重要的点一语带过，说话时间放在重要的点上）
- 面对不同的听众，要用不同的讲解精简方式。不要用教育讲课的方式，*不要对一个概念反复重复讲 -- 即, 不要用"画素描"的方式, 从粗到细地反复勾轮廓; 而要用"毛笔白描"的方式, 一笔过, 精准, 不来回勾。
- 重要的观点和举证案例，记下来，讲时别遗漏，否则就失去精彩点了。* (*不要翻来覆去讲同一个意思, 你拍自己的讲课短视频就知道了, 同一个意思(比如ps中蒙版的意思)前后反复讲, 会非常令观众厌倦和觉得啰嗦, 浪费观众的时间*)
- *话语安排别啰嗦.*
- 别"词不达意".
- 无关的话题，故事，不要在会议上说，不要浪费大家时间，可以私下聊。
- 不要把所有的你要讲的内容都写在ppt上，这就剧透了，导致听众会用“看”的而不是“听”你讲，他自己就全看完了。所以，ppt上只写关键词就够了，别把逻辑因果解释都写上去。逻辑解释必须听你说！

'''

=== 演讲(道)


==== 脱口秀就是制造“改变的幻觉”

- *人天然喜欢看成长，你要用五分钟的时间成长给他看，观众也会感觉自己在"成长"(幻觉)。 也许观众过几天就忘了, 但脱口秀就是制造“改变的幻觉”。*

- 脱口秀故事, 类似于电影中的主角. 五到十分钟的讲述之后，你需要有一个成长变化.  +
成长可以是你理解了你的父亲，走出了失恋阴影，也可以是戏弄了你愚笨的老板。  +
或者, 你也可以没解决任何问题，但是，你通过这五分钟让观众知道，你意识到了人生的无解 ——这也是一种成长，智慧的成长。


'''

==== 你有没有实现一上来就让观众觉得我是自己人?

要让人愿意相信你说的, 你的真诚是第一位的。要让对方接受你，心理上拉近彼此，敲门砖只能是情绪 (情感, 攻心为上)。之后, 你的说服, (价值观呈现), 才能对他人发挥作用. 检视自己 : 有没有一上来就让观众觉得我是自己人? (即亲和力, 如郭德纲就有对观众的亲和力)


'''

==== (脱口秀)你的目的是为了"共鸣", 而不是去”改变”尽可能多的人。

很多演员在看完别人的表演后会说，“他没啥毛病，就是没劲儿。” 那就是没有投入情绪，或者你俩没有共鸣。


'''

==== 暴露, 不是为了把真实隐私说出来，而是"还原"那份心情。

- 表演老师在教表演时，会强调演员在台上要学会保护自己(无论是演反派角色, 还是悲惨人物)，要记住舞台上都是假的，你进入的是角色，虽然你要用真情实感来演，但下了台要尽快抽离。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|脱口秀演员怎么抽离, 保护自己呢？
|我的办法是: 做到**只保证情绪永远是真的. 其他的文本可以是编造的，对人生故事可以做修改。** +
脱口秀表演中的自我暴露, 是有分寸的暴露. **暴露, 目的不是为了把真实隐私说出来，**而是把那种情绪带到舞台上。**是"还原"那份心情。** 故事的真实性并不重要, 怎么改头换面其实都可以， 关键是从中的"情绪"是真的.  +
讲故事，还原那个故事的目的, 其实你是在"还原"那个情绪.

|关键是"还原"，不要"表演". **能用演的就不要讲，能代入角色就不要冷眼旁观。**
|方法就是**把你要说的情境, "还原"在眼前。让听你说话的人仿佛看到了一样。情境本身的真假不重要, 我们的表演任务，就是让它变成真的。** +
能用演的就不要讲. *把那些啰唆的话语都删掉。你的目的是"还原"那个情境，而不是"告诉"大家发生了什么事。*

比如我说 “昨天我跟我爸说，爸，上海户口办下来了”, “啊，怎么做到的”，而不是说，“我爸就问我，那你是怎么做到的”。这句话没有必要，直接就开始表演就好。
|===


'''

=== 演讲(术)


==== 听众最多能记住7个要点, 但推荐只说3个点.


实验证明，一次记住3个要点最容易，记住7个要点需要比记住3个要点多15倍的努力，而记住10个要点就需要比记住3个要点多50倍的努力！所以，不能一下子输出太多的内容，小份高频的输入才有利于听众记忆。

麦肯锡对总结提炼的要求, 是要简化到几个要点呢？自然就是最容易记住的3点。有个笑话说，麦肯锡内部发言的开场白都一样，都是清一色的“我有3点看法……”如果有第4个要点要说，那就拆分成3a和3b，依然是以“我有3点看法”开场，然后补充“第3点分为两部分”。 +
所有事情都应尽量简化，但不能损失原味。

给别人讲述核心要点, 会强迫我们内化信息, 并用对方能听懂的语言将其重构. (其实就是翻译成你自己的话语说出来，看出其背后通用的底层逻辑.)

'''

==== 以15分钟为一单元

- 人能够集中精神“听一件事情(即"干货")的单元，大概是15分钟。之后的15分钟左右, 他可以听些不要紧的闲话、扯谈之类的。之后你再讲下一件干货事情, 依次循环。(番茄时间法, 一个单元是 25分钟) (15分钟, 不正好是比较长的短视频的时长么, 有其道理)


- 一场演讲，能让人记住三件事，已经是非常好的演讲了。剩下的时间，你就是逗他们开心，勾起他们的兴趣.
如果在相聚的两小时里面，你有三次让对方开心的笑，那对方应该是绝对不会记得你曾经提过几个无聊的话题的。
- 脱口秀行业有一句话：一个人摔跤的时候是可笑的，但是当一个人摔出血了就不好笑了。

'''


==== 故事, 是拆解成"小情境"与"大情境"的

你讲的故事, 可以拆解成小情境与大情境

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|小情境: *就是你的一个又一个段子，你在用这些小情境, 反复证明与拓展自己的价值观。*
|如果你有个段子经常忘，我的经验就是别讲。说明你就是不喜欢它。

|大情境: 就是你对整条线的主持.
|*这是三个小情境，你中间要有一个逻辑线把它串起来的。大情境就是我怎么把这些串起来，能体现你人格的完整性, 和你的"成长".* +
*要有"起承转合",* 就是你写的不能是趣事堆积，*也不能是你几个不相干的好段子联排。你在五到十分钟里要完成层层推进，要有主题有人物有冲突，最终有一个像结局的结局。*
|===

'''

==== 节奏感

一个人的节奏感，就是这个人在一个时间线上, *对信息量松弛的一个整体把控能力。*

一定要让观众在心理上跟你是一头儿的，*首先必须先"同步"，情绪，共鸣，都是为了同步。 接着, 一定还要"引领"，让观众对你表演的预测落空。还要无限循环, 不停找到同步，做出一点点引领，打破，重建，再同步，再引领。这过程光想一想你就知道它是有节奏的。*

听段子的过程中，你在等，就是"铺垫"; 你等到了，就是"梗"。  +
没等到，就是垮了.   +
如果你等的过程中走神了，那就是他没铺好。

有的演员是梗比较密，铺垫接梗，铺垫接梗，铺垫接梗. 有的演员是会铺很长，然后出来一个特别大的梗。 这就是不同的表演节奏.  +
**所谓的节奏就是嗒嗒/嗒，嗒嗒/嗒，有的人就是喜欢嗒嗒嗒嗒/嗒，也有的人就是喜欢嗒/嗒，嗒/嗒。** +
*好的脱口秀表演，节奏都是变的。如果是五分钟，你可以一直嗒嗒/嗒，嗒嗒/嗒，嗒嗒/嗒，但你要是超过十五分钟用一个节奏，观众会疯的。*

'''




