
= Psychology and influence
:toc: left
:toclevels: 3
:sectnums:
//:stylesheet: myAdocCss.css

'''


== 权力

==== ★★ 话语权即政治

*话语权即政治， 表达出的话语即政治. 是你很重要的权力！*

- 每个人都偏爱自己的主张——不是因为这是他(她)想出来的，而是该主张与他(她)的潜在信仰和偏好(即价值观)相适应（相一致）。
- *我的看法未必对别人有影响, 但对自己却很重要。这表达了你自己的价值排序, 好恶、爱憎，等等。*
- “那是他的价值观，我说的是我的！”
- 这一类问题往往并没有谁对谁错，关键要逻辑自洽. (但**逻辑自洽, 不等于就是真相.** 柯南探案中逻辑是自洽的, 但作品故事依然是编的)

'''


==== 一切问题的核心, 就是: 如何控制人(及其权力)

一切问题的核心, 都可以归源于一个核心点: 如何控制人的人性和权力.

- 官员管理问题, 宦官问题, 外戚问题, 中朝外朝问题, 诸侯军阀问题, 党争问题, 人事斗争问题, 抗击与控制少数民族入侵问题. 本质都是"如何控制人"的问题

- 有贤而不知，知贤而不用，用贤而不委，委贤而不信，此四者古今之通患也。
有贤才, 却不知道他们的存在， +
知道了贤才的存在, 却不使用他们， +
即使用了, 却不委以重任， +
即使委以重任, 却不信任人家， +
这是很多人会犯的错误。

'''




==== 如何限制权力？-- 分散权力

如何限制权力？最好的办法就是分散权力。

“三权分立”分为大中小三种： +

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|大三权分立 :
|党、议、行

|中三权分立:
|立法权、行政权, 司法权

|小三权分立:
|把行政权划分为: 决策权、执行权、监督权
|===



'''

== --------- ---------

'''
== 影响力


=== 先建立信任, 后才有可能发展关系

人与人, 你与陌生人之间的关系, 肯定是从最冷, 最敌意, 再到熟悉亲近的. 所以你生活中遇到陌生人对你恶语相向, 是非常符合这个心理逻辑的.


==== 做生意之前, 首先要建立起别人对自己的信任

*做生意之前, 首先要建立起别人对自己的信任. 换位思考: 你不相信别人, 你就不会放心去和别人做金钱交易.*

- 在对方心中还未建立起你的亲和性、可信度和权威感的情况下，就想说服对方, 是很少会成功的.
- 如果说客户只认识到了你的价值，但是并没有建立起对你的信任，一切就不会有下一步进展。
- 某些药，是为别的药服务的，它们被叫作“药引子”；同样，*某些沟通，是作为预备性的, 目的是为了让接下来的沟通更顺畅. 即, 在开展实际对话之前，我们有很多准备工作要做；在对话从浅水区. 渐渐迈向深水区的过程中，我们需要先建立起情感联系, 与基本共识.* (即: 郭德纲的"闲白"所起的功能)
所以, 那些演讲时，上台就急着煽情或者下结论的演讲者, 是不会有效果的.
- 双方已然失去了基本的信任，没有这个误会它也得有那个误会，没有事它也会生出事儿来。(两国关系也是如此)

'''



==== 必须先建立情感, 然后才有可能说服对方.

- 异性之间，顺序是: 先喜欢一个人的性格特质，然后才会对其肉体（性）产生兴趣，而非顺序相反。 不首先对一个人产生心理上的喜欢，是不会对其肉体产生爱的。
- 郭德纲再说评书前, 必先和观众闲白, 就是这个原因, 先建立起双方情感连接, 对方才会听你说事.
- 她说某品牌的安装师傅到家装空调, 会带一块布把这个地擦干净. 我说这块布要贵10％，*这块布擦的不是你们家地板，擦的不是你们家的机器，擦的是客户的心。*

'''



==== 情感是流动的

- 关系就如逆水行舟，如果没有得到改善、维持和发展，就会随着时间而衰退。人与人的关系不是变热就是变冷，没有保持不变的中间的关系。
- *任何一个运动系统如果要持续稳定地运行，必须要有持续稳定的能量源源不断地注入；否则，系统就会紊乱(熵增)，甚至崩溃。婚姻也是运动的系统，它若要持续稳定的运行，也需要持续稳定的能量源源不断地注入。*
- 感情是流动的，因而必须要有不流动的合同来规范我们的行为(做生意上)。

'''



==== ★ *把社交看做吃饭、睡觉一样自然。不需要什么心理负担.*

- 社交就像吃饭、睡觉一样重要，同样，也应该像吃饭、睡觉一样自然。*不要对它抱着过高的期待和目标，把它放低一点，让它成为你生命中一件自然而然的事情，把它跟你的形象、评价、标准松绑。*
- 你很难喜欢上嘉宾, 可以这样操作: 别把他想象成一个真人，你们可能这辈子都不会再见面了，你就当采访一个NPC（非玩家角色），就隔离那个情感。

- 对方也在乎你对他们的看法. 台上表演者, 也希望台下观众能与自己互动越热情越好. 而不是收到冷场.

'''



==== *不要欺骗别人，能被你骗到的都是相信你的人。*

'''


==== *要想人与人之间做事能顺利的话, 必须先建立"处理问题"的机制(如同"合同"的逻辑一样)*

- 夫妻之间应该建立一种就矛盾冲突进行讨论的机制（平等地位、就事论事, 相同权利）。如果没有机制, 很快地，争吵的焦点就不是本来要讨论的事情，而是“对方的态度如何不对”这种"机制"上的问题了. (所以, 美中两国对话, 就要先建立起双方对话的机制, 双方先达成共识.)

'''

== --------- ---------

'''

== 说服

==== (人气)传播的背后是情绪

(人气)传播的背后是情绪。能激发人情绪的东西, 会被参与, 并传播.

- 根据"消费者体验的心理动线", *要对这六个关键时刻(场景): 感知→接触→触动→行动→消费→分享, 来进行布局(进行说服性动作) . 这其实就是研究广告的人总结出的一个模型而已.*

'''



==== *在公共舆论上, 少数人密集持有的”激情观点”, 能够抵消(击败)大量冷漠的人的”温和,无所谓态度的观点”*

- 对某一事物或现象, 能够影响政治家的, 永远是那些"充满激情的，密集"发声的少数群体, 而不是"沉默的, 或持无所谓态度的"大多数. 即少数的“炙热”的观点, 在任何时候都能击败大数的“温和”的观点。 +
在许多问题上，普通大众因为缺乏相关知识, 或缺乏明确的意见，这时, 少数人的密集关心，就可能会主导民意测验的结果。 +
*所以, 所谓的“公共”舆论，永远只是一个小团体的观点, 而不代表大众的想法.*

- 网络骂战不像实际战争, 战争能通过消灭敌人的肉体, 来彻底让他们不再能够发声. 而网络骂战不行. 骂不死敌人, 他们是永远能够”卷土重来”的. 所以, 双方从来不能够一方完全压倒另一方.

'''


== --------- ---------

'''

== 做事 (是"获得你的影响力", 或"展现你的影响力"的必经方式)

==== 权力与责任必须对等

- 消费者购买某产品, 必定要通过"用户之旅"的全过程. 所以不能让负责最前端内容推广的公关人, 直接承诺最后一个环节的销售成果.

'''

==== 做事不要怕! 你的态度应该是从"自我沉浸" 改为"自我抽离"

.做事不要怕! 正确的做法是什么呢? 从"自我沉浸" 改为"自我抽离"(就像演员演戏一样). 不要把自己代入, 而是站在第三方角度, 来考虑你担心中会遇到的问题:

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|原因
|造成这些问题的原因是什么？包括表面原因, 和深层原因.  +
其中有哪些是由于我行动不当所导致的？有哪些是我无法控制、无法决定的？

|结果
|如果换了别人，他是否会跟我碰到一样的问题，会做得比我更好吗？

|带来的影响
|这个问题有哪些可能的结果？它们发生的可能性有多高？对我有多大的实质影响？ +
其实很多无论为何种结果，对你都没有实质性的影响。
|===

- 我经常劝年轻人，不要害怕，你的上级把任务交给你的时候，预期就是你会搞砸。你为什么觉得他会把一个绝对不能搞砸的事情, 交给你呢?

'''


==== "有用"比"绝对为真"更重要.

- **科学界一般公认，没有任何一种理论百分之百绝对正确。判断它真正价值的, 是它的实用性 (比如量子力学理论)。**即 : 对“某知识”的价值评判, 不在于其在哲学上是否绝对为真实，而在于它是否能让人得到力量。(即, 别本末倒置. “判断为真”只是手段, 不要把手段当目的.)

'''


==== 只要是人制定的、做出来的，就一定是有漏洞的（不完善的）

.事情是人做出来的, 规则是人定出来的, 只要是人制定的、做出来的，就一定是有漏洞的（不完善的）、需要改进的, 创新的。(否则, 人类社会中的一切就不会再发展.)

- 重要的是，这些路不是用来局限住你的，而只意味着提供你一些选择的途径. *没有创新精神的人, 永远也只能是一个执行者。*
- “理在事中”，能成事就是有理。世事往往是“以迂为直”。如果两点之间的直线阻力却最大，那么这根直线，其实是最远的路径。
- 在“我是对的”和“有效果”之间，你必须做一个选择。你认为的好坏，和你的婚姻关系相比较，哪个更重要？

- *所有伟大的真理开始都离经叛道。权威的思想将它的某些力量赋予敢于向它挑战的人。没有创新精神的人永远也只能是一个执行者。* (就像郭德纲说的: 唱戏, 到七老八十了还亦步亦趋前人的做法? 你不可能永远是一个学徒!)

- 向那些疯狂的家伙们致敬，他们特立独行，他们桀骜不驯，他们惹事生非，他们格格不入，*他们用与众不同的眼光看待事物，他们不喜欢墨守成规，他们也不愿安于现状。你可以赞美他们，引用他们，反对他们，质疑他们，颂扬或是诋毁他们，但唯独不能漠视他们。因为他们改变了事物。* — 乔布斯

'''



==== 路径依赖, 是没有目标的表现

- "因为以前这样做，所以现在也这样做..." 这个思考是错的。这样的路径不是根据目标来的，是**根据以往习惯来的(即路径依赖)，这是没有目标的表现。 (必须倒过来想, 以终为始. )**

[.my1]
.案例
====
对用户来说，他关心的是速度, 比如"扫描速度从20秒提升到10秒". 这个目标实现了，留存率自然就上来了。而不是公司一开始就把目标设计成"留存率"或用户"使用次数"，因为这只是"公司角度"的目标和需要, 而不是"用户"的目标和需要. 所以一定要站在用户的角度来考虑问题. 在“速度”这个目标下, 又能分解出很多个子目标.
====


'''


== --------- ---------

'''



== 借力 (好风凭借力, 送我上青云)


==== 要得到一样东西, 卡位很重要，近水楼台先得月

要得到一样东西（比如地铁上抢空位），卡位很重要，近水楼台先得月。

- 同样，**要借助某权势人物的力量，卡位成为他们关系上最近的人, 是非常重要的。没人能在第一步就直接看到最后一步该怎么做, 但很多人还是能走通, 为什么？就在于他们的性格 -- 他们是通过试探，来一步步验证每一步的行动有效与否的，他们天生就有一种探索的乐趣精神，最终能摸着石头走过整条河。而不是要靠别人来告诉他们每一步该怎么走。**他们自己天生就是极强的探索，复盘，有效行为迭代，和不在意失败的开拓精神。

'''

== --------- ---------

'''


== (观人) 你会怎么看待他人, 你对他人如何做出判断

==== ★★ *“可预测性”是对”稳定性”的判断，“可展望性”是对”成长性”的评估。*

- 如果你十次有八次把事情做到80分，两次做到60分，上司对你的预期就是80分；  +
如果你十次有六次把事情做到100分，四次不及格，那上司对你没有稳定的预期。

'''


==== ★★★ 人的价值，在遭受诱惑的一瞬间被显现

*人的价值，在遭受诱惑的一瞬间被显现. 别人对你价值的判断, 是步步试探, 从你的态度反馈上得出来的.*

- **权，然后知轻重；度，然后知长短。**物皆然，心为甚。 +
→ 权：本指秤锤，这里用作动词，指称物。  +
→ 称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。

- 相形不如论心，论心不如择术.  +
观察人的相貌, 不如考察他的思想; 考察他的思想, 不如鉴别他立身处世的方法。

- 其实我并没有傻到每次约会都带女儿，我只是想试一下，他对我女儿的态度。


- 不要对自己提出提高薪水的要求感到愧疚：人做的最愚蠢的事情之一，就是有的人总是白干活。 *不要把自己白白捐献出去，否则，你不仅会失掉你应得的钱，还会贬低自己在别人眼中的价值。*

- 头部主播奉行的这种全网最低价，对品牌来说是慢性毒药。*当消费者长此以往习惯低价，品牌溢价就没了，以后价格很难上去。(形成了不该有的条件反射, 固化印象)*

- **你最低所需要的, 不等于你的价值。**在研究生时，我一年12,000美元也活得很不错。可是，我会因为生存只需要12,000美元, 就只要求拿这么多的薪水吗？ *如果你只想着你需要的程度（维持最低生活的），你永远也不会得到你所值的（与你价值相符的）。*

'''


