
= 创作 (表演与电影)
:toc: left
:toclevels: 3
:sectnums:
//:stylesheet: myAdocCss.css

'''

== (道) 好的电影作品的原则


==== 好的电影, 能够提出重要的问题 → 人生的问题, 社会的问题

*“值得拍”的电影，会反映我们人生的问题, 这个世界的问题. 传递强烈的情感 -- 让观众陷入难以抉择的难题中，反省自己根深蒂固的某些观念.*

[.my1]
.案例
====
- 表面上, 《不羁夜》（Boogie Nights）是对七十年代洛杉矶色情业工作者的淫猥一瞥，但实际上，它想表达的是: 个人在"站队文化"中寻找自我. 反映人们的价值观与身份, 是如何随着科技的发展, 而变化. 以及电影媒介本身的浪漫与脆弱。
- 表面上，《正午》是一部小镇警长式西部片，讲述警长努力在镇上寻求帮助却无人响应，只能孤身对抗犯罪团伙的故事。但它底层的内核主题, 是反映民粹主义盛行下的政治怯懦。
====

*坏的电影都在讲剧情; 好电影都在讲人(人性), 哪怕这些角色并不是人类。*

'''

==== 电影一定要表达出导演个人化的价值观

电影一定要表达出导演个人化的价值观, 和审美品味. 你作为导演, 就要为影片注入个人风格 (xx作品). *既然由你来导演这部影片, 那一定就是反映的你的想法和价值观, 而不是别人的. 否则还要你来拍干嘛?* 随便找个人去拍就行. 很多自编自导型导演, 他们的作品无疑都能反映导演本人的思想、 品位、观点以及执念。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|差的导演:  |好的导演:

|- 只在特写镜头、中景镜头和主镜头之间来回切换. *他们要么在随便剪辑, 而不是在引导观众。*
- *要么通过过度剪辑的特写镜头, 对观众进行过多的引导，让我们没有选择的余地。*
- 平庸的作品, 就是给人感觉: **它不是诞生于个人的独特想法，**而是诞生在好莱坞流水线模式下. *他们的电影毫无"个人特色", 或者"作者表达"可言。*

|*会通过各种手段, 不断影响观众的感知与预期 — 引导我们的眼睛和情绪, 心情.*
|===

'''


==== 差的电影主题常犯的错误 : ①廉价心灵鸡汤, ②灌输说教, ③只有剧情, 却没故事.

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|廉价心灵鸡汤
|即: 只表现最浅薄的"真善美".

|灌输说教
|即 : *主题过于直白、恨不得打在广告牌上直接告诉你. 这样的影片会让观众感觉在被灌输思想，而不是受到自动的启发或获得娱乐。* (中国春晚的小品) +
一个好的剧本, *要让观众自己去思考，挖掘其中的深意。(展现而不讲述.)*

|这部电影只是一个剧情PPT，还是一个引人入胜的故事？
|我讨厌剧情 (只是干瘪瘪的骨架)，但我喜欢故事 (有血有肉, 深谙人类心理学)。

|===

'''

==== 要展现, 要不要去阐释 exposition

阐释（exposition）是编剧的一大禁忌。“阐释”就是通过对白, 来解释角色的背景, 或展现内在的情感。

为什么 exposition 是糟糕的?  因为它会带来这些负面作用:

- 阐释会对影片的"可信度"造成负面影响.
- *阐释会破坏影片的节奏.* 特别是当角色突然停止行动，开始讨论他们早就心知肚明的事情，只为让观众了解情况时。*这种停顿, 就会破坏故事的节奏.*

可以用其他更好的方法来实现 exposition, 如: 边走边聊

'''

== (术) 让观众有代入感, 如何抓住观众的心?

如何持久地把握住观众的好奇心? 一个好剧本，*要做到能掐住观众的咽喉，一刻都不松手。要逐渐将信息释放给观众 (即要一直吊着观众的胃口).* +
*每隔一段时间，这个剧本就应该释放足够的信息 → 让观众对接下来的故事发展保持好奇(吊胃口, 犹如爱丽丝漫游仙境一样, 一幕一幕都令人有悬疑感)，永远不觉得出戏、无聊或者毫无头绪。*

[.my1]
.案例
====
- 《唐人街》中，汤小心翼翼、一点一点地释放关于侦探杰克·盖特斯, 和他调查的洛杉矶富人家庭的信息，使观众全程保持精神集中，直到最终揭开真相。
- Manchester by the Sea 中，导演像折纸一样架构故事，随着折纸一点一点展开，我们也一步一步了解了钱德勒在几年前经历的惨剧。采用这个结构是因为钱德勒一直在想尽办法封闭这段记忆，埋藏过去的悔恨。换言之, 如果处理得当，影片的结构就是由角色的性格来决定的.
====


'''

==== 方法: 故事发生的环境要让人有"真实感”

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 这个世界好不好看不重要，重要的是它是否真实? *要真实到能够让观众相信, 并彻底沉浸其中.*
|<天国王朝>中, 那些环境场景, 真的让人如同回到了中世纪的欧洲

|▶ 画面的背景中, 发生了什么？告诉了我们什么？*画面的背景, 是在帮助叙事，还是分散了观众的注意力？*
|*这些环境能反映生活在其中的角色的个人特点，就好像我们的房子能反映我们的性格一样。* +
这就是普通的背景, 和优秀的艺术设计, 的区别 -- 前者是演员在静态背景下演戏，后者是在看得见、摸得着的世界中生活。

那些让人看完就忘的电影，里面所有的房子都带着千篇一律的白木桩围栏，所有的角色都穿着毫无特色的Dockers或者J.Jill 。这些片子的艺术指导, 没有为丰富"角色内涵"再做点儿什么，他们只是去商场买了点儿东西回来敷衍了事，除了搭建一个好看的背景供演员表演，他们什么也没做。

|▶ *艺术设计, 唤起了你的哪些感觉？它们反映出了怎样的情绪？*
|.好的艺术设计, 要能帮助叙事，而不是分散观众的注意力.
**艺术设计的最终目的, 不是为了表面上的搭建物理场景，而是为了传递重要的"心理和情感信息"。**最好的艺术设计, 是难以察觉、不着痕迹的，观众可能根本意识不到它的存在。但**艺术设计绝对不能完全消失，因为它有着"传递信息"和"表达情感"的作用。会对观众的"心理情绪"产生影响.**

后者才是本质目的，如同你建立自己的"设计方法论"时, 对"设计元素"的分解分析一样，看它们会带给人, 怎样不同的情绪体验, 这就是"各种元素"和"风格"所能起到的作用, 它们的价值所在. *如果这些东西不能给人带来你想要的情绪体验, 它们就没有存在价值.* 正如<大逃杀>中的核心观点 -- 要成为有生存价值的成年人(元素).

[.my1]
.案例
====
- 为了凸显人物在政府机构面前的渺小无力，艺术指导故意突出建筑物的高大冷酷，给它们涂上了一层法西斯的色彩。
- Stanley Kubrick 的电影, 一直都是利用夸张设计, 来激起观众强烈情感反应的. 如《The Shining‎ 闪灵》中阴森空荡的远望酒店. 酒店内新旧装饰元素的诡异交融、高得夸张的天花板、俗气的色彩搭配，以及反复出现的迷宫式设计母题 （motif），目的都是为了给观众, 营造出这样一种感觉 -- 好像被什么强大而邪恶的力量, 压得喘不过气来。
====

电影一定要尽量多给观众一点儿信息，用画面和信息淹没他们。如此一来，一部电影便可以重复欣赏，影迷每次重看都会有新的发现。


.不同颜色或色调, 会带来何种的象征意义和情感? 会触发观众相应的反应。
这些色彩是在帮助叙事，还是衬托、暗示当下已经很明显的情绪和信息？

[.my1]
.案例
====

<Precious> 讲述的是一个被贫穷与家庭暴力围绕的女孩的成长故事。但导演依然使用了鲜艳的背景色, 目的是想要捕捉她在不屈不挠、努力求生中, 展现出的活力与乐观精神. “我们既要展现痛苦，也要展现美丽。”
====
|===


所以, 设计部门和美术部门最累. +
对细节的打磨，导致设计部门和美术部门通常都是最早开工. -- "我们会尽力为后来者设立一个高标杆，这样一来，任何人都没有理由偷懒", "这也是为什么我们把那么多的时间都花在素材积累上".

'''


==== 方法: 攻心.  让观众对主角的命运产生关心

*只有当你(观众)对这些人(角色)产生了关心, 你才会进一步关心和主角相关的一切.* +
*所以在电影的开场处, 就要让主角有足够的吸引力或角色深度，让观众愿意跟随主角到天涯海角 (如同你对情人一样)*（或者至少跟到影片结束）。

即使是塑造令人讨厌的角色，好的编剧也要赋予他值得同情的点。因为如果没有这些特点，编剧对这些角色, 就不会有兴趣去塑造. (即使是反派, 也要有魅力. 有魅力的反派更能衬托主角的魅力, 人是互相抬高的. 优秀的敌人能衬托出你更优秀.)

[.my1]
.案例
====
Angelina Jolie 在 <Salt 特工绍特> 中，她扮演了一个俄国间谍。这样的角色一般并不需要太多观众的共情，但**没有共情, 演员就很难与观众形成情感联系.** Angelina Jolie 想要搭建这种联系, 所以其实这个角色身上很多极端的地方, 都是她自己塑造的.
====

'''

==== 方法: 人的魅力来源于"看不透", 和"难以预测", 这些心理学

角色让人真实可信, 又觉得难以预测 (难以预测才会带来性格魅力). +
*神秘感起到了重要的作用：伟大的演员能不断勾起我们的好奇心.* +
既要"透明"到能让观众瞬间了解角色，又要"内敛"到让观众好奇角色下一步会怎么做。

'''

==== 方法: 用“局内人”视角, 让观众更有代入感

要清楚电影的视角：是谁在银幕世界中引领观众？我们是透过谁的眼睛和情感, 来看待故事中的矛盾冲突、悲欢离合、失败与成功的？要确保“从剧本到片场”（再到银幕）全程视角一致。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|视角有两种:
|- 某个角色的主观视角 (局内人视角)
- 如上帝般, 冷眼旁观的视角 (局外人视角)

[.my1]
.案例
====
- 《拆弹部队》的视角类似于第三方的记者视角，从来没出现全知视角（omniscient eye）——即镜头永远不会拉到一定距离之外，用“上帝视角”来观察银幕上发生的一切.
- 《后窗》几乎全程都是通过主角视角来进行叙事。镜头全程陪伴杰弗里斯，我们只能见其所见，闻其所闻. 但在影片的某一个场景中，*趁着杰弗里斯入睡，镜头向观众透露了一条关键信息。这条信息对于观众理解整个故事有着重要作用，但是主角自己并不知情。这是一招不着痕迹的作弊手法，目的是让观众对接下来的故事走向更加好奇。*
====

通常来说，优秀的导演手法, 应该介于这两种极端之间 —— 私密但持重；客观但不冷淡；处在一定距离外冷静观察，但仍保持尊重与同情。


|镜头目标, 声音, 都能表达出"以谁为视角?”
|摄影机摆在哪里，*镜头反映的是谁的视点，观众是通过谁的耳朵听声音，电影配乐是在传达谁的内心情感，都取决于角色和角色视角。* (红楼梦中, 第二次, 读者是跟着刘姥姥的目光与感受, 来体验大观园的)

|好的艺术设计, 还能进入主角的视角。
|
[.my1]
.案例
====
<Black Swan> 中, 通过对镜子、窗子等带反射面的母题运用，来展现一位芭蕾舞女演员的心灵走向崩溃的过程。
====

|===

'''

==== 观众的自我想法, 也在帮助塑造角色 (一千个读者心中有一千个阿姆雷特)

- 你可以通过看得见的东西讲故事，也可以通过看不见的东西讲故事，如果你把什么都展现给观众, 那就没有什么东西是重要的了 (没有了观众能参与的想象力了).
- 从这一刻起，观众也加入进来，赋予这个之前只存在于纸页上的角色, 更多的含义，和演员一起塑造角色。
你(观众)看完电影后，也会往角色身上加上自己的想法(你自己对角色的人物分析)。你也同时在为演员充实这个角色。


'''

== (术) 如何让故事的推进更自然?

==== 故事必须有"起承转合". 每个场景, 必有它要达成的目的.

如果一部电影的展开, 只是从A点走到B点，再到C点再到D点，就犯了“ 章节化”（episodic）的问题. 就是场景只是机械地串在一起，起承转合过于生硬，缺乏连贯性，而不是自成一体、一气呵成。

*每一场戏一定都是有它的目的的: 1.为了推进故事，2.揭露和角色有关的信息，3.为后来的剧情发展做铺垫。* +
*不能“推进剧情”或体现“角色发展”的场景, 都要删掉。*

'''

==== 角色对故事阶段的推进, 背后必有动机支持

演员**要弄清楚这些角色从何而来(想要获得的欲望需求是什么?)，要去向何方(行为动机指向哪里?)，以及在具体的某一刻，他们处在什么位置(每个阶段, 不同阶段的困境)。** (即角色意志的 过去, 现在, 和未来)

*差的故事, 没有任何情节驱动力。编剧只是为了给主角找事做,* 而给他强加不合情理的难题。*缺乏"为什么要必须去做它"的动机, 观众就不会理解角色行为, 也就没有了共情.*


'''

==== 用环境, 来展现"潜台词”

如果离开冗长的对话场景，编剧就不能清晰地展现角色和角色动机，那就是一个坏剧本。

'''

== (术) 角色塑造

==== 表演

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 研究人物
|好的演员, 要做的第一件事就是分析角色，拆解每个角色的对白和行为，理解角色说的每一句话、做的每一件事（或者不做的事情）背后的含义。(正如郭德纲所说: 说三国, 发生了什么事情不重要, 重要的是分析人物背后的心理和动机, 这些底层原因, 才是导致各种表层事件发生的源泉. )

|▶ 真实, 才会令人相信, 进而引发情感
|*衡量一个演员表演的好坏，是看观众是否获得情感共鸣*：演员的表演, 是帮助了我们进入银幕中的世界，还是让我们觉得出戏？ +
一部电影一定要让观众觉得可信，细到每一个词、每一个眼神、每一个领带夹、每一个茶杯，*都要"真实可信"。只有这样, 才能激发出他们的情感, 而不会因为"太假"而引不出真情.*

- 很多灾难特效大片, 打动不了观众, 就是因为它们都只是呈现灾难和奇观的载具. 这些电影只有剧情，没有故事；只有角色，没有人；只有刺激，没有感情。总而言之，没有可信度。
- 最忌讳被观众发现表演痕迹的类型片，可能是喜剧片。很多演员都会告诉你，演喜剧的时候，千万不能一心想着逗人发笑。*如果观众感受到演员是在故意演给他们看, 他们就会出戏.*

|▶ 要表演, 不要模仿
|演员要演出角色的心理状态. **你不是在演一个混蛋，而是要把你内心的那个混蛋展示出来。因为"模仿"并不属于"角色刻画"，**不会**揣摩角色的心理活动，**也不会**为他们塑造一个完整的内心世界。**这样就无法打造一个活生生的人、一个能透过屏幕与观众达成情感连接的人.

[.my1]
.案例
====
一个演员要在电影中模仿尼克松, 轻而易举, 但如果只做到这一点, 那他在艺术性上绝不会比 <The Tonight Show 今夜秀> 中 Rich Little 的"尼克松模仿秀"高明到哪里去。
====

浮夸的说话风格和装模作样的动作，让他看上去更像是个搞笑演员在模仿，而不是在呈现一个真实角色。

尽力保持克制，不到万不得已时千万不要哭，不要喊，更不要浮夸。否则，演员呈现的只有"情感主义"（emotionalism），而没有"情感"。电影并不需要演员像演话剧那样, 抑扬顿挫地讲话，或者动作举止夸张激烈。要让情绪自然流露。 +
要想演活一个角色，意味着你的走路、说话、思考、生活方式, 都要和角色一致。你可以留心演员在不说话时，脸上是否会失去一些神采；或者当另一位演员在说话时，他能否像注意自己的台词一样, 注意对方的台词。(即对”角色身份”的投入性, 是否能一直在保持延续中?)

|▶ 细节 : 能突出人物性格
|细到“这个角色是会把衬衫的纽扣全都扣上，还是会解开四个纽扣或六个纽扣？*因为所有这些特征, 会告诉剧中的其他角色, 这是一个怎样的人?”。*

.眼睛是不会撒谎的
电影是一个“看脸”的世界，它是一个被特写主宰的媒介。*很多时候，成就一段精彩表演的，只是演员最简单的、最直接的一个眼神。*

[.my1]
.案例
====
<The Silence of the Lambs 沉默的羔羊>中的 由 Anthony Hopkins 演的 Hannibal Lecte ) 他把这个角色想象成一只介于猫和蜥蜴之间的生物：“他是一个不会眨眼的人，他可以好几个小时一动不动，就好像一只狩猎的螳螂, 观察着，然后再展开行动。”
====

|▶ 演员本人的魅力气质, 是否与角色相符
|电影明星, 历来和他们参演的电影, 有一种矛盾关系: 明星的名气能拉来投资, 但明星也要放下架子服务于角色本身, 而**导演在这个过程又不能破坏明星的魅力，否则就失去了邀请大明星参演的意义。**

[.my1]
.案例
====
- <Hyde Park on Hudson> 讲的是罗斯福总统和一个远房亲戚的婚外情，话题较敏感，唯有 Bill Murray (<迷失东京>男主) 能驾驭这个角色。因为他身上有种特性，能让你对他的错误既往不咎。
- <The Hurt Locker 拆弹部队> 中最大牌的演员 Guy Pearce 在第一场戏中就遇难身亡. 当 Jeremy Renner (复联的"鹰眼") 出现并取代 Guy Pearce 的角色成为上士时，观众对于 Jeremy Renner 的陌生感, 会让这个角色的命运多了一份不确定性。如果你把这两个演员的角色对调, 你就会知道要在《The Hurt Locker》中营造不确定性和强烈的临场感，正确的选角有多么重要。
====

|===



'''

==== 镜头: 摄影机的机位选择, 对观众有心理暗示作用。

基本上， 电影语法就是建立在三种镜头之上： 远景（ long shot）、中景（medium shot）和特写（close-up）。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|远景也叫“全景”（wide shot）(*反映角色身处的"环境"*):
|全景镜头视野非常广阔。*如果全景镜头中有人，那么人物通常是处于次要位置，镜头中的自然环境或者人造环境, 才是主角。* +
因为远景镜头能够传达很多关于时间与地点的信息，所以它们通常都是用来作定场镜头.

|中景镜头(*反映角色的"行为, 动作"*):
|展现的是角色如何移动，如何和其他人接触、交流。 +
用中景镜头拍摄时，你可以看到角色腰部以上的画面（不要将"中景镜头"和"中特写镜头"混淆，中特写镜头拍的是人物胸部以上的画面）。 +
*中景镜头通过角色的行为, 能让观众对角色产生同情或者疏离的情绪*。

|特写(*反映角色的"内心心理,情感"*):
|就是将镜头放在距离人物面部. +
*特写成了一种极富心理暗示的电影语言，通常用来直白地，甚至令人不适地展现角色的脆弱与瑕疵。*

|▶ 摄影机放在哪里？它为什么在那里？如果摄影机在移动，它移动的原因是什么？
|- *摄影机的位置如何移动, 能增强某个场景的情感冲击力？*
- *镜头运动, 是如何营造活力感、宏伟感、历史感和紧张感的?*

对于每一个行为或问题, 你都要去思考其背后的原因及答案, 这才能使你成为"谋事者".
|===


'''


==== 服装 : 能帮助展现角色的性格

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 是演员穿着衣服，还是衣服“穿着”演员？
|服装不仅能体现一个角色的阶层地位、家庭背景，甚至宗教和性取向，还能传达角色隐秘的欲望和追求的形象。服装应该“能表现角色的灵魂”。

[.my1]
.案例
====
Pearl Harbor 珍珠港中的演员造型更带着一股明星写真的味道，Ben Affleck 和一众影星根本不像是在拍战争片，倒像是砸重金玩了一次战争题材的角色扮演游戏。
====

|▶ 服装还能提供"潜台词"含义.
|
[.my1]
.案例
====
<The Seven Year Itch> 中的玛丽莲· 梦露虽然穿着一条白色系颈裙，可是她的角色真的像这条裙子一样纯洁吗？
====

|===



'''

==== 灯光 : 能富有"情绪"和"自我表达性"。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 最基本的要求是: *演员身上的打光要增强、凸显演员身上的特质。*
|灯光刺眼还是柔和？是为演员增色，还是暴露出他身上的每一条皱纹和伤疤？ +
犯罪惊悚片, 也探索了类似的舞台剧式打光，来表现角色恐慌不安的内心世界。

[.my1]
.案例
====
<The Godfather‎ 教父>喜欢在阴影中拍摄演员。开场中，唐·柯里昂坐在一个灯光昏暗的书房，而他女儿的婚礼却是在户外阳光灿烂的花园中举行，两个场景展现出柯里昂分化的内心世界，一边是肮脏的犯罪生意，一边是对家人的关心爱护。
====

低光摄影应该遵循这样的标准：**隐藏起来的视觉信息, 要能进一步将观众吸引到叙事当中，**而不是迫使他们吃力挖掘。
|===



'''


== 演员表演的好坏, 如何判断?

==== 一千个读者心中有一千个阿姆雷特

评价演员和表演好坏, 是一件很"个人审美, 喜好"的事情 (一千个读者心中有一千个阿姆雷特. 文无第一武无第二.)

'''

==== 判断时, 要把这个演员可控的地方, 和不可控的地方区分开来。

在评价一个你不喜欢的演员的表演时，必须把这个演员可控的地方, 和不可控的地方区分开来。*观众应该问自己的问题，不是演员本人是否有吸引力，而是演员扮演的这个角色, 是否具有"真实度"?* +
任何人都应该降低对其不喜欢的演员抱有恶意。*毕竟这些演员把自己的内在和外在生活都赤裸裸地展示出来，任凭我们欣赏或是嘲笑，这样的勇气值得我们钦佩。*(对搞文艺的, 设计师也是一样. 当然, 郭德纲也说过, *你赚钱的里面有一半是用于挨骂的,* 即别人为了骂你而付你钱)


'''

== 电影一定要尽量多给观众一点儿信息，用画面和信息淹没他们。如此一来，一部电影便可以重复欣赏，影迷每次重看都会有新的发现。

除了演员，艺术设计的**所有重要细节, 都要让肉眼轻松捕捉，让观众能够获取他们需要的信息和情报，** 其中包括自然背景、人造环境、道具、服装，以及能够传达故事背景及潜台词的各种细节。 +
虽然有时候, 细节并不一定要被观众注意到，但是**如果好不容易精心挑选出了一屋子的装饰品，最后都隐藏在阴沉昏暗的灯光之中，那又何必费这个心呢？**


'''
