
= (术) 如何塑造,树立起角色
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

.表演上
[%collapsible%close]
====

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 研究人物
|好的演员, 要做的第一件事就是分析角色，拆解每个角色的对白和行为，理解角色说的每一句话、做的每一件事（或者不做的事情）背后的含义。(正如郭德纲所说: 说三国, 发生了什么事情不重要, 重要的是分析人物背后的心理和动机, 这些底层原因, 才是导致各种表层事件发生的源泉. )

|▶ 真实, 才会令人相信, 进而引发情感
|*衡量一个演员表演的好坏，是看观众是否获得情感共鸣*：演员的表演, 是帮助了我们进入银幕中的世界，还是让我们觉得出戏？ +
一部电影一定要让观众觉得可信，细到每一个词、每一个眼神、每一个领带夹、每一个茶杯，*都要"真实可信"。只有这样, 才能激发出他们的情感, 而不会因为"太假"而引不出真情.*

- 很多灾难特效大片, 打动不了观众, 就是因为它们都只是呈现灾难和奇观的载具. 这些电影只有剧情，没有故事；只有角色，没有人；只有刺激，没有感情。总而言之，没有可信度。
- 最忌讳被观众发现表演痕迹的类型片，可能是喜剧片。很多演员都会告诉你，演喜剧的时候，千万不能一心想着逗人发笑。*如果观众感受到演员是在故意演给他们看, 他们就会出戏.*

|▶ 要表演, 不要模仿
|演员要演出角色的心理状态. **你不是在演一个混蛋，而是要把你内心的那个混蛋展示出来。因为"模仿"并不属于"角色刻画"，**不会**揣摩角色的心理活动，**也不会**为他们塑造一个完整的内心世界。**这样就无法打造一个活生生的人、一个能透过屏幕与观众达成情感连接的人.

- 一个演员要在电影中模仿尼克松, 轻而易举, 但如果只做到这一点, 那他在艺术性上绝不会比 <The Tonight Show 今夜秀> 中 Rich Little 的"尼克松模仿秀"高明到哪里去。

浮夸的说话风格和装模作样的动作，让他看上去更像是个搞笑演员在模仿，而不是在呈现一个真实角色。

尽力保持克制，不到万不得已时千万不要哭，不要喊，更不要浮夸。否则，演员呈现的只有"情感主义"（emotionalism），而没有"情感"。电影并不需要演员像演话剧那样, 抑扬顿挫地讲话，或者动作举止夸张激烈。要让情绪自然流露。 +
要想演活一个角色，意味着你的走路、说话、思考、生活方式, 都要和角色一致。你可以留心演员在不说话时，脸上是否会失去一些神采；或者当另一位演员在说话时，他能否像注意自己的台词一样, 注意对方的台词。(即对”角色身份”的投入性, 是否能一直在保持延续中?)

|▶ 细节 : 能突出人物性格
|细到“这个角色是会把衬衫的纽扣全都扣上，还是会解开四个纽扣或六个纽扣？*因为所有这些特征, 会告诉剧中的其他角色, 这是一个怎样的人?”。*

.眼睛是不会撒谎的
电影是一个“看脸”的世界，它是一个被特写主宰的媒介。*很多时候，成就一段精彩表演的，只是演员最简单的、最直接的一个眼神。*

- <The Silence of the Lambs 沉默的羔羊>中的 由 Anthony Hopkins 演的 Hannibal Lecte ) 他把这个角色想象成一只介于猫和蜥蜴之间的生物：“他是一个不会眨眼的人，他可以好几个小时一动不动，就好像一只狩猎的螳螂, 观察着，然后再展开行动。”


|▶ 演员本人的魅力气质, 是否与角色相符
|电影明星, 历来和他们参演的电影, 有一种矛盾关系: 明星的名气能拉来投资, 但明星也要放下架子服务于角色本身, 而**导演在这个过程又不能破坏明星的魅力，否则就失去了邀请大明星参演的意义。**

- <Hyde Park on Hudson> 讲的是罗斯福总统和一个远房亲戚的婚外情，话题较敏感，唯有 Bill Murray (<迷失东京>男主) 能驾驭这个角色。因为他身上有种特性，能让你对他的错误既往不咎。
- <The Hurt Locker 拆弹部队> 中最大牌的演员 Guy Pearce 在第一场戏中就遇难身亡. 当 Jeremy Renner (复联的"鹰眼") 出现并取代 Guy Pearce 的角色成为上士时，观众对于 Jeremy Renner 的陌生感, 会让这个角色的命运多了一份不确定性。如果你把这两个演员的角色对调, 你就会知道要在《The Hurt Locker》中营造不确定性和强烈的临场感，正确的选角有多么重要。
|===

'''
====

.镜头: 摄影机的机位选择, 对观众有心理暗示作用。
[%collapsible%close]
====
基本上， 电影语法就是建立在三种镜头之上： 远景（ long shot）、中景（medium shot）和特写（close-up）。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|远景也叫“全景”（wide shot）(*反映角色身处的"环境"*):
|全景镜头视野非常广阔。*如果全景镜头中有人，那么人物通常是处于次要位置，镜头中的自然环境或者人造环境, 才是主角。* +
因为远景镜头能够传达很多关于时间与地点的信息，所以它们通常都是用来作定场镜头.

|中景镜头(*反映角色的"行为, 动作"*):
|展现的是角色如何移动，如何和其他人接触、交流。 +
用中景镜头拍摄时，你可以看到角色腰部以上的画面（不要将"中景镜头"和"中特写镜头"混淆，中特写镜头拍的是人物胸部以上的画面）。 +
*中景镜头通过角色的行为, 能让观众对角色产生同情或者疏离的情绪*。

|特写(*反映角色的"内心心理,情感"*):
|就是将镜头放在距离人物面部. +
*特写成了一种极富心理暗示的电影语言，通常用来直白地，甚至令人不适地展现角色的脆弱与瑕疵。*

|▶ 摄影机放在哪里？它为什么在那里？如果摄影机在移动，它移动的原因是什么？
|- *摄影机的位置如何移动, 能增强某个场景的情感冲击力？*
- *镜头运动, 是如何营造活力感、宏伟感、历史感和紧张感的?*

对于每一个行为或问题, 你都要去思考其背后的原因及答案, 这才能使你成为"谋事者".
|===

'''
====

.服装 : 能帮助展现角色的性格
[%collapsible%close]
====

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 是演员穿着衣服，还是衣服“穿着”演员？
|服装不仅能体现一个角色的阶层地位、家庭背景，甚至宗教和性取向，还能传达角色隐秘的欲望和追求的形象。服装应该“能表现角色的灵魂”。

- Pearl Harbor 珍珠港中的演员造型更带着一股明星写真的味道，Ben Affleck 和一众影星根本不像是在拍战争片，倒像是砸重金玩了一次战争题材的角色扮演游戏。


|▶ 服装还能提供"潜台词"含义.
|- <The Seven Year Itch> 中的玛丽莲· 梦露虽然穿着一条白色系颈裙，可是她的角色真的像这条裙子一样纯洁吗？
|===


'''
====

.灯光 : 能富有"情绪"和"自我表达性"。
[%collapsible%close]
====

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 最基本的要求是: *演员身上的打光要增强、凸显演员身上的特质。*
|灯光刺眼还是柔和？是为演员增色，还是暴露出他身上的每一条皱纹和伤疤？ +
犯罪惊悚片, 也探索了类似的舞台剧式打光，来表现角色恐慌不安的内心世界。

- <The Godfather‎ 教父>喜欢在阴影中拍摄演员。开场中，唐·柯里昂坐在一个灯光昏暗的书房，而他女儿的婚礼却是在户外阳光灿烂的花园中举行，两个场景展现出柯里昂分化的内心世界，一边是肮脏的犯罪生意，一边是对家人的关心爱护。

低光摄影应该遵循这样的标准：**隐藏起来的视觉信息, 要能进一步将观众吸引到叙事当中，**而不是迫使他们吃力挖掘。
|===


'''
====



