
= 做事
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

做事 (是"获得你的影响力", 或"展现你的影响力"的必经方式)


.*权力与责任必须对等*
[%collapsible%close]
====
- 消费者购买某产品, 必定要通过"用户之旅"的全过程. 所以不能让负责最前端内容推广的公关人, 直接承诺最后一个环节的销售成果.

'''
====

.做事不要怕! 你的态度应该是从"自我沉浸" 改为"自我抽离"
[%collapsible%close]
====
- 做事不要怕! 正确的做法是什么呢? 从"自我沉浸" 改为"自我抽离"(就像演员演戏一样). 不要把自己代入, 而是站在第三方角度, 来考虑你担心中会遇到的问题:

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|原因
|造成这些问题的原因是什么？包括表面原因, 和深层原因.  +
其中有哪些是由于我行动不当所导致的？有哪些是我无法控制、无法决定的？

|结果
|如果换了别人，他是否会跟我碰到一样的问题，会做得比我更好吗？

|带来的影响
|这个问题有哪些可能的结果？它们发生的可能性有多高？对我有多大的实质影响？ +
其实很多无论为何种结果，对你都没有实质性的影响。
|===

- 我经常劝年轻人，不要害怕，你的上级把任务交给你的时候，预期就是你会搞砸。你为什么觉得他会把一个绝对不能搞砸的事情, 交给你呢?

'''
====

."有用"比"绝对为真"更重要.
[%collapsible%close]
====
- **科学界一般公认，没有任何一种理论百分之百绝对正确。判断它真正价值的, 是它的实用性 (比如量子力学理论)。**即 : 对“某知识”的价值评判, 不在于其在哲学上是否绝对为真实，而在于它是否能让人得到力量。(即, 别本末倒置. “判断为真”只是手段, 不要把手段当目的.)

'''
====

.只要是人制定的、做出来的，就一定是有漏洞的（不完善的）
[%collapsible%close]
====
- 事情是人做出来的, 规则是人定出来的, 只要是人制定的、做出来的，就一定是有漏洞的（不完善的）、需要改进的, 创新的。(否则, 人类社会中的一切就不会再发展.)
- 重要的是，这些路不是用来局限住你的，而只意味着提供你一些选择的途径. *没有创新精神的人, 永远也只能是一个执行者。*
- “理在事中”，能成事就是有理。世事往往是“以迂为直”。如果两点之间的直线阻力却最大，那么这根直线，其实是最远的路径。
- 在“我是对的”和“有效果”之间，你必须做一个选择。你认为的好坏，和你的婚姻关系相比较，哪个更重要？

- *所有伟大的真理开始都离经叛道。权威的思想将它的某些力量赋予敢于向它挑战的人。没有创新精神的人永远也只能是一个执行者。* (就像郭德纲说的: 唱戏, 到七老八十了还亦步亦趋前人的做法? 你不可能永远是一个学徒!)

- 向那些疯狂的家伙们致敬，他们特立独行，他们桀骜不驯，他们惹事生非，他们格格不入，*他们用与众不同的眼光看待事物，他们不喜欢墨守成规，他们也不愿安于现状。你可以赞美他们，引用他们，反对他们，质疑他们，颂扬或是诋毁他们，但唯独不能漠视他们。因为他们改变了事物。*  — 乔布斯

'''
====

.路径依赖, 是没有目标的表现
[%collapsible%close]
====
- "因为以前这样做，所以现在也这样做..." 这个思考是错的。这样的路径不是根据目标来的，是**根据以往习惯来的(即路径依赖)，这是没有目标的表现。 (必须倒过来想, 以终为始. )**

- 对用户来说，他关心的是速度, 比如"扫描速度从20秒提升到10秒". 这个目标实现了，留存率自然就上来了。而不是公司一开始就把目标设计成"留存率"或用户"使用次数"，因为这只是"公司角度"的目标和需要, 而不是"用户"的目标和需要. 所以一定要站在用户的角度来考虑问题. 在“速度”这个目标下, 又能分解出很多个子目标.


'''
====






