
= 科学, 科学研究方法
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


.现代科学, 与先前的知识体系, 有三大不同之处:
[%collapsible%close]
====

1. 愿意承认自己的无知。**现代科学的基础就是拉丁文前缀“ignoramus-”，意为“我们不知道”。**我们承认了自己并非无所不知。 更重要的是，我们也愿意在知识进展之后，承认过去相信的可能是错的。*于是，再也没有什么概念、想法或理论是神圣不可挑战的。*
2. 以观察和数学为中心。现代科学如何获得新知? 通过收集各种观察值，再用数学, 逻辑，形成理论。
3. 取得新能力。光是创造理论，对现代科学来说还不够。它希望能够运用这些理论来取得新的能力，特别是发展出新的科技。

对于像是伊斯兰教、基督教、佛教、儒教这些前现代知识体系来说，它们假设世上所有重要的事情都已经为人（某些过去的智者）或为神所知。通过经典或口传，将这些智慧传给后人。而对于平民百姓而言，重点就是要钻研这些古籍和传统。 在当时，如果说《圣经》、《古兰经》或《吠陀经》居然漏了某些宇宙的重大秘密，而这个秘密又居然能被一般血肉之躯的人给发现，这简直是不可思议的事。

- *科学研究并不承认权威，而只承认可重复的、能被独立验证的证据。所有所谓的"信仰"(其实就是理论幻想, 猜想. 世上没有神!) 都必须能够接受质疑。* 所以科学不是另一种宗教. *宗教会维护权威; 而科学是喜欢自我革命, 打倒权威.*
- 在著名学术期刊上发表论文, 不等于成果就已经获得了承认，是不是真实可靠的, 还要看能否被别人重复出来。

'''
====


.日本对历史的研究, 随着日本自身现代化(科学化)了.
[%collapsible%close]
====
- 晚清史在1912年以后, 也仍没有得到充分客观的阐释。简言之,*日本对历史的研究编纂, 随着日本自身现代化(科学化)了.* 而在中国, 对历史的编撰, 仍然遵循着传统(缺乏科学)的方式.

'''
====





.相关关系 ≠ 因果关系
[%collapsible%close]
====
统计学教科书里教的第一件事就是: "相关关系"不是"因果关系"! +
*相关关系: 是指一个变量(var 1)变化的同时，另一个变量(var 2)也会随之发生变化，但不能确定var 1 变化是不是 var 2 变化的原因。*

image:../img/0042.svg[,]


- "大数据分析"可以在完全不考虑"因果关系"的情况下，通过数据点的"相关性"和其他规律，精准地给出对下一个购买行为的预测分析。商家不必纠结“因果”，仅用"相关关系", 就可预测大部分市场营销的需求。 (就好像你不需要知道量子物理学的具体原理，只需要知道它是有效的, 就能直接使用它.)

- 美国零售大户Target, 曾经利用消费者购买数据, 判断女性消费者的怀孕状态，并通过推送婴儿用品广告等方式, 进行精准市场营销。— 如果发现女性消费者突然改变自己的消费习惯, 并开始新的消费行为，如购买无香的身体乳液，购买一系列如钙、镁和碘等维生素，购买育儿图书或杂志，或者注册了孩子的礼物名单等，商家内部客户管理系统（CRM）就会提升所谓“怀孕预测指数”。一旦指数达到设定标准，公司就会为此类消费者打上标签，并向这类消费者按不同孕期阶段, 进行促销，一次推送多达20多种孕期产品的介绍或样品。


- 虽然"相关关系" 给我们提供了很多增加收益的方法。但成也萧何败萧何 : *"相关关系"也是相对不稳定的, 易变的. (因为你还是不知道背后真正起作用的变量(即真正的因果关系)是哪个)*

'''
====

.真正的"因果关系" 该如何验证? 需要以下4种可能性矩阵来收集数据:
[%collapsible%close]
====
最简单的"因果关系"验证实验, 需要以下4种可能性矩阵来收集数据:

[.small]
[options="autowidth" cols="1a,1a,1a"]
|===
|Header 1 |待证实的”结果”, 出现|待证实的”结果”, 未出现

|待证实的”原因”, 出现
|a 数量
|b 数量

|待证实的”原因”,未出现
|c 数量
|d 数量
|===

即: 只有在严格控制其他因素，去掉混淆变量，并在我们得到这四种数据下: +
原因出现，结果出现（a个案例）； +
原因出现，结果未出现（b个案例）； +
原因未出现，结果出现（c个案例）； +
原因未出现，结果未出现（d个案例）。

我们才能用以下的数学公式, 来验证"因果关系"是否真的成立: +
latexmath:[ \varDelta P =\dfrac{a}{a+b} - \dfrac{c}{c+d} ]

即: +
→ 如果ΔP的值是零，则完全无相关性； +
→ 如果ΔP的值是正数，则值越大（总实验次数为上限），因果关系越强； +
→ 如果ΔP的值是负值，则说明, 此"原因"有"抑制结果产生"的功效。

- 假设我们做了200次实验，其中100次有原因出现，这时有80次出现了期待的结果，20次没有出现。另外100次实验没有这种原因出现，有80次出现了期待的结果，20次没有出现。 +
现在套用公式： +
latexmath:[\varDelta P =\dfrac{a}{a+b} - \dfrac{c}{c+d} = \dfrac{80}{80+20} - \dfrac{80}{80+20} =0 ] +
在200个实验基数上，ΔP=0, 说明这两个变量(待验证的原因, 和待验证的结果)之间, 并无真正的因果关系。

'''
====

.循环论证（Petitio Principii 或Begging the Question）
[%collapsible%close]
====
循环论证, 就是用问题的假设前提, 来回答问题本身，而没有给出真正的原因。

- 如 : 为什么超人能飞起来？因为他是超人啊！为什么他是超人呢？因为他能飞啊.  ← 论据只不过是在重复之前所做的假设，而完全没有提供支持的论点。

'''
====






