
= 吴军 - 脉络
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


我只偶尔在很小范围的朋友圈子中, 分享我对一些问题的看法，仅限于此。在大众面前，对于比较残酷的事实，我是不讲的. 根据我的经验，世界上自以为是的人, 要远比虚怀若谷的人多得多。所以这么多年我不断告诫自己，*#不要自讨没趣 (不要去和网上的人打嘴仗)#*。

*一个觉得历史是少数英雄创造的人，在现实中会屈服于权威.*

唱赞歌，不是作家的任务；发现问题，特别是深层次的问题，才是作家的责任。**只有**了解人类幼稚, 自私之处，**了解人性的弱点，**包括我们自身的弱点，*才能对社会有一个公允的看法.*

乔治·奥威尔说，谁控制了过去，谁就控制了未来。

历史故事, 要比现实中的故事，好听得多，因为不好听的历史故事都被过滤掉了，或者被人们遗忘了.

没有正确目标的辛劳，只会陷入越忙越穷、越穷越忙的陷阱。后来我担任了职权不低的管理者，才认识到, **"授权"常常比"亲力亲为"要好得多。**特别是在做投资之后，我更深刻地体会到，"少操作"是获得高回报的关键. 因此，今天我不断和大家讲，*要做减法.* 很多人的问题不是做事太少，而是做事太多。


现实教育我，历史书中的建议，或者古代圣贤的箴言, 不可太当真。 *“闻过则喜”这个典故, 我发现自己很难做到，身边的人我就几乎没见到过谁是这样的，倒是一句“伸手不打笑脸人”说得十分准确。("不符合人性"的宣传和要求, 都是谎言. 哪怕它说的冠冕堂皇, 如当官是“为人民服务”之类. 事实上, 当官首先是为了能获得自己的利益!)*

由于一些天生的弱点，人即使知道什么是对的，也不会去做。(人性弱点,食色性也)



史家们总结出来所谓历史规律，大多是根据结果倒推原因的。但比如古典文明（即罗马帝国和秦汉帝国）的终结, 很多是由客观原因造成的，包括气候、人类迁徙、文明自身的脆弱性、政治制度自身的问题等，这些因素不是任何人可以逆转的(非人力可为)。 +
其实，一个人有为、无为，抑或有害，常常是后人根据结果给他贴的标签 (即是"以结果论英雄", 即"成王败寇"的评判思想)。很多事，在当时的环境下，换个人可能也会不得不这么做。


如果一个人对于现实的看法, 得不到"历史数据"的验证，那他这种结论可能是错的。但反过来，在历史上被验证的经验，在现实中却未必管用。投**资界常说的一句话：#过去的表现, 不代表未来的表现，但是过去表现不好的投资人或者基金，未来几乎也都做不好。#** (一切只是概率,而非必然性.)  +
(所以必须要有证明自己的事件,才能打破惯性, 在他人对你的感觉中,才会令他们的思维倾向转变原来的方向惯性（思维定势）. 即, 你不是原来的你了. )

人类在大约一万年的文明史上，只发生了两件最有意义的事: 1.农业革命, 2.工业革命.

有一些人，虽然位高权重，但其实是文明的破坏者，而不是创造者。

人类从历史中学到的唯一教训，就是"人类无法从历史中学到任何教训"。

孔子讲：“危邦不入，乱邦不居”, 同样, 不应该到施行暴政的国家做官，或者在可预见的末代王朝做官，而应该首先保全自己。 (不过也有点事后诸葛亮,你怎么知道他朝代一定会灭亡)

在古典文明结束之后，中亚以西世界的历史几乎就是宗教史, 甚至延续到今天.

整个西方金融史，就是一次次金融危机、一次次股灾和崩盘的历史。同时也是人类吸取教训，并且在制度进行不断改进的历史.

历史中, 很多规律很难总结，即使总结出一些所谓的规律，在后来条件稍微有所
改变后，也变得没有太多的参考意义。因为**统计学中有这样一个常识: 即使##统计一下"一件事发生或者不发生的概率"，也要几百个样本, 才能得到具有95%以上置信度的结论。##但是绝大部分历史事件, 不可能出现那么多次，甚至很多只出现一次。**这样得到的所谓的规律, 更多只是巧合而已。

**#给看到的现象, 找一个逻辑上能够自洽的解释, 是一件很容易的事情，但是这种解释, 通常不是造成结果的原因. 而找到"真正原因"和"结果"之间的逻辑关系，是很难的。#**对于受到很多因素影响的历史问题，总结规律就更难了 (变量太多,很难构建因果模型)。因此，今天绝大部分做事成功的人，更倾向于用"当下得到的信息"，而不是"历史上发生的事情", 来指导行动，因为今天不可能完全重复历史(现在的各种变量, 完全不可能和历史都相同)。

研究历史的因果关系不容易, 研究当代问题就更是如此. 因为现实的结果还看不到.


汉武帝做了什么对历史发展有帮助的事?很少。 汉武帝花了无数的钱，消耗了汉初几代皇帝轻徭薄赋的累积. 死了无数的人，只是取得了对匈奴战争阶段性的胜利. 司马光说：“孝武穷奢极欲，繁刑重敛，内侈宫室，外事四夷，信惑神怪，巡游无度，使百姓疲敝，起为盗贼，其所以异于秦始皇者无几矣。”在司马光看来，汉武帝就是个亡国之君，本来他的结局是和秦始皇差不多的。好在他的儿子汉昭帝不是秦二世，辅政大臣霍光也不是赵高，才免于人亡国。

汉武帝临终前也意识到自己的问题，下了中国历史上第一个罪己诏——《轮台诏》。

汉武帝的儿子汉昭帝, 和其曾孙汉宣帝，他们改变了汉武帝几乎所有的经济政策，与民生息，这才让汉帝国得以保全。昭、宣二帝在历史上没有什么名气，今人重新评价他们，称他们的统治时期为“昭宣中兴”，那是今天的事情.


拿破仑的功劳, 主要在于他领导编纂了《拿破仑法典》，并且把平等、自由的思想带到欧洲. 至于他的几十场战役的胜利，其实对法国和欧洲的格局没有什么影响。

而真正奠定法国大国地位的, 是路易十三的枢机主教"黎塞留"(外交手段), 和他的继任者"马萨林" (和欧洲各国签署了《威斯特伐利亚和约》，才确定了法国今天的疆域). +
对法国贡献极大的第三个人, 是被拿破仑称为阴谋家的"塔列朗"，他在法国输掉了拿破仑战争之后，通过他的外交手段，维持了法国作为一个大国的体面, 以及法国在《威斯特伐利亚和约》中获得的疆域。


几何学的出现，让人类能够从基本的假设出发，通过理性, 推导出新的知识.

很多人喜欢比较文明的长度，这种比较其实意义没那么大. 而且我们今天的生活, 和绝大多数古代文明没有直接关系。

一个文明曾经控制的疆域和人口数量，和文明的贡献也并不成比例关系。

古埃及文明, 和今天没有太多的直接关系:

- 古埃及人编纂了人类最古老的几何学著作, 但是今天公理化的几何学, 并不源自于此。
- 建造金字塔的技术, 对后来世界上的建筑也没有多大帮助。
- 古埃及的防腐技术。不过，根据今天对古埃及各种防腐药方的分析，发现里面没有多少有效成分。


南亚次大陆最早的文明，即印度河文明，与后来的古印度文明几乎没有关系，和今天的印度更没有关系。

古印度文明, 是南下的雅利安人建立的"吠陀文明". 吠陀文明影响到南亚、东南亚后来的文化，但是对
于今天那里的文明进步影响极其微小，其中最大的影响是"种姓制度"。


今天全世界所有文明
真正的起点, 其实是我们前面提到的轴心时代文明，也就是从公元前8世纪到公元前3世纪发
生在整个欧亚大陆的思想革命。换句话说，虽然人类的文明史有6000年，但是对今天真正
有影响的时间不到3000年。

秦始皇统一了中国, 但没有秦，也会有其他诸侯国统一中国。因此，这些人、这些事了解得多一点或少一点, 对我们并不重要. 我们真正该了解的, 应该是那些对人类文明有"转折点"的事.

人类文明史上, 有些人或事的作用, 被高估夸大, 有些则被低估.

孔子的思想, 时而被奉为圣人，时而被打倒，但这都不重要. 他的思想无论好坏, 至今还影响到现在的人, 则是不争的事实。 +
美国有过一个"世界有影响力的历史人物排行榜", 前几位是(排名不分先后):
- 牛顿, 哥伦布, 蔡伦(造纸术), 古登堡(印刷术) +
- 耶稣, 使徒保罗(基督教会的实际建立者) +
- 穆罕默德,  +
- 释迦牟尼,  +
- 孔子.


历史学家和经济学家, 通常使用两个标准, 来衡量经济和社会发展水平:

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.人均GDP
|

|2.获取能量的总量和利用水平
|任何一个物种, 要想实现繁衍，就必须: 获取的能量 > 消耗的能量. +
如果想要发展，就必须: 获取的能量 = n倍"消耗的能量"。
|===


人类是在什么时候获得平等权利的呢？基本上是在工业革命之后。

启蒙运动只是提出了一个想法，但当时还不具备实现的条件。

法国大革命打破了血统论，让公民和教士、贵族在法律上做到了平等，但是由于当时法国还没有开始工业革命，贫富差距依然明显.






35