
= 政治中,历史的规律
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 核心思想

.用政治意识形态来教历史, 就是伪史
[%collapsible%open]
====
- 中国在历史教育上的问题 : *学校里的课, 名义上讲的是历史，实际上却不是在搞真正的历史研究，而是按政治课的性质开的. 其目的是想给学生灌输一种特定的意识形态.* 因此, 从"是非"和"真伪"角度来看，这样的历史就是伪史.

'''
====



== 帝制时代

.★ 王朝统治的衰败规律
[%collapsible%open]
====
[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1."明规则"阶段
|当新的王朝发展到一定时期，制度(明规则)就会开始懈怠. 该遵守的规则失去落实，该处理的政务没有人干。

|2.逐渐的，"潜规则"开始当家.
|其实有较为固定的"潜规则"，也能维持运转，大家实践几次也就都知道该怎样办事了。

|3."无规则"阶段
|再后来，潜规则也不管用了，它又被"无规则"取代。但等到"潜规则"都被破坏了，这个时候就会产生混乱，人们对该怎么办事就没有共同预期了。

|===


'''
====


== 清末

.晚清历史的本质, 就是西方把中国拖入世界体系的过程。
[%collapsible%open]
====
中国近代史的本质, 就是西方迫使清朝接受西方有关"国际贸易"和"国际关系"的概念. +
晚清历史的本质, 就是西方把中国拖入世界体系的过程。中国传统是"朝贡体系". 朝贡体系就是国与国不平等关系.  如果我们不知道近代中国是怎样融入世界体系的，或者完全无视这个过程，结果就只会有人重新闭关锁国, 鼓噪排外。


'''
====

.为什么称为"不平等条约"?
[%collapsible%open]
====
为什么西方和清朝签订的条约, 是把中国带入了现代世界和开明进步, 却还被称作”不平等条约”? *因为条约主要是中国出让了一些主权, 所以它们就被称为"不平等的".*

'''
====

.中西方法律差距的背后, 实际上隐含着对个人”权利”和”义务"的两种截然相反的看法价值观.
[%collapsible%open]
====
西方人对中国落后的司法(随意逮捕, 折磨被告)不满, 因此执行"治外法权"制度 (由外国司法机构, 来审理外国国民). **中西方法律差距的背后, 实际上隐含着对"个人权利和义务"的两种截然相反的看法价值观.**  +
**司法要改革，**如同在日本的一样, *被外国列强认为是废除在华"治外法权"的必要前提。*

'''
====

.最惠国条款, 继续将任何一个条约国所取得的所有特权, 给予每一个条约国。
[%collapsible%open]
====
始自19世纪40年代的这一体系 (最惠国条款), 在20世纪最终发展为: 大概控制包括约90个通商口岸和开放港口、约25个(轮船) 停靠港, 和约30多万外国侨民的体系。在通商口岸城市中, 西方人引进了西方都市化的市政设施 — 报纸、学校、图书馆, 医院、供水排水系统、铺石道路, 和照明系统。还有西方的更高的生活标准。

'''
====



.下一代的新式教育下的学生阶层, 很快就会开始成为社会的领导者.
[%collapsible%open]
====
教育体制和教育内容不改，就培养不出新思想下的下一代, 社会就缺乏”宪法文化”, 宪制的发展就缺乏发动机. 因为**下一代的新式教育下的学生阶层, 很快就会开始成为社会的领导者.**

洋务运动从整体上来说，还只是停留在少数开明官员的实践中，还没有成为整个社会的士大夫的集体自觉行为。因为科举还没有变. *科举不变，整个社会的评价体系就不会变, 士风也很难发生改变.* 士大夫的思想仍然活在中世纪，在儒家建构起的"天下秩序"里思考现实。 +
所以**没有用西式教育培养全新思想的人, 这就导致洋务运动的后续, 中坚人才长期匮乏 (没有接班人)。 导致整个洋务运动只是"变物, 没变思想和制度".**

为了同时利用儒学来支持变法思想, 康有为决定改造儒学、改造孔子, 将孔子打扮成一个支持变法的革新者. **最好的方式是找到原始儒学，然后直接往里面加东西，因为原始儒学写的很模糊(所谓微言大义), 本来就具有较大的解读开放性，可以添设许多新的理论思想**，靠这种方法来支持变法是可以的 (变"他驱"为"自驱")。

对于变法来说，启蒙只是一个方面，而文化的改造一直会是个难题。

'''
====

.外因里,有"益处"也有"弊处". 同样, 内因里也是既有"益处"也有"弊处". 所以不能把所有的"弊处"都归于"外因".
[%collapsible%open]
====
传统解释认为, 中国现代化过程的缓慢, 主要是因为(外因)西方“帝国主义"压迫的有害影响。但这种观点无法解释为什么势不可当的“帝国主义"影响, 在日本和中国却产生了如此不同的结果 (日本在"西方文明的外因"和"自身文化的内因"下, 通过明治维新, 逐渐进入了民主国家行列)。 +
事实上, (内因)儒家文化的某些特征, 阻碍了中国的变革. (中国的历史向来没有宪法文化, 没有宪政文化的土壤, 就很难实现”宪政果实的最终结出”. 因为文化就是发动机, 就是惯性.)

'''
====

.★ 关于清末新政, 凡是都一定要踏出开头第一步,才会有第二步. 不能因为第一步做的不够好, 就直接否定掉它. 否则就会犯“倒果为因”的认知错误.
[%collapsible%open]
====
我们至今在评述革命时，总是从正面对其进行评价, **我们惯常的逻辑总是误以为, 肯定是前代王朝事情做的不好，所以才导致了革命。但这种解释, 很多推论都是”倒果为因”.** 事实上, 清末新政还算搞得不错.

新政时, 朝廷中的官制改革、司法改革，废除科举，都在有序地进行。民营工业的增加, 国家财政好转, 吏治逐渐变好. 预备立宪以后，这方面的表现就更明显了。在新政期间，地方的自治团体确实也成了国家法律上承认的合法机构，不像以前，官方可以无视这些民意代表的意见.

**有些人批评说这些都是假的，清政府搞的不是真民主。但任何事情总是要有个起点，从这个起点坚持走下去，只要大方向不错，一般都会走到真民主的状态。(如台湾)**

有人批评当时的选举有财产限制，说朝廷对”选举人”和”被选举人”都设有很高的财产门槛，但你不能据此就说那是假民主。在那个时代，几乎所有国家的选举都有限制，都有财产和纳税的限制，而且妇女都没有选举权。若是以”普选”为标准来衡量当时的民主的话，直到二十世纪30年代以前，世界上都没有民主国家——一个国家一半的人口都没有选举权，那凭什么说它是民主国家啊。道理不能这么讲，清朝搞新政，本身就含有推进民主的意义。**民主的实现, 是一个逐渐完善的过程. 但首先它得有开端.**

1908年，光绪和西太后都死了, 让溥仪继位，溥仪的爹载沣为摄政王. 载沣开始收权, 开新政的倒车.

'''
====

.中国以往历史教育中的"革命线索" —— 强调从太平天国、义和团, 然后到辛亥革命. 这很容易使我们忽略历史的多线性.
[%collapsible%open]
====
今天我们关于戊戌变法的历史叙事，其实在很大程度上是沿袭了康梁对变法的描绘和记述。所以我们一提到戊戌维新，首先联想到的可能就是康梁主导下的变法. 但其实在当时，有许多人都在变法。所以，戊戌变法在当时是存在多个中心、多条路径的。

'''
====



== 北洋时代

.会党对历史的作用被长期夸大和高估了。因为**在中国，任何事情一旦发迹，就会有人给其写东西、编历史。**
[%collapsible%open]
====
现在关于会党的研究很多，最大的问题在于，**会党对历史的作用被长期夸大和高估了。因为在中国，任何事情一旦发迹，就会有人给其写东西、编历史。** +
编历史的会这样说，这些组织从一开始就是抱着反清复明这样的远大宗旨的. 其实帮会人士只是希望抵抗清政府对他们的敌视和压制。**至于反清复明什么的，都是后来人加上去的一些由头。** +
包括会党的历史，以及他们跟少林寺、南少林寺的关系，都是编的。其实少林寺和南少林寺的历史本身也是编的。民众就是需要一些神话，如果太真实了，就缺少吸引人的地方了。

革命党搞的起义，只要是有会党参与的，一般都没什么戏。因为兴中会钱多，所以总是用钱去收买土匪或者三合会去发动起义。一旦钱没了, 大家就都散了。 +
如果革命党笼络的会党稍微多一点，他们可能就会自己先掐起来，因为他们从来都不是一个团体. 帮会并没有真正的谱系，这些谱系什么的都是后来建的。洪门，尤其是青帮，都是组织完善以后, 自己建起的谱系发展脉络(就跟建家谱一样)。*什么辈分啊，排序啊，都是后来人弄出的名堂.* 最初就是一盘散沙，山头林立。

而这些帮会又自认为是革命党。很多地方的帮会都没怎么打过仗，但他们都自认为是革命元勋。**这些混吃混喝的人就这么起来了，虽然无甚功劳，但已经成为革命元勋了，就要分享革命成果。**所以帮会开始各占一摊，进了城之后秩序大乱，他们觉得轮到帮会来坐天下，他们该做皇帝了，就为所欲为，比如公开地包娼包赌，公然地在大街上抢劫。 +
*所以到了后来，跟帮会沾边的革命党人都遭到了排挤.* 比如湖南的焦达峰、陈作新先后被杀，显然是跟他们的帮会背景有关系。当时的帮会太猖狂了，焦达峰在都督府里每天都要摆流水席，天天接待各种江湖人士。**这些人来了，不仅要吃饭，还要封官，还要给钱，**湖南在新政期间攒了几百万两的银子，都让这帮人花光了，而且之后整个长沙城秩序还是一直混乱。

*在当时，革命党若是不镇压帮会，就根本处理不了混乱的局势。如果革命党想赢得民众的支持，塑造合法性，就必须镇压昔日的盟友。*

就孙中山的个人想法而言，他未必想真正地动员帮会，他做的只是对他们进行收买和利用. 在同盟会中，孙中山是最大的金主，**因为两广人士中的海外华侨比较多，**所以能从海外筹到钱的只有孙中山，他可以收买大批帮会参与起事。**而江浙和两湖地区出外谋生的海外华侨, 则少很多，**所以光复会以及两湖的革命党没法从海外筹钱，只能依靠当地的富人捐一点钱。没钱怎么动员帮会呢？只有靠拉感情了，就是跟人套关系、戴高帽。 +
**革命党人对这些帮会分子从一定意义上讲就是利用，他们并不会真的想要跟帮会共天下，或者起事成功后平分国家权力。**

'''
====

.如果没有外国的中立, 没有各省份的独立, 而没有去军事武力镇压起义者, 辛亥革命是不可能成功的.
[%collapsible%open]
====
武昌落入起义者的手中后 (10月10日), 外国领事宣布中立。它促使另外约二十个重要城巿或地区宣布反满. 到12月初, 所有南部和中部省份, 甚至包括西北部省份都宣告独立。

'''
====

.*袁世凯和其后继者, 都缺乏革命派所企望的那种"建立 Anglo-Saxon 盎格鲁–撤克逊式政府"所必备的法理依据, 而不得不依赖于武力维持统治。 共和制, 就变蜕变为军阀政府.*
[%collapsible%open]
====
辛亥革命后, 袁世凯与革命党人和清皇室, 都进行了公开或秘密的谈判, 并达成一项总的解决办法. +
清帝溥仪退位(1912.2.12)之后, 孙中山随即辞去临时总统的职务, 袁世凯被南京选为孙的继承人 (因为孙中山和同僚, 既没有掌握武装力量, 在各省又没有大批的支持者). 不过, 袁借口北京发生兵变, 不南下就职, 而在自己的势力范围北京就职, 按照《临时约法》进行统治, 直到选出国会, 和建立完全的立宪政府时为止.

但是, **袁世凯和其后继者, 都缺乏革命派所企望的那种"建立 Anglo-Saxon 盎格鲁–撤克逊式政府"所必备的法理依据, 而不得不依赖于武力维持统治。 共和制, 变蜕变为军阀政府.**

孙中山, 黄兴等老一辈的革命领导人, 不谙(ān 熟悉；懂得)治国之术,无力实现政党统治,甚至连这个要求也提不出。他们在这个问题上思想不明、目标未定、意见不一. 而且**政党制度, 也尚未在中国的条件下经过考验.**

**当时的所有政党, 只不过是由一群靠个人关系聚集到一起的上层人物的团体. 这些人并非从民选种产生, 因此他们缺乏选民的拥护、政治上的显赫地位和经验.**
'''
====

.★ 美国共和制, 应用到中国时, 遇到的中国问题阻力
[%collapsible%open]
====
共和制度, 是一个模仿美国建立的当时最先进的制度. 但应用到中国时，遇到了一些问题阻碍:

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|1.一个就是: **原有的忠诚和服从意识丧失，属下总是发生叛乱。所以若是某人当了某省或地区的督军，一般都要兼任一个主力师的师长，不然就有被人架空的危险 (枪杆子里面出政权)。**这种模式会不断向下复制，一个师长要想控制住自己的军队，必须兼任一个主力旅的旅长，而旅长又要兼任一个主力团的团长，循次往下，否则就没戏。
|这个问题, 中山没有机会也没有能力解决. 袁世凯是个政治强人，他也解决不了这个问题. 很多军阀也都被这个问题所困扰。吴佩孚为了解决这个问题，他的办法是重建传统秩序. 冯玉祥则借助基督教. 后来蒋介石找到了一个主义和一个党, 来建构一个忠诚体系，但这个体系远不够牢靠。

袁世凯死于1916年6月. 1916-1928年这段时期, 是军阀混战. **只拥有政党, 而不拥有军队的革命派, 无法获取政权; 只拥有军队, 而不拥有政党的军阀, 也同样无法获取政权.**

|2.对共和制的运作, 学习不够，经验不足，还在试用期，需要长期摸熟
|**国会的运作，行政权、立法权、司法权的分立制衡等到底该如何实际运作，中国人也一直不是很清楚 (即中国历史上就缺乏宪政文化, 所以中国人对此的知识储备为零, 只能重复踩坑来积累经验, 导致社会就会处在持续循环的”民主化”倾向与”专制化”倾向的摇摆中, 就好像一个人在学会走路之前, 必定会先踉踉跄跄的左一步, 右一步积累经验一样, 直到他最终掌握了平衡杆, 并将这种平衡杆内化到肌肉记忆(即社会拥有了”宪政文化和经验”后), 社会才会实现并运行平稳的民主统治方式)。**此前虽然有预备立宪的尝试，但这种尝试很短暂, 经验积累不够。而且，清末预备立宪的准议会, 和后来的国会也不一样. 所以**中国一下子改成共和制以后，民众对这套全新的架构不熟悉, 不知道总统是个什么样的职务. 所以各种纷扰(即磨合期)先后出现。**

当时的选举, 是由地方士绅负责操办的. 投票只是个过程，事实上是没有投的。因为地方士绅并不确定共和制是什么，更不清楚共和制下的国会是怎么一回事儿，所以他们倾向于选那些出头露面的革命党人, 或者是与革命有关系的人。很多代表都回忆说，他们是在家乡被提名为国会议员的，但他们既没有去竞选，也没有去拉票，什么都没搞，坐在北京就当上了国会议员。

|3.当选人权威性没有大到, 让政府和国会信服, 一致行动. 造成施政推进困难.
|.袁世凯
袁世凯虽然当上了正式大总统，但是**共和制所带来的那些问题依然困扰着他。包括他的官僚集团和他的亲信部下, 都出现了疑问：需不需要效忠？向谁效忠？忠于皇帝(帝制社会), 还是忠于国家人民 (民主社会)？**

袁世凯是没有权威的，他连那些当了国务总理或是各部总长的老朋友, 都控制不了，更不敢处理手握重兵的军头。这是北洋系统内部的问题，所谓的**内忧问题，主要集中在”权威性不够”这一点上。**也暴露出了袁世凯政权的虚弱性。

袁世凯很难对他的部下树立权威。有些人原来和袁世凯都是称兄道弟的，袁世凯当总统以后，不好直接拍桌子把这些人撤职。所以他想到借当皇帝, 来提高他的权威，因为再牛的人物跟他也是君臣关系了. (**这也解释了, 没有宪政的社会文化基础, 国家治理就会乱, 为了维稳, 逼得专制者出来解决问题, 结果社会就从”民主制度”变成”专制制度”.  所谓”一放(民主)就乱, 一抓(专政)就死”.**)

**但若是要建立新皇朝，你总得有一点点文治武功吧? (比如拿破仑.)** 但事实上，袁世凯两个方面都没有政治功绩，无论内政还是外交，都让人非常沮丧和焦虑。

**(但民主化的慢慢建成, 还是需要稳定的社会环境支撑. 而日本对华的侵略打破了这种环境的提供.) 即中国面临着当时的外部环境和世界秩序, 都不允许你慢慢变法图强。(可能就逼迫了袁世凯走向了极端路线, 来解决问题.)**

袁世凯死后, 各地割据军阀并起。袁世凯时代，各省的督军还多少对中央保持着一点服从，还能给中央上解一点钱粮税款，但是袁死后，这种事情就没了，**中央政府从此政令难出都门。**当然，也不是说中央完全控制不了地方，而是**要想控制，就得先给钱。往往地方从中央拿一万块钱，就给中央办一千块钱或者一百块钱的事儿 (严重缩水);** 要是中央不给钱，地方啥事也不办，中央政府对此毫无办法。整个体系，上下不服从的问题更为严重.

之前, 最牛的人是袁世凯，**其余所有人都是他提拔的，因此所有人都听命于他.  但在袁世凯死后，他的继承者就很难有这样的权威。**像北洋三杰龙虎狗，王士珍、冯国璋和段祺瑞，**大家平起平坐，而且跟他们资历基本相同的人还有很多，**比如张勋、陆建章、段芝贵等，其实有一大堆人，原来都是称兄道弟的，基本都差不多。这个时候要想从*矮*子里面拔将军，筷子里头挑旗杆, 谁能赶得上袁世凯的权威呢？

.段祺瑞
段祺瑞希望采取跟袁不一样的统治方式，尽量向民主共和方向靠拢，因而恢复了《临时约法》。《临时约法》**采用的是法国式的”内阁”政体. 如果强调责任内阁这一部分，那么总统就是虚位的, 而总理就是有实权的. 所以段祺瑞选择当有实权的总理.** 不过，**虽然段祺瑞认为中华民国采纳的是”内阁制”，但黎元洪坚持民国实行的是”总统制”。**事实上,民国初年的多党制实践, 已脱离了最初按美国经验设计的两党制模式**，**但**黎元洪等人仍然坚持总统应该握有实权。**这就是当时中国制度的含混之处，而这也种下了后来”府院之争”的伏笔。

段祺瑞跟国会的关系, 怎么协调也没法玩活，跟总统府也一直存在纠纷。后来他急了，**干脆还是来权术，**直接拉督军团，**让军人干政。**后来段祺瑞每次跟黎元洪的关系一紧张，就让督军团出面嚷嚷，黎元洪就软了。**这就是中国政治的一大难题，每逢当政者想按照民主的程序办事时，这套东西玩不转，而用传统的权术方式办理时，可能又会很灵。你让他怎么选择？**段祺瑞绕开民主规则的第一次成功，就是处理”府院之争”。

.府院之争 : 段祺瑞(总理) vs 黎元洪(总统)
第一次世界大战于1914年爆发，到1916年时，日本和美国都希望说服中国参战。因为这个时候欧战陷入了胶着状态，双方逐渐转入阵地战. 当地的民工不够了，缺乏挖战壕、抬伤员、运送枪弹的人手，这一系列的苦差事在当时欧洲也没人愿意干，于是一些国家就希望到中国招募华工. 但**如果中国不参战，那么他们从中国招募华工就很麻烦.**

**为了说服中国参战，列强肯定要做出一些让利条件允诺。**而段祺瑞政府此时又的确比较困窘，财政捉襟见肘. **列强开出的价码包括: 重新议定关税税率; 取消庚子赔款中, 中国需向同盟国偿付的赔款; 等等。协约国承诺，只要开战，中国就不必再向德国和奥匈帝国赔款了，**而向这两国偿付的庚款比例很大，一来一去就是不少钱。段祺瑞于是就想干。

而黎元洪则觉得德国不能惹, 提出中国只需跟德国及奥匈帝国断交就算了，起码应该保持中立姿态，但不能宣战. 黎元洪担心打不过德国人，到时候德国人卷土重来怎么办? 但是段祺瑞则是执意要打，结果就闹得非常僵。段祺瑞这次又找来督军团想压服黎元洪，但黎死活不同意. 最后闹翻了，黎元洪干脆就把段祺瑞的总理一职免了。

**其实，按照责任内阁体制的设计，总统是不能罢免总理的，罢免总理只能由国会通过不信任票决议。**段祺瑞被免了以后，各省的督军就都闹起独立来了，一则总统罢免总理不合法理，二则地方都不想跟着黎元洪干。督军团里的张勋就表示，可以担当总统府和国务院的调解人.

其实，督军团里并非没有比张勋更牛的人，**毕竟军人干政也不是件光彩的事儿，所以希望找个比较傻的人当头，可以让他承担大部分的风险，**所以就选中了张勋。

张勋一进京就闹复辟。黎元洪意识到了自己是引狼入室，赶紧逃命。他躲进日本使馆后就下了道命令，重新任命段祺瑞为国务总理，并委任他组织讨逆军. 总统则由副总统冯国璋代理。段祺瑞开始组织讨逆军，但手里既没有钱，又没有嫡系军队. 那个时候他跟曹汝霖关系很好，曹汝霖又跟日本人关系很好，于是曹汝霖就向日本三菱公司借了一百万，段祺瑞就开始到各方收买军队. 复辟就这么解决了. 段祺瑞就成了再造共和的英雄。而黎元洪也不可能再回来当总统了, 所以参加一次世界大战就没有问题了。中国正式参战，加入协约国，这一事件就种下了后来五四运动的伏笔。


|===

'''
====



== 民国

.三民主义思想, 是个内涵比较模糊的概念
[%collapsible%open]
====

清末, "中国该走何种政治道路”, 有着不同的思想竞争

**面临着上述这些竞争和机会, 孙中山提出了他自己的思想 -- 三民主义**(民族, 民权, 民生)。 **这三个概念的具体含义, 能在特定情况下做较大的变更.**

**孙中山**是一个外国化的中国人, 而**不是一个著名学者,他以他的密谋和果敢的行动而著称，而不以他的文章而闻名: 他确实有理论, 却失之于肤浅. 因此，他不能充当指导同辈人思想的理论家角色。** +
而**关于”共和主义”的新思想体系**, 是孙中山的副手 — 同盟会刊物《民报》的撰稿人 — **汪精卫和胡汉民等来建立的,** 通过抨击梁启超的”渐进改良”和”君主立宪”的思想, 同盟会成功赢得中国学生对一个引人入胜的论点的支持, 即中国通过一场迅疾的革命, 就能够赶上和超过西方(如同日本一样)。(事后证明这种想法太乐观了.)

孙中山实现民主的三阶段计划是：  +
1."军政之治" (3年), 各县逐一建立起地方自治政府. +
2."约法之治" (6年)，这一阶段也被称为“训要”. +
3."宪政之治",选举产生总统和国会。

'''
====






