
= (术) 让观众有代入感, 如何抓住观众的心?
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''



.掐住观众的咽喉，一刻都不松手。要逐渐将信息释放给观众 (即要一直吊着观众的胃口)
[%collapsible%open]
====

如何持久地把握住观众的好奇心? 一个好剧本，*要做到能掐住观众的咽喉，一刻都不松手。要逐渐将信息释放给观众 (即要一直吊着观众的胃口).* +
*每隔一段时间，这个剧本就应该释放足够的信息 → 让观众对接下来的故事发展保持好奇(吊胃口, 犹如爱丽丝漫游仙境一样, 一幕一幕都令人有悬疑感)，永远不觉得出戏、无聊或者毫无头绪。*


- 《唐人街》中，汤小心翼翼、一点一点地释放关于侦探杰克·盖特斯, 和他调查的洛杉矶富人家庭的信息，使观众全程保持精神集中，直到最终揭开真相。
- Manchester by the Sea 中，导演像折纸一样架构故事，随着折纸一点一点展开，我们也一步一步了解了钱德勒在几年前经历的惨剧。采用这个结构是因为钱德勒一直在想尽办法封闭这段记忆，埋藏过去的悔恨。换言之, 如果处理得当，影片的结构就是由角色的性格来决定的.

'''
====

.方法: 故事发生的环境要让人有"真实感”
[%collapsible%open]
====

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|▶ 这个世界好不好看不重要，重要的是它是否真实? *要真实到能够让观众相信, 并彻底沉浸其中.*
|<天国王朝>中, 那些环境场景, 真的让人如同回到了中世纪的欧洲

|▶ 画面的背景中, 发生了什么？告诉了我们什么？*画面的背景, 是在帮助叙事，还是分散了观众的注意力？*
|*这些环境能反映生活在其中的角色的个人特点，就好像我们的房子能反映我们的性格一样。* +
这就是普通的背景, 和优秀的艺术设计, 的区别 -- 前者是演员在静态背景下演戏，后者是在看得见、摸得着的世界中生活。

那些让人看完就忘的电影，里面所有的房子都带着千篇一律的白木桩围栏，所有的角色都穿着毫无特色的Dockers或者J.Jill 。这些片子的艺术指导, 没有为丰富"角色内涵"再做点儿什么，他们只是去商场买了点儿东西回来敷衍了事，除了搭建一个好看的背景供演员表演，他们什么也没做。

|▶ *艺术设计, 唤起了你的哪些感觉？它们反映出了怎样的情绪？*
|.好的艺术设计, 要能帮助叙事，而不是分散观众的注意力.
**艺术设计的最终目的, 不是为了表面上的搭建物理场景，而是为了传递重要的"心理和情感信息"。**最好的艺术设计, 是难以察觉、不着痕迹的，观众可能根本意识不到它的存在。但**艺术设计绝对不能完全消失，因为它有着"传递信息"和"表达情感"的作用。会对观众的"心理情绪"产生影响.**

后者才是本质目的，如同你建立自己的"设计方法论"时, 对"设计元素"的分解分析一样，看它们会带给人, 怎样不同的情绪体验, 这就是"各种元素"和"风格"所能起到的作用, 它们的价值所在. *如果这些东西不能给人带来你想要的情绪体验, 它们就没有存在价值.* 正如<大逃杀>中的核心观点 -- 要成为有生存价值的成年人(元素).


案例:

- 为了凸显人物在政府机构面前的渺小无力，艺术指导故意突出建筑物的高大冷酷，给它们涂上了一层法西斯的色彩。
- Stanley Kubrick 的电影, 一直都是利用夸张设计, 来激起观众强烈情感反应的. 如《The Shining‎ 闪灵》中阴森空荡的远望酒店. 酒店内新旧装饰元素的诡异交融、高得夸张的天花板、俗气的色彩搭配，以及反复出现的迷宫式设计母题 （motif），目的都是为了给观众, 营造出这样一种感觉 -- 好像被什么强大而邪恶的力量, 压得喘不过气来。


电影一定要尽量多给观众一点儿信息，用画面和信息淹没他们。如此一来，一部电影便可以重复欣赏，影迷每次重看都会有新的发现。


.不同颜色或色调, 会带来何种的象征意义和情感? 会触发观众相应的反应。
这些色彩是在帮助叙事，还是衬托、暗示当下已经很明显的情绪和信息？


案例:

- <Precious> 讲述的是一个被贫穷与家庭暴力围绕的女孩的成长故事。但导演依然使用了鲜艳的背景色, 目的是想要捕捉她在不屈不挠、努力求生中, 展现出的活力与乐观精神. “我们既要展现痛苦，也要展现美丽。”

|===


所以, 设计部门和美术部门最累. +
对细节的打磨，导致设计部门和美术部门通常都是最早开工. -- "我们会尽力为后来者设立一个高标杆，这样一来，任何人都没有理由偷懒", "这也是为什么我们把那么多的时间都花在素材积累上".

'''
====

.电影一定要尽量多给观众一点儿信息，用画面和信息淹没他们。如此一来，一部电影便可以重复欣赏，影迷每次重看都会有新的发现。
[%collapsible%open]
====
除了演员，艺术设计的**所有重要细节, 都要让肉眼轻松捕捉，让观众能够获取他们需要的信息和情报，** 其中包括自然背景、人造环境、道具、服装，以及能够传达故事背景及潜台词的各种细节。 +
虽然有时候, 细节并不一定要被观众注意到，但是**如果好不容易精心挑选出了一屋子的装饰品，最后都隐藏在阴沉昏暗的灯光之中，那又何必费这个心呢？**

'''
====

.方法: 攻心. 让观众对主角的命运产生关心
[%collapsible%open]
====

*只有当你(观众)对这些人(角色)产生了关心, 你才会进一步关心和主角相关的一切.* +
*所以在电影的开场处, 就要让主角有足够的吸引力或角色深度，让观众愿意跟随主角到天涯海角 (如同你对情人一样)*（或者至少跟到影片结束）。

即使是塑造令人讨厌的角色，好的编剧也要赋予他值得同情的点。因为如果没有这些特点，编剧对这些角色, 就不会有兴趣去塑造. (即使是反派, 也要有魅力. 有魅力的反派更能衬托主角的魅力, 人是互相抬高的. 优秀的敌人能衬托出你更优秀.)

- Angelina Jolie 在 <Salt 特工绍特> 中，她扮演了一个俄国间谍。这样的角色一般并不需要太多观众的共情，但**没有共情, 演员就很难与观众形成情感联系.** Angelina Jolie 想要搭建这种联系, 所以其实这个角色身上很多极端的地方, 都是她自己塑造的.

'''
====

.方法: 人的魅力来源于"看不透", 和"难以预测", 这些心理学
[%collapsible%open]
====
角色让人真实可信, 又觉得难以预测 (难以预测才会带来性格魅力). +
*神秘感起到了重要的作用：伟大的演员能不断勾起我们的好奇心.* +
既要"透明"到能让观众瞬间了解角色，又要"内敛"到让观众好奇角色下一步会怎么做。

'''
====

.方法: 用“局内人”视角, 让观众更有代入感
[%collapsible%open]
====

要清楚电影的视角：是谁在银幕世界中引领观众？我们是透过谁的眼睛和情感, 来看待故事中的矛盾冲突、悲欢离合、失败与成功的？要确保“从剧本到片场”（再到银幕）全程视角一致。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|视角有两种:
|1.某个角色的主观视角 (局内人视角) +
2.如上帝般, 冷眼旁观的视角 (局外人视角)


案例:

- 《拆弹部队》的视角类似于第三方的记者视角，从来没出现全知视角（omniscient eye）——即镜头永远不会拉到一定距离之外，用“上帝视角”来观察银幕上发生的一切.
- 《后窗》几乎全程都是通过主角视角来进行叙事。镜头全程陪伴杰弗里斯，我们只能见其所见，闻其所闻. 但在影片的某一个场景中，*趁着杰弗里斯入睡，镜头向观众透露了一条关键信息。这条信息对于观众理解整个故事有着重要作用，但是主角自己并不知情。这是一招不着痕迹的作弊手法，目的是让观众对接下来的故事走向更加好奇。*


通常来说，优秀的导演手法, 应该介于这两种极端之间 —— 私密但持重；客观但不冷淡；处在一定距离外冷静观察，但仍保持尊重与同情。


|镜头目标, 声音, 都能表达出"以谁为视角?”
|摄影机摆在哪里，*镜头反映的是谁的视点，观众是通过谁的耳朵听声音，电影配乐是在传达谁的内心情感，都取决于角色和角色视角。* (红楼梦中, 第二次, 读者是跟着刘姥姥的目光与感受, 来体验大观园的)

|好的艺术设计, 还能进入主角的视角。
|
- <Black Swan> 中, 通过对镜子、窗子等带反射面的母题运用，来展现一位芭蕾舞女演员的心灵走向崩溃的过程。
|===

'''
====

.观众的自我想法, 也在帮助塑造角色 (一千个读者心中有一千个阿姆雷特)
[%collapsible%open]
====

- 你可以通过看得见的东西讲故事，也可以通过看不见的东西讲故事，如果你把什么都展现给观众, 那就没有什么东西是重要的了 (没有了观众能参与的想象力了).
- 从这一刻起，观众也加入进来，赋予这个之前只存在于纸页上的角色, 更多的含义，和演员一起塑造角色。
你(观众)看完电影后，也会往角色身上加上自己的想法(你自己对角色的人物分析)。你也同时在为演员充实这个角色。

'''
====

